//! FrozenHir → Chisel Scala (FR28 mechanical + FR97 idiomatic / AD-27).
//! Interop contract for FIRRTL text remains FrozenHir ↔ FIRRTL 6 (AD-3).
//! FR81 Path A: documented Mem/SyncReadMem subset lowers here; out-of-subset → E0901.

use std::collections::HashMap;

use bitloom_hir::{
    Artifact, AssignExpr, AssignTarget, EmittedFile, FrozenHir, GroundType, Module, PortConnect,
    PortDirection, ProcessKind, Stmt,
};

/// Documented pairing (AD-9 / NFR12): Chisel 7.14.0 ↔ firtool-1.155.0.
pub const CHISEL_TARGET: &str = "7.14.0";

/// Documented firtool pin paired with [`CHISEL_TARGET`].
pub const FIRTOOL_TARGET: &str = "1.155.0";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChiselGenError {
    pub code: String,
    pub en: String,
    pub zh: String,
}

impl std::fmt::Display for ChiselGenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {} ({})", self.code, self.en, self.zh)
    }
}

impl std::error::Error for ChiselGenError {}

/// Idiomatic / FR97 acceptance failure (readable; never silent Ok).
pub type IdiomaticCheckError = ChiselGenError;

fn e0901(name: &str, reason_en: &str, reason_zh: &str) -> ChiselGenError {
    ChiselGenError {
        code: "rhdl::E0901".into(),
        en: format!("Chisel emit does not lower mem `{name}` ({reason_en})"),
        zh: format!("Chisel 发射不降低 mem `{name}`（{reason_zh}）"),
    }
}

fn e0904(en: &str, zh: &str) -> IdiomaticCheckError {
    IdiomaticCheckError {
        code: "rhdl::E0904".into(),
        en: en.to_string(),
        zh: zh.to_string(),
    }
}

/// FR81 Path A: single-clock `Mem` / `SyncReadMem` (+ optional constant init).
/// Returns `Err` with E0901 when outside that subset (do not delete wholesale).
fn mem_path_a_ok(depth: u32, width: u32, init: &Option<Vec<u64>>) -> Result<(), &'static str> {
    if depth == 0 || width == 0 {
        return Err("depth/width must be non-zero for Path A subset");
    }
    if let Some(words) = init {
        if words.len() != depth as usize {
            return Err("init length does not match depth (out of Path A subset)");
        }
    }
    Ok(())
}

#[derive(Clone, Copy)]
enum EmitFace {
    /// FR28 / FR46 mechanical compilable (not FR97).
    Mechanical,
    /// FR97 idiomatic / maintainable (naming + structure + readability).
    Idiomatic,
}

fn preflight(hir: &FrozenHir) -> Result<HashMap<&str, &Module>, ChiselGenError> {
    let modules_by_name: HashMap<&str, &Module> = hir
        .circuit()
        .modules
        .iter()
        .map(|m| (m.name.as_str(), m))
        .collect();

    for m in &hir.circuit().modules {
        for stmt in &m.body {
            match stmt {
                Stmt::MemDecl {
                    name,
                    depth,
                    width,
                    init,
                    ..
                } => {
                    if let Err(reason) = mem_path_a_ok(*depth, *width, init) {
                        return Err(e0901(name, reason, "子集外或不合法 MemDecl"));
                    }
                }
                Stmt::Instance(inst) if !modules_by_name.contains_key(inst.module.as_str()) => {
                    return Err(ChiselGenError {
                        code: "rhdl::E0903".into(),
                        en: format!(
                            "instance `{}` references unknown module `{}`",
                            inst.name, inst.module
                        ),
                        zh: format!("实例 `{}` 引用未知模块 `{}`", inst.name, inst.module),
                    });
                }
                _ => {}
            }
        }
    }
    Ok(modules_by_name)
}

fn emit_with_face(hir: &FrozenHir, face: EmitFace) -> Result<Artifact, ChiselGenError> {
    let modules_by_name = preflight(hir)?;
    let mut body = match face {
        EmitFace::Mechanical => format!(
            "// generated by bitloom; target Chisel {CHISEL_TARGET} (firtool-{FIRTOOL_TARGET} pair)\n\
             // FR28 compilable Chisel — FrozenHir ↔ FIRRTL 6.0.0 text remains AD-3\n\
             // FR81 Path A: Mem/SyncReadMem (+ optional constant init)\n\
             // mechanical ≠ idiomatic — use emit_chisel_idiomatic for the maintainable face\n\
             import chisel3._\n\n"
        ),
        EmitFace::Idiomatic => format!(
            "// generated by Bitloom; target Chisel {CHISEL_TARGET} (firtool-{FIRTOOL_TARGET} pair)\n\
             // FR97 idiomatic / maintainable Chisel (AD-27 revised) — beyond FR28 mechanical\n\
             // Naming: HIR public module/port/instance names preserved (clk/rst → clock/reset)\n\
             // Structure: Module + IO Bundle + sectioned body; Readable: grouped comments\n\
             // FIRRTL text contract remains AD-3; Parser.parse not required\n\
             import chisel3._\n\n"
        ),
    };
    for m in &hir.circuit().modules {
        body.push_str(&emit_module(m, &modules_by_name, face));
        body.push('\n');
    }
    let path = format!("{}.scala", hir.abi_name);
    Ok(Artifact {
        files: vec![EmittedFile {
            path: path.clone(),
            contents: body,
        }],
        filelist: vec![path],
    })
}

/// Emit mechanical-style Chisel Scala accepted under the pinned Chisel+firtool stack.
///
/// FR81 Path A: `MemDecl` with valid depth/width/(optional matching init) lowers to
/// Chisel `Mem` / `SyncReadMem`. Out-of-subset `MemDecl` fails with `rhdl::E0901`.
/// Hierarchy with instances is in scope for FR28 (no E0902).
///
/// **Not FR97:** this face is compilable ≠ idiomatic. Use [`emit_chisel_idiomatic`].
pub fn emit_chisel(hir: &FrozenHir) -> Result<Artifact, ChiselGenError> {
    emit_with_face(hir, EmitFace::Mechanical)
}

/// Emit FR97 idiomatic / maintainable Chisel Scala (AD-27 revised).
///
/// Satisfies NFR14 Epic 42 naming + structure + readability predicates when checked with
/// [`check_idiomatic_chisel`]. Does not claim Chisel official Style Guide unless documented.
pub fn emit_chisel_idiomatic(hir: &FrozenHir) -> Result<Artifact, ChiselGenError> {
    emit_with_face(hir, EmitFace::Idiomatic)
}

/// Assert FR97 idiomatic acceptance criteria against emitted Scala + FrozenHir.
///
/// Mechanical [`emit_chisel`] output must fail here (explicit downgrade / no silent claim).
pub fn check_idiomatic_chisel(scala: &str, hir: &FrozenHir) -> Result<(), IdiomaticCheckError> {
    let lower = scala.to_lowercase();

    // Require contiguous positive claim — mechanical headers may mention "≠ idiomatic / FR97"
    // as a downgrade notice and must still fail.
    let claims_fr97 = scala.contains("FR97 idiomatic")
        || scala.contains("FR97 Idiomatic")
        || (scala.contains("FR97") && scala.contains("可维护"));
    if !claims_fr97 {
        return Err(e0904(
            "idiomatic check failed: Scala lacks FR97 idiomatic header (mechanical FR28 output is not FR97)",
            "idiomatic 验收失败：Scala 缺少 FR97 idiomatic 头（机械 FR28 产出不算 FR97）",
        ));
    }

    if scala.contains("FR28 compilable") {
        return Err(e0904(
            "idiomatic check failed: mechanical FR28 face must not claim FR97",
            "idiomatic 验收失败：机械 FR28 面不得宣称 FR97",
        ));
    }

    if scala.lines().count() <= 8 {
        return Err(e0904(
            "idiomatic check failed: output looks like a non-readable single dump (too few lines)",
            "idiomatic 验收失败：产出行数过少，不像可维护分节结构",
        ));
    }

    let has_io_section = lower.contains("--- io ---");
    if !has_io_section {
        return Err(e0904(
            "idiomatic check failed: missing readable // --- IO --- section marker",
            "idiomatic 验收失败：缺少可读 // --- IO --- 分节注释",
        ));
    }

    // Require body section markers for stmt kinds present in HIR (not just always-on IO).
    let mut need_registers = false;
    let mut need_wires = false;
    let mut need_instances = false;
    let mut need_logic = false;
    let mut need_memories = false;
    let mut has_clk_or_rst = false;
    for m in &hir.circuit().modules {
        for p in &m.ports {
            if p.name == "clk" || p.name == "rst" {
                has_clk_or_rst = true;
            }
        }
        for stmt in &m.body {
            match stmt {
                Stmt::RegDecl { .. } => need_registers = true,
                Stmt::WireDecl { .. } => need_wires = true,
                Stmt::Instance(_) => need_instances = true,
                Stmt::Process(_) => need_logic = true,
                Stmt::MemDecl { .. } => need_memories = true,
            }
        }
    }
    let missing = [
        (need_registers, "--- registers ---"),
        (need_wires, "--- wires ---"),
        (need_instances, "--- instances ---"),
        (need_logic, "--- logic ---"),
        (need_memories, "--- memories ---"),
    ]
    .into_iter()
    .filter(|(need, marker)| *need && !lower.contains(marker))
    .map(|(_, marker)| marker)
    .collect::<Vec<_>>();
    if !missing.is_empty() {
        return Err(e0904(
            &format!(
                "idiomatic check failed: missing body section marker(s) required by HIR: {}",
                missing.join(", ")
            ),
            &format!(
                "idiomatic 验收失败：HIR 要求的正文分节缺失：{}",
                missing.join(", ")
            ),
        ));
    }

    if has_clk_or_rst && !(scala.contains("clock") || scala.contains("reset")) {
        // Modules with only clk/rst (no other ports) still map via Chisel implicit clock/reset;
        // presence of the words in comments/header is weak — prefer body uses when non-clk ports exist.
        // Accept either Chisel implicit use in connects or documented mapping comment in header.
        if !scala.contains("clk/rst") && !scala.contains("clock/reset") {
            return Err(e0904(
                "idiomatic check failed: clk/rst present in HIR but no clock/reset mapping evidence",
                "idiomatic 验收失败：HIR 含 clk/rst 但未见 clock/reset 映射证据",
            ));
        }
    }

    if !scala.to_lowercase().contains("bitloom") {
        return Err(e0904(
            "idiomatic check failed: Scala must cite Bitloom brand",
            "idiomatic 验收失败：Scala 须标明 Bitloom 品牌",
        ));
    }

    for m in &hir.circuit().modules {
        if !scala.contains(&format!("class {} extends Module", m.name)) {
            return Err(e0904(
                &format!(
                    "idiomatic check failed: missing Module class for HIR name `{}`",
                    m.name
                ),
                &format!(
                    "idiomatic 验收失败：缺少与 HIR 名 `{}` 对应的 Module class",
                    m.name
                ),
            ));
        }
        if !scala.contains("IO(new Bundle") {
            return Err(e0904(
                "idiomatic check failed: missing IO(new Bundle) structure",
                "idiomatic 验收失败：缺少 IO(new Bundle) 结构",
            ));
        }
        for p in &m.ports {
            if p.name == "clk" || p.name == "rst" {
                continue;
            }
            let dir = match p.direction {
                PortDirection::Input => "Input",
                PortDirection::Output => "Output",
                PortDirection::InOut => "Analog",
            };
            let needle = format!("val {} = {dir}(", p.name);
            if !scala.contains(&needle) {
                return Err(e0904(
                    &format!(
                        "idiomatic check failed: port `{}` not found as `val {} = {dir}(` (naming)",
                        p.name, p.name
                    ),
                    &format!(
                        "idiomatic 验收失败：端口 `{}` 未以 `val {} = {dir}(` 出现（命名）",
                        p.name, p.name
                    ),
                ));
            }
        }
        for stmt in &m.body {
            if let Stmt::Instance(inst) = stmt {
                if !scala.contains(&format!("val {} = Module(new {})", inst.name, inst.module)) {
                    return Err(e0904(
                        &format!(
                            "idiomatic check failed: instance `{}` / module `{}` naming mismatch",
                            inst.name, inst.module
                        ),
                        &format!(
                            "idiomatic 验收失败：实例 `{}` / 模块 `{}` 命名不一致",
                            inst.name, inst.module
                        ),
                    ));
                }
            }
        }
    }

    Ok(())
}

fn chisel_ty(ty: &GroundType) -> String {
    match ty {
        GroundType::UInt { width } => format!("UInt({width}.W)"),
        GroundType::SInt { width } => format!("SInt({width}.W)"),
        GroundType::Clock => "Clock()".into(),
        GroundType::Reset => "Reset()".into(),
        GroundType::Bool => "Bool()".into(),
        GroundType::Analog => "Analog()".into(),
    }
}

fn ref_name(m: &Module, n: &str) -> String {
    if n == "clk" {
        "clock".into()
    } else if n == "rst" {
        "reset".into()
    } else if m.ports.iter().any(|p| p.name == n) {
        format!("io.{n}")
    } else {
        n.to_string()
    }
}

fn emit_expr(m: &Module, expr: &AssignExpr) -> String {
    match expr {
        AssignExpr::Ref(n) => ref_name(m, n),
        AssignExpr::Lit(v) => format!("{v}.U"),
        AssignExpr::Inc(n) => format!("{} + 1.U", ref_name(m, n)),
        AssignExpr::Add(a, b) => format!("{} + {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Sub(a, b) => format!("{} - {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::And(a, b) => format!("{} & {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Or(a, b) => format!("{} | {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Xor(a, b) => format!("{} ^ {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Shl(a, b) => format!("{} << {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Shr(a, b) => format!("{} >> {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Eq(a, b) => format!("{} === {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Mux { sel, t, f } => format!(
            "Mux({}, {}, {})",
            ref_name(m, sel),
            ref_name(m, t),
            ref_name(m, f)
        ),
        // Mem: combinational read; SyncReadMem: sync read (latency 1) via same API.
        AssignExpr::MemRead { mem, addr } => {
            format!("{mem}.read({})", ref_name(m, addr))
        }
    }
}

fn emit_instance_connects(
    parent: &Module,
    inst_name: &str,
    child: &Module,
    connects: &[PortConnect],
) -> String {
    let mut out = String::new();
    for c in connects {
        if c.dangling || c.child_port == "clk" || c.child_port == "rst" {
            continue;
        }
        let Some(port) = child.ports.iter().find(|p| p.name == c.child_port) else {
            continue;
        };
        let parent_ref = ref_name(parent, &c.parent_net);
        let child_io = format!("{inst_name}.io.{}", c.child_port);
        match port.direction {
            PortDirection::Input => {
                out.push_str(&format!("  {child_io} := {parent_ref}\n"));
            }
            PortDirection::Output => {
                out.push_str(&format!("  {parent_ref} := {child_io}\n"));
            }
            PortDirection::InOut => {
                out.push_str(&format!(
                    "  // inout skipped: {child_io} <-> {parent_ref}\n"
                ));
            }
        }
    }
    out
}

fn emit_mem_decl(
    name: &str,
    depth: u32,
    width: u32,
    sync_read: bool,
    init: &Option<Vec<u64>>,
) -> String {
    let ctor = if sync_read { "SyncReadMem" } else { "Mem" };
    let mut out = format!("  val {name} = {ctor}({depth}, UInt({width}.W))\n");
    if let Some(words) = init {
        let lits: Vec<String> = words.iter().map(|w| format!("{w}.U({width}.W)")).collect();
        out.push_str(&format!(
            "  val {name}_init = VecInit({})\n",
            lits.join(", ")
        ));
        out.push_str(&format!(
            "  when (reset.asBool) {{\n    for (i <- 0 until {depth}) {{\n      {name}.write(i.U, {name}_init(i))\n    }}\n  }}\n"
        ));
    }
    out
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum BodySection {
    None,
    Memories,
    Registers,
    Wires,
    Instances,
    Logic,
}

fn emit_module(m: &Module, modules_by_name: &HashMap<&str, &Module>, face: EmitFace) -> String {
    let mut io_fields = String::new();
    for p in &m.ports {
        if p.name == "clk" || p.name == "rst" {
            continue;
        }
        let dir = match p.direction {
            PortDirection::Input => "Input",
            PortDirection::Output => "Output",
            PortDirection::InOut => "Analog",
        };
        io_fields.push_str(&format!(
            "    val {} = {dir}({})\n",
            p.name,
            chisel_ty(&p.ty)
        ));
    }
    let mut body = match face {
        EmitFace::Mechanical => format!(
            "class {} extends Module {{\n  val io = IO(new Bundle {{\n{io_fields}  }})\n",
            m.name
        ),
        EmitFace::Idiomatic => format!(
            "class {} extends Module {{\n  // --- IO ---\n  val io = IO(new Bundle {{\n{io_fields}  }})\n",
            m.name
        ),
    };

    let mut section = BodySection::None;
    let mut enter = |body: &mut String, next: BodySection, label: &str| {
        if matches!(face, EmitFace::Idiomatic) && section != next {
            body.push_str(&format!("  // --- {label} ---\n"));
            section = next;
        }
    };

    for stmt in &m.body {
        match stmt {
            Stmt::RegDecl { name, ty, .. } => {
                enter(&mut body, BodySection::Registers, "registers");
                let w = match ty {
                    GroundType::UInt { width } | GroundType::SInt { width } => *width,
                    _ => 1,
                };
                body.push_str(&format!("  val {name} = RegInit(0.U({w}.W))\n"));
            }
            Stmt::WireDecl { name, ty, .. } => {
                enter(&mut body, BodySection::Wires, "wires");
                body.push_str(&format!("  val {name} = Wire({})\n", chisel_ty(ty)));
            }
            Stmt::Process(p) => {
                enter(&mut body, BodySection::Logic, "logic");
                for a in &p.assigns {
                    match (&a.target, p.kind) {
                        (AssignTarget::Net(n), ProcessKind::Combinational)
                        | (AssignTarget::RegD(n), ProcessKind::Sequential) => {
                            body.push_str(&format!(
                                "  {} := {}\n",
                                ref_name(m, n),
                                emit_expr(m, &a.expr)
                            ));
                        }
                        (AssignTarget::MemWrite { mem, addr, we }, ProcessKind::Sequential) => {
                            let write = format!(
                                "{mem}.write({}, {})",
                                ref_name(m, addr),
                                emit_expr(m, &a.expr)
                            );
                            match we {
                                Some(en) => {
                                    body.push_str(&format!(
                                        "  when ({}) {{\n    {write}\n  }}\n",
                                        ref_name(m, en)
                                    ));
                                }
                                None => {
                                    body.push_str(&format!("  {write}\n"));
                                }
                            }
                        }
                        _ => {}
                    }
                }
            }
            Stmt::Instance(inst) => {
                enter(&mut body, BodySection::Instances, "instances");
                let child = modules_by_name
                    .get(inst.module.as_str())
                    .expect("preflight rejects unknown module refs");
                body.push_str(&format!(
                    "  val {} = Module(new {})\n",
                    inst.name, inst.module
                ));
                body.push_str(&emit_instance_connects(
                    m,
                    &inst.name,
                    child,
                    &inst.connects,
                ));
            }
            Stmt::MemDecl {
                name,
                depth,
                width,
                sync_read,
                init,
                ..
            } => {
                enter(&mut body, BodySection::Memories, "memories");
                // Preflight already enforced Path A; emit Mem / SyncReadMem.
                body.push_str(&emit_mem_decl(name, *depth, *width, *sync_read, init));
            }
        }
    }
    body.push_str("}\n");
    body
}
