//! FrozenHir → compilable Chisel Scala (FR28 / AD-27).
//! Interop contract for FIRRTL text remains FrozenHir ↔ FIRRTL 6 (AD-3).

use std::collections::HashMap;

use bitloom_hir::{
    Artifact, AssignExpr, AssignTarget, EmittedFile, FrozenHir, GroundType, Module, PortConnect,
    PortDirection, ProcessKind, Stmt,
};

/// Documented pairing (AD-9 / NFR12): Chisel 7.14.0 ↔ firtool-1.155.0.
pub const CHISEL_TARGET: &str = "7.14.0";

/// Documented firtool pin paired with [`CHISEL_TARGET`].
pub const FIRTOOL_TARGET: &str = "1.155.0";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChiselGenError {
    pub code: String,
    pub en: String,
    pub zh: String,
}

impl std::fmt::Display for ChiselGenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {} ({})", self.code, self.en, self.zh)
    }
}

impl std::error::Error for ChiselGenError {}

/// Emit mechanical-style Chisel Scala accepted under the pinned Chisel+firtool stack.
///
/// Unsupported subset (e.g. `MemDecl`) fails with a structured error. Hierarchy with
/// instances is in scope for FR28 (no E0902).
pub fn emit_chisel(hir: &FrozenHir) -> Result<Artifact, ChiselGenError> {
    let modules_by_name: HashMap<&str, &Module> = hir
        .circuit()
        .modules
        .iter()
        .map(|m| (m.name.as_str(), m))
        .collect();

    for m in &hir.circuit().modules {
        for stmt in &m.body {
            match stmt {
                Stmt::MemDecl { name, .. } => {
                    return Err(ChiselGenError {
                        code: "rhdl::E0901".into(),
                        en: format!("Chisel emit does not lower mem `{name}` (unsupported subset)"),
                        zh: format!("Chisel 发射不降低 mem `{name}`（子集外）"),
                    });
                }
                Stmt::Instance(inst) if !modules_by_name.contains_key(inst.module.as_str()) => {
                    return Err(ChiselGenError {
                        code: "rhdl::E0903".into(),
                        en: format!(
                            "instance `{}` references unknown module `{}`",
                            inst.name, inst.module
                        ),
                        zh: format!("实例 `{}` 引用未知模块 `{}`", inst.name, inst.module),
                    });
                }
                _ => {}
            }
        }
    }

    let mut body = format!(
        "// generated by bitloom; target Chisel {CHISEL_TARGET} (firtool-{FIRTOOL_TARGET} pair)\n\
         // FR28 compilable Chisel — FrozenHir ↔ FIRRTL 6.0.0 text remains AD-3\n\
         import chisel3._\n\n"
    );
    for m in &hir.circuit().modules {
        body.push_str(&emit_module(m, &modules_by_name));
        body.push('\n');
    }
    let path = format!("{}.scala", hir.abi_name);
    Ok(Artifact {
        files: vec![EmittedFile {
            path: path.clone(),
            contents: body,
        }],
        filelist: vec![path],
    })
}

fn chisel_ty(ty: &GroundType) -> String {
    match ty {
        GroundType::UInt { width } => format!("UInt({width}.W)"),
        GroundType::SInt { width } => format!("SInt({width}.W)"),
        GroundType::Clock => "Clock()".into(),
        GroundType::Reset => "Reset()".into(),
        GroundType::Bool => "Bool()".into(),
        GroundType::Analog => "Analog()".into(),
    }
}

fn ref_name(m: &Module, n: &str) -> String {
    if n == "clk" {
        "clock".into()
    } else if n == "rst" {
        "reset".into()
    } else if m.ports.iter().any(|p| p.name == n) {
        format!("io.{n}")
    } else {
        n.to_string()
    }
}

fn emit_expr(m: &Module, expr: &AssignExpr) -> String {
    match expr {
        AssignExpr::Ref(n) => ref_name(m, n),
        AssignExpr::Lit(v) => format!("{v}.U"),
        AssignExpr::Inc(n) => format!("{} + 1.U", ref_name(m, n)),
        AssignExpr::Add(a, b) => format!("{} + {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Sub(a, b) => format!("{} - {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::And(a, b) => format!("{} & {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Or(a, b) => format!("{} | {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Xor(a, b) => format!("{} ^ {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Shl(a, b) => format!("{} << {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Shr(a, b) => format!("{} >> {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Eq(a, b) => format!("{} === {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::Mux { sel, t, f } => format!(
            "Mux({}, {}, {})",
            ref_name(m, sel),
            ref_name(m, t),
            ref_name(m, f)
        ),
        AssignExpr::MemRead { mem, addr } => format!("{mem}({})", ref_name(m, addr)),
    }
}

fn emit_instance_connects(
    parent: &Module,
    inst_name: &str,
    child: &Module,
    connects: &[PortConnect],
) -> String {
    let mut out = String::new();
    for c in connects {
        if c.dangling || c.child_port == "clk" || c.child_port == "rst" {
            continue;
        }
        let Some(port) = child.ports.iter().find(|p| p.name == c.child_port) else {
            continue;
        };
        let parent_ref = ref_name(parent, &c.parent_net);
        let child_io = format!("{inst_name}.io.{}", c.child_port);
        match port.direction {
            PortDirection::Input => {
                out.push_str(&format!("  {child_io} := {parent_ref}\n"));
            }
            PortDirection::Output => {
                out.push_str(&format!("  {parent_ref} := {child_io}\n"));
            }
            PortDirection::InOut => {
                out.push_str(&format!(
                    "  // inout skipped: {child_io} <-> {parent_ref}\n"
                ));
            }
        }
    }
    out
}

fn emit_module(m: &Module, modules_by_name: &HashMap<&str, &Module>) -> String {
    let mut io_fields = String::new();
    for p in &m.ports {
        if p.name == "clk" || p.name == "rst" {
            continue;
        }
        let dir = match p.direction {
            PortDirection::Input => "Input",
            PortDirection::Output => "Output",
            PortDirection::InOut => "Analog",
        };
        io_fields.push_str(&format!(
            "    val {} = {dir}({})\n",
            p.name,
            chisel_ty(&p.ty)
        ));
    }
    let mut body = format!(
        "class {} extends Module {{\n  val io = IO(new Bundle {{\n{io_fields}  }})\n",
        m.name
    );
    for stmt in &m.body {
        match stmt {
            Stmt::RegDecl { name, ty, .. } => {
                let w = match ty {
                    GroundType::UInt { width } | GroundType::SInt { width } => *width,
                    _ => 1,
                };
                body.push_str(&format!("  val {name} = RegInit(0.U({w}.W))\n"));
            }
            Stmt::WireDecl { name, ty, .. } => {
                body.push_str(&format!("  val {name} = Wire({})\n", chisel_ty(ty)));
            }
            Stmt::Process(p) => {
                for a in &p.assigns {
                    match (&a.target, p.kind) {
                        (AssignTarget::Net(n), ProcessKind::Combinational)
                        | (AssignTarget::RegD(n), ProcessKind::Sequential) => {
                            body.push_str(&format!(
                                "  {} := {}\n",
                                ref_name(m, n),
                                emit_expr(m, &a.expr)
                            ));
                        }
                        (AssignTarget::MemWrite { mem, addr, we }, ProcessKind::Sequential) => {
                            let gate = we
                                .as_ref()
                                .map(|e| format!(" if {}", ref_name(m, e)))
                                .unwrap_or_default();
                            body.push_str(&format!(
                                "  // mem write{gate} {mem}({}) := {}\n",
                                ref_name(m, addr),
                                emit_expr(m, &a.expr)
                            ));
                        }
                        _ => {}
                    }
                }
            }
            Stmt::Instance(inst) => {
                let child = modules_by_name
                    .get(inst.module.as_str())
                    .expect("preflight rejects unknown module refs");
                body.push_str(&format!(
                    "  val {} = Module(new {})\n",
                    inst.name, inst.module
                ));
                body.push_str(&emit_instance_connects(
                    m,
                    &inst.name,
                    child,
                    &inst.connects,
                ));
            }
            Stmt::MemDecl { .. } => {
                // Pre-checked in emit_chisel.
            }
        }
    }
    body.push_str("}\n");
    body
}
