//! Best-effort FrozenHir → Chisel Scala (FR28). Not a round-trip contract (AD-3).

use bitloom_hir::{
    Artifact, AssignExpr, AssignTarget, EmittedFile, FrozenHir, GroundType, Module, PortDirection,
    ProcessKind, Stmt,
};

/// Documented pairing (AD-9 / NFR12): Chisel 7.14.0 ↔ firtool-1.155.0.
pub const CHISEL_TARGET: &str = "7.14.0";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChiselGenError {
    pub code: String,
    pub en: String,
    pub zh: String,
}

impl std::fmt::Display for ChiselGenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {} ({})", self.code, self.en, self.zh)
    }
}

impl std::error::Error for ChiselGenError {}

/// Best-effort Chisel Scala. Interop contract remains FrozenHir ↔ FIRRTL 6 text.
pub fn emit_chisel(hir: &FrozenHir) -> Result<Artifact, ChiselGenError> {
    for m in &hir.circuit().modules {
        for stmt in &m.body {
            match stmt {
                Stmt::MemDecl { name, .. } => {
                    return Err(ChiselGenError {
                        code: "rhdl::E0901".into(),
                        en: format!("best-effort Chisel gen does not lower mem `{name}`"),
                        zh: format!("尽力 Chisel 生成不降低 mem `{name}`"),
                    });
                }
                Stmt::Instance(inst) => {
                    return Err(ChiselGenError {
                        code: "rhdl::E0902".into(),
                        en: format!(
                            "best-effort Chisel gen does not lower instance `{}`",
                            inst.name
                        ),
                        zh: format!("尽力 Chisel 生成不降低实例 `{}`", inst.name),
                    });
                }
                _ => {}
            }
        }
    }
    let mut body = format!(
        "// generated by rhdl; target Chisel {CHISEL_TARGET} (firtool-1.155.0 pair)\n\
         // NOT a round-trip contract — FrozenHir ↔ FIRRTL 6.0.0 text remains AD-3\n\
         import chisel3._\n\n"
    );
    for m in &hir.circuit().modules {
        body.push_str(&emit_module(m));
        body.push('\n');
    }
    let path = format!("{}.scala", hir.abi_name);
    Ok(Artifact {
        files: vec![EmittedFile {
            path: path.clone(),
            contents: body,
        }],
        filelist: vec![path],
    })
}

fn chisel_ty(ty: &GroundType) -> String {
    match ty {
        GroundType::UInt { width } => format!("UInt({width}.W)"),
        GroundType::SInt { width } => format!("SInt({width}.W)"),
        GroundType::Clock => "Clock()".into(),
        GroundType::Reset => "Reset()".into(),
        GroundType::Bool => "Bool()".into(),
        GroundType::Analog => "Analog()".into(),
    }
}

fn ref_name(m: &Module, n: &str) -> String {
    if n == "clk" {
        "clock".into()
    } else if n == "rst" {
        "reset".into()
    } else if m.ports.iter().any(|p| p.name == n) {
        format!("io.{n}")
    } else {
        n.to_string()
    }
}

fn emit_expr(m: &Module, expr: &AssignExpr) -> String {
    match expr {
        AssignExpr::Ref(n) => ref_name(m, n),
        AssignExpr::Lit(v) => format!("{v}.U"),
        AssignExpr::Inc(n) => format!("{} + 1.U", ref_name(m, n)),
        AssignExpr::Add(a, b) => format!("{} + {}", ref_name(m, a), ref_name(m, b)),
        AssignExpr::MemRead { mem, addr } => format!("{mem}({})", ref_name(m, addr)),
    }
}

fn emit_module(m: &Module) -> String {
    let mut io_fields = String::new();
    for p in &m.ports {
        if p.name == "clk" || p.name == "rst" {
            continue;
        }
        let dir = match p.direction {
            PortDirection::Input => "Input",
            PortDirection::Output => "Output",
            PortDirection::InOut => "Analog", // best-effort
        };
        io_fields.push_str(&format!(
            "    val {} = {dir}({})\n",
            p.name,
            chisel_ty(&p.ty)
        ));
    }
    let mut body = format!(
        "class {} extends Module {{\n  val io = IO(new Bundle {{\n{io_fields}  }})\n",
        m.name
    );
    for stmt in &m.body {
        match stmt {
            Stmt::RegDecl { name, ty, .. } => {
                let w = match ty {
                    GroundType::UInt { width } | GroundType::SInt { width } => *width,
                    _ => 1,
                };
                body.push_str(&format!("  val {name} = RegInit(0.U({w}.W))\n"));
            }
            Stmt::WireDecl { name, ty, .. } => {
                body.push_str(&format!("  val {name} = Wire({})\n", chisel_ty(ty)));
            }
            Stmt::Process(p) => {
                for a in &p.assigns {
                    match (&a.target, p.kind) {
                        (AssignTarget::Net(n), ProcessKind::Combinational)
                        | (AssignTarget::RegD(n), ProcessKind::Sequential) => {
                            body.push_str(&format!(
                                "  {} := {}\n",
                                ref_name(m, n),
                                emit_expr(m, &a.expr)
                            ));
                        }
                        (AssignTarget::MemWrite { mem, addr }, ProcessKind::Sequential) => {
                            body.push_str(&format!(
                                "  // mem write {mem}({}) := {}\n",
                                ref_name(m, addr),
                                emit_expr(m, &a.expr)
                            ));
                        }
                        _ => {}
                    }
                }
            }
            _ => {}
        }
    }
    body.push_str("}\n");
    body
}
