[package]
name = "rhdl-firrtl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "FrozenHir ↔ FIRRTL 6.0.0 text"

[dependencies]
bitloom-hir = { workspace = true }

[dev-dependencies]
bitloom-builder = { workspace = true }
bitloom-sim = { workspace = true }
bitloom-vlog = { workspace = true }
