// Generated by CIRCT firtool-1.159.0
`ifndef layers_Fr198DirectCore_Verification	// src/main/scala/Design.scala:2656:7
  `define layers_Fr198DirectCore_Verification
`endif // not def layers_Fr198DirectCore_Verification
