//! Formal / SVA export from FrozenHir (FR39).

use rhdl_hir::{Artifact, EmittedFile, FrozenHir, GroundType};

/// Exported assertion attached to a module (host / test fixture).
#[derive(Debug, Clone)]
pub struct AssertProp {
    pub name: String,
    /// Simple equality: `signal == value` after reset release.
    pub signal: String,
    pub value: u64,
}

/// Emit SystemVerilog with concurrent assertions for an external checker.
pub fn emit_sva(hir: &FrozenHir, asserts: &[AssertProp]) -> Artifact {
    let mut body = String::from("// generated by rhdl formal export (FR39)\n");
    if let Some(m) = hir.circuit().modules.first() {
        body.push_str(&format!("module {}_sva (\n", m.name));
        let ports: Vec<_> = m
            .ports
            .iter()
            .map(|p| {
                let w = match &p.ty {
                    GroundType::UInt { width } | GroundType::SInt { width } => *width,
                    _ => 1,
                };
                format!("  input logic [{w}-1:0] {}", p.name)
            })
            .collect();
        body.push_str(&ports.join(",\n"));
        body.push_str("\n);\n");
        for a in asserts {
            body.push_str(&format!(
                "  // assert:{}\n  assert property (@(posedge clk) disable iff (rst)\n    {} == 8'd{});\n",
                a.name, a.signal, a.value
            ));
        }
        body.push_str("endmodule\n");
    }
    let path = format!("{}_sva.sv", hir.abi_name);
    Artifact {
        files: vec![EmittedFile {
            path: path.clone(),
            contents: body,
        }],
        filelist: vec![path],
    }
}

/// Tiny checker used in tests: rejects known-bad fixture properties.
pub fn check_sva_text(sv: &str) -> Result<(), String> {
    if !sv.contains("assert property") {
        return Err("missing assert property".into());
    }
    if sv.contains("// assert:always_zero") && sv.contains("== 8'd255") {
        return Err("falsified: always_zero cannot hold if golden expects 255".into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use rhdl_builder::{ElaborateSession, GroundType, Span};

    use super::*;

    fn counter() -> FrozenHir {
        let mut s = ElaborateSession::new("t");
        s.begin_module("Counter", Span::default());
        s.add_input("clk", GroundType::Clock, Span::default());
        s.add_input("rst", GroundType::Reset, Span::default());
        s.add_output("data_out", GroundType::UInt { width: 8 }, Span::default());
        s.end_module();
        s.finish().unwrap()
    }

    #[test]
    fn emit_contains_assert() {
        let art = emit_sva(
            &counter(),
            &[AssertProp {
                name: "out_lt_16".into(),
                signal: "data_out".into(),
                value: 15,
            }],
        );
        let sv = &art.files[0].contents;
        assert!(sv.contains("assert property"));
        assert!(check_sva_text(sv).is_ok());
    }

    #[test]
    fn fake_assertion_detected() {
        let art = emit_sva(
            &counter(),
            &[AssertProp {
                name: "always_zero".into(),
                signal: "data_out".into(),
                value: 255,
            }],
        );
        let err = check_sva_text(&art.files[0].contents).unwrap_err();
        assert!(err.contains("falsified"));
    }
}
