[package]
name = "rhdl-vlog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "FrozenHir → Yosys-friendly Verilog (.v)"

[dependencies]
rhdl-hir = { workspace = true }

[dev-dependencies]
rhdl-builder = { workspace = true }
