// Generated by CIRCT firtool-1.159.0
module Fr198Gpio(	// src/main/scala/Design.scala:1705:7
  input         clock,	// src/main/scala/Design.scala:1705:7
                reset,	// src/main/scala/Design.scala:1705:7
                io_req_valid,	// src/main/scala/Design.scala:1706:14
                io_write,	// src/main/scala/Design.scala:1706:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:1706:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:1706:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:1706:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:1706:14
  output        io_req_ready,	// src/main/scala/Design.scala:1706:14
                io_rsp_valid,	// src/main/scala/Design.scala:1706:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:1706:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:1706:14
  input  [31:0] io_pad_in,	// src/main/scala/Design.scala:1706:14
  output [31:0] io_pad_out,	// src/main/scala/Design.scala:1706:14
                io_pad_oe,	// src/main/scala/Design.scala:1706:14
  output        io_raw_event	// src/main/scala/Design.scala:1706:14
);

  wire [31:0] _csr_io_dir_value;	// src/main/scala/Design.scala:1768:19
  wire        _csr_io_out_write_commit;	// src/main/scala/Design.scala:1768:19
  wire [31:0] _csr_io_out_candidate;	// src/main/scala/Design.scala:1768:19
  wire        _csr_io_set_write_commit;	// src/main/scala/Design.scala:1768:19
  wire [31:0] _csr_io_set_candidate;	// src/main/scala/Design.scala:1768:19
  wire        _csr_io_clear_write_commit;	// src/main/scala/Design.scala:1768:19
  wire [31:0] _csr_io_clear_candidate;	// src/main/scala/Design.scala:1768:19
  reg  [31:0] out_r;	// src/main/scala/Design.scala:1748:22
  reg  [31:0] sync1;	// src/main/scala/Design.scala:1749:22
  reg  [31:0] sync2;	// src/main/scala/Design.scala:1750:22
  reg  [31:0] history;	// src/main/scala/Design.scala:1751:24
  wire [31:0] rise_bits = sync2 & ~history & ~_csr_io_dir_value;	// src/main/scala/Design.scala:1750:22, :1751:24, :1768:19, :1813:26, :1814:24, :1815:19, :1816:23
  always @(posedge clock) begin	// src/main/scala/Design.scala:1705:7
    if (reset) begin	// src/main/scala/Design.scala:1705:7
      out_r <= 32'h0;	// src/main/scala/Design.scala:1748:22
      sync1 <= 32'h0;	// src/main/scala/Design.scala:1748:22, :1749:22
      sync2 <= 32'h0;	// src/main/scala/Design.scala:1748:22, :1750:22
      history <= 32'h0;	// src/main/scala/Design.scala:1748:22, :1751:24
    end
    else begin	// src/main/scala/Design.scala:1705:7
      out_r <=
        _csr_io_out_write_commit
          ? _csr_io_out_candidate
          : _csr_io_set_write_commit
              ? out_r | _csr_io_set_candidate
              : ({32{~_csr_io_clear_write_commit}} | ~_csr_io_clear_candidate) & out_r;	// src/main/scala/Design.scala:1748:22, :1768:19, :1821:22, :1822:32, :1824:21, :1825:19, :1826:18
      sync1 <= io_pad_in;	// src/main/scala/Design.scala:1749:22
      sync2 <= sync1;	// src/main/scala/Design.scala:1749:22, :1750:22
      history <= sync2;	// src/main/scala/Design.scala:1750:22, :1751:24
    end
  end // always @(posedge)
  BitloomGpioCsrRegisters csr (	// src/main/scala/Design.scala:1768:19
    .clock                 (clock),
    .reset                 (reset),
    .io_req_valid          (io_req_valid),
    .io_write              (io_write),
    .io_addr               (io_addr),
    .io_wdata              (io_wdata),
    .io_wstrb              (io_wstrb),
    .io_rsp_ready          (io_rsp_ready),
    .io_req_ready          (io_req_ready),
    .io_rsp_valid          (io_rsp_valid),
    .io_rdata              (io_rdata),
    .io_error              (io_error),
    .io_dir_value          (_csr_io_dir_value),
    .io_out_write_commit   (_csr_io_out_write_commit),
    .io_out_value          (out_r),	// src/main/scala/Design.scala:1748:22
    .io_out_candidate      (_csr_io_out_candidate),
    .io_in_value           (sync2),	// src/main/scala/Design.scala:1750:22
    .io_set_write_commit   (_csr_io_set_write_commit),
    .io_set_candidate      (_csr_io_set_candidate),
    .io_clear_write_commit (_csr_io_clear_write_commit),
    .io_clear_candidate    (_csr_io_clear_candidate),
    .io_rise_bits          (rise_bits)	// src/main/scala/Design.scala:1815:19, :1816:23
  );	// src/main/scala/Design.scala:1768:19
  assign io_pad_out = out_r & _csr_io_dir_value;	// src/main/scala/Design.scala:1705:7, :1748:22, :1768:19, :1812:23
  assign io_pad_oe = _csr_io_dir_value;	// src/main/scala/Design.scala:1705:7, :1768:19
  assign io_raw_event = (|rise_bits) & ~reset;	// src/main/scala/Design.scala:1705:7, :1815:19, :1816:23, :1817:22, :1819:36, :1820:28
endmodule

