// Generated by CIRCT firtool-1.159.0
module Fr198Irq(	// src/main/scala/Design.scala:2577:7
  input         clock,	// src/main/scala/Design.scala:2577:7
                reset,	// src/main/scala/Design.scala:2577:7
                io_req_valid,	// src/main/scala/Design.scala:2578:14
                io_write,	// src/main/scala/Design.scala:2578:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:2578:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:2578:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:2578:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:2578:14
  output        io_req_ready,	// src/main/scala/Design.scala:2578:14
                io_rsp_valid,	// src/main/scala/Design.scala:2578:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:2578:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:2578:14
  input  [4:0]  io_raw_events,	// src/main/scala/Design.scala:2578:14
  output        io_irq	// src/main/scala/Design.scala:2578:14
);

  wire [31:0] _csr_io_pending_value;	// src/main/scala/Design.scala:2616:19
  wire [31:0] _csr_io_enable_value;	// src/main/scala/Design.scala:2616:19
  wire        _csr_io_test_write_commit;	// src/main/scala/Design.scala:2616:19
  wire [31:0] _csr_io_test_candidate;	// src/main/scala/Design.scala:2616:19
  wire [31:0] raw_value = {27'h0, io_raw_events};	// src/main/scala/Design.scala:2646:10, :2648:32
  BitloomIrqCsr csr (	// src/main/scala/Design.scala:2616:19
    .clock                (clock),
    .reset                (reset),
    .io_req_valid         (io_req_valid),
    .io_write             (io_write),
    .io_addr              (io_addr),
    .io_wdata             (io_wdata),
    .io_wstrb             (io_wstrb),
    .io_rsp_ready         (io_rsp_ready),
    .io_req_ready         (io_req_ready),
    .io_rsp_valid         (io_rsp_valid),
    .io_rdata             (io_rdata),
    .io_error             (io_error),
    .io_pending_value     (_csr_io_pending_value),
    .io_event_bits
      (raw_value | (_csr_io_test_write_commit ? _csr_io_test_candidate : 32'h0)),	// src/main/scala/Design.scala:2616:19, :2645:10, :2648:32, :2649:19, :2650:27
    .io_enable_value      (_csr_io_enable_value),
    .io_test_write_commit (_csr_io_test_write_commit),
    .io_test_candidate    (_csr_io_test_candidate),
    .io_raw_value         (raw_value)	// src/main/scala/Design.scala:2648:32
  );	// src/main/scala/Design.scala:2616:19
  assign io_irq = |(_csr_io_pending_value & _csr_io_enable_value);	// src/main/scala/Design.scala:2577:7, :2616:19, :2651:27, :2652:19
endmodule

