// Generated by CIRCT firtool-1.159.0
module BitloomIrqCsr(	// src/main/scala/Design.scala:2284:7
  input         clock,	// src/main/scala/Design.scala:2284:7
                reset,	// src/main/scala/Design.scala:2284:7
                io_req_valid,	// src/main/scala/Design.scala:2285:14
                io_write,	// src/main/scala/Design.scala:2285:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:2285:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:2285:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:2285:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:2285:14
  output        io_req_ready,	// src/main/scala/Design.scala:2285:14
                io_rsp_valid,	// src/main/scala/Design.scala:2285:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:2285:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:2285:14
  output [31:0] io_pending_value,	// src/main/scala/Design.scala:2285:14
  input  [31:0] io_event_bits,	// src/main/scala/Design.scala:2285:14
  output [31:0] io_enable_value,	// src/main/scala/Design.scala:2285:14
  output        io_test_write_commit,	// src/main/scala/Design.scala:2285:14
  output [31:0] io_test_candidate,	// src/main/scala/Design.scala:2285:14
  input  [31:0] io_raw_value	// src/main/scala/Design.scala:2285:14
);

  reg         _csr_pending;	// src/main/scala/Design.scala:2315:29
  reg  [31:0] _csr_data;	// src/main/scala/Design.scala:2316:26
  reg  [1:0]  _csr_error;	// src/main/scala/Design.scala:2317:27
  reg  [31:0] _csr_value0;	// src/main/scala/Design.scala:2318:28
  reg  [31:0] _csr_value1;	// src/main/scala/Design.scala:2319:28
  wire        io_req_ready_0 = ~_csr_pending & ~reset;	// src/main/scala/Design.scala:2315:29, :2441:27, :2443:34, :2444:22
  wire        _csr_n114_T = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:2444:22, :2446:28
  wire [4:0]  _csr_n18 = {5{io_wstrb[0]}};	// src/main/scala/Design.scala:2454:23, :2456:18
  wire [31:0] io_pending_value_0 = {27'h0, _csr_value0[4:0]};	// src/main/scala/Design.scala:2318:28, :2471:27
  wire [31:0] io_enable_value_0 = {27'h0, _csr_value1[4:0]};	// src/main/scala/Design.scala:2319:28, :2502:27
  wire        _csr_n100_T = io_addr == 16'h8;	// src/main/scala/Design.scala:2532:12, :2533:23
  wire        _csr_n112_T = io_addr == 16'hC;	// src/main/scala/Design.scala:2556:13, :2557:24
  wire        _csr_n50_T = io_addr == 16'h0;	// src/main/scala/Design.scala:2474:23
  wire        _csr_n80_T = io_addr == 16'h4;	// src/main/scala/Design.scala:2504:12, :2505:23
  always @(posedge clock) begin	// src/main/scala/Design.scala:2284:7
    if (reset) begin	// src/main/scala/Design.scala:2284:7
      _csr_pending <= 1'h0;	// src/main/scala/Design.scala:2315:29
      _csr_data <= 32'h0;	// src/main/scala/Design.scala:2316:26
      _csr_error <= 2'h0;	// src/main/scala/Design.scala:2317:27
      _csr_value0 <= 32'h0;	// src/main/scala/Design.scala:2318:28
      _csr_value1 <= 32'h0;	// src/main/scala/Design.scala:2319:28
    end
    else begin	// src/main/scala/Design.scala:2284:7
      _csr_pending <= _csr_n114_T | ~io_rsp_ready & _csr_pending;	// src/main/scala/Design.scala:2315:29, :2446:28, :2449:18, :2450:18
      if (_csr_n114_T) begin	// src/main/scala/Design.scala:2446:28
        _csr_data <=
          _csr_n112_T
            ? (io_write ? 32'h0 : {27'h0, io_raw_value[4:0]})
            : _csr_n100_T
                ? 32'h0
                : _csr_n80_T
                    ? (io_write ? 32'h0 : io_enable_value_0)
                    : _csr_n50_T & ~io_write ? io_pending_value_0 : 32'h0;	// src/main/scala/Design.scala:2316:26, :2448:24, :2471:27, :2474:23, :2493:18, :2494:18, :2502:27, :2505:23, :2528:18, :2529:18, :2533:23, :2553:19, :2555:29, :2557:24, :2566:19, :2567:19
        _csr_error <=
          _csr_n112_T
            ? {io_write, 1'h0}
            : _csr_n100_T ? {~io_write, 1'h0} : _csr_n80_T ? 2'h0 : {~_csr_n50_T, 1'h0};	// src/main/scala/Design.scala:2317:27, :2474:23, :2491:18, :2492:18, :2505:23, :2527:18, :2533:23, :2550:18, :2551:18, :2557:24, :2564:19, :2565:19
      end
      _csr_value0 <=
        io_pending_value_0
        & ~(_csr_n114_T & _csr_n50_T & io_write & io_wstrb[0]
              ? io_wdata & {27'h0, _csr_n18}
              : 32'h0) | {27'h0, io_event_bits[4:0]};	// src/main/scala/Design.scala:2318:28, :2446:28, :2454:23, :2456:18, :2471:27, :2474:23, :2475:24, :2479:24, :2483:24, :2487:24, :2488:24, :2495:18, :2497:24, :2498:24, :2499:29, :2500:24
      _csr_value1 <=
        _csr_n114_T & _csr_n80_T & io_write & io_wstrb[0]
          ? io_enable_value_0 & {27'h7FFFFFF, ~_csr_n18} | io_wdata & {27'h0, _csr_n18}
          : io_enable_value_0;	// src/main/scala/Design.scala:2319:28, :2446:28, :2454:23, :2456:18, :2502:27, :2505:23, :2506:24, :2510:24, :2514:24, :2516:24, :2517:24, :2518:24, :2522:24, :2523:24, :2530:18
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:2284:7, :2444:22
  assign io_rsp_valid = _csr_pending;	// src/main/scala/Design.scala:2284:7, :2315:29
  assign io_rdata = _csr_data;	// src/main/scala/Design.scala:2284:7, :2316:26
  assign io_error = _csr_error;	// src/main/scala/Design.scala:2284:7, :2317:27
  assign io_pending_value = io_pending_value_0;	// src/main/scala/Design.scala:2284:7, :2471:27
  assign io_enable_value = io_enable_value_0;	// src/main/scala/Design.scala:2284:7, :2502:27
  assign io_test_write_commit = _csr_n114_T & _csr_n100_T & io_write & io_wstrb[0];	// src/main/scala/Design.scala:2284:7, :2446:28, :2454:23, :2533:23, :2534:24, :2546:24, :2547:24
  assign io_test_candidate = io_wdata & {27'h0, _csr_n18};	// src/main/scala/Design.scala:2284:7, :2456:18, :2538:24, :2542:24
endmodule

