// Generated by CIRCT firtool-1.159.0
module BitloomTimerCsr(	// src/main/scala/Design.scala:1833:7
  input         clock,	// src/main/scala/Design.scala:1833:7
                reset,	// src/main/scala/Design.scala:1833:7
                io_req_valid,	// src/main/scala/Design.scala:1834:14
                io_write,	// src/main/scala/Design.scala:1834:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:1834:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:1834:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:1834:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:1834:14
  output        io_req_ready,	// src/main/scala/Design.scala:1834:14
                io_rsp_valid,	// src/main/scala/Design.scala:1834:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:1834:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:1834:14
  output        io_ctrl_write_commit,	// src/main/scala/Design.scala:1834:14
  input  [31:0] io_ctrl_value,	// src/main/scala/Design.scala:1834:14
  output [31:0] io_ctrl_candidate,	// src/main/scala/Design.scala:1834:14
  output        io_count_write_commit,	// src/main/scala/Design.scala:1834:14
  input  [31:0] io_count_value,	// src/main/scala/Design.scala:1834:14
  output [31:0] io_count_candidate,	// src/main/scala/Design.scala:1834:14
  output        io_compare_write_commit,	// src/main/scala/Design.scala:1834:14
  output [31:0] io_compare_value,	// src/main/scala/Design.scala:1834:14
  input  [31:0] io_match_bits	// src/main/scala/Design.scala:1834:14
);

  reg         _csr_pending;	// src/main/scala/Design.scala:1867:29
  reg  [31:0] _csr_data;	// src/main/scala/Design.scala:1868:26
  reg  [1:0]  _csr_error;	// src/main/scala/Design.scala:1869:27
  reg  [31:0] _csr_value2;	// src/main/scala/Design.scala:1870:28
  reg  [31:0] _csr_value3;	// src/main/scala/Design.scala:1871:28
  wire        io_req_ready_0 = ~_csr_pending & ~reset;	// src/main/scala/Design.scala:1867:29, :2010:27, :2012:34, :2013:22
  wire        _csr_n131_T = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:2013:22, :2015:28
  wire [31:0] _csr_n86 =
    (io_wstrb[0] ? 32'hFF : 32'h0) | (io_wstrb[1] ? 32'hFF00 : 32'h0)
    | (io_wstrb[2] ? 32'hFF0000 : 32'h0) | (io_wstrb[3] ? 32'hFF000000 : 32'h0);	// src/main/scala/Design.scala:2023:23, :2024:12, :2025:18, :2027:23, :2028:12, :2029:18, :2030:24, :2031:23, :2032:12, :2033:18, :2034:24, :2035:23, :2036:12, :2037:18, :2038:24
  wire [31:0] _csr_n32 = {30'h0, io_ctrl_value[1:0]};	// src/main/scala/Design.scala:2040:29
  wire        _csr_n54_T = io_addr == 16'h0;	// src/main/scala/Design.scala:2042:23
  wire        _csr_n78_T = io_addr == 16'h4;	// src/main/scala/Design.scala:2069:12, :2070:23
  wire        _csr_n102_T = io_addr == 16'h8;	// src/main/scala/Design.scala:2098:12, :2099:23
  wire        io_compare_write_commit_0 =
    _csr_n131_T & _csr_n102_T & io_write & (|_csr_n86);	// src/main/scala/Design.scala:2015:28, :2030:24, :2034:24, :2038:24, :2099:23, :2100:24, :2105:24, :2116:24, :2117:24
  wire [31:0] _csr_n105 = {31'h0, _csr_value3[0]};	// src/main/scala/Design.scala:1871:28, :2126:28
  wire        _csr_n123_T = io_addr == 16'hC;	// src/main/scala/Design.scala:2128:13, :2129:24
  always @(posedge clock) begin	// src/main/scala/Design.scala:1833:7
    if (reset) begin	// src/main/scala/Design.scala:1833:7
      _csr_pending <= 1'h0;	// src/main/scala/Design.scala:1867:29
      _csr_data <= 32'h0;	// src/main/scala/Design.scala:1868:26
      _csr_error <= 2'h0;	// src/main/scala/Design.scala:1869:27
      _csr_value2 <= 32'h0;	// src/main/scala/Design.scala:1870:28
      _csr_value3 <= 32'h0;	// src/main/scala/Design.scala:1871:28
    end
    else begin	// src/main/scala/Design.scala:1833:7
      _csr_pending <= _csr_n131_T | ~io_rsp_ready & _csr_pending;	// src/main/scala/Design.scala:1867:29, :2015:28, :2018:18, :2019:18
      if (_csr_n131_T) begin	// src/main/scala/Design.scala:2015:28
        _csr_data <=
          _csr_n123_T
            ? (io_write ? 32'h0 : _csr_n105)
            : _csr_n102_T
                ? (io_write ? 32'h0 : _csr_value2)
                : _csr_n78_T
                    ? (io_write ? 32'h0 : io_count_value)
                    : _csr_n54_T & ~io_write ? _csr_n32 : 32'h0;	// src/main/scala/Design.scala:1868:26, :1870:28, :2017:24, :2040:29, :2042:23, :2065:18, :2066:18, :2070:23, :2093:18, :2094:18, :2099:23, :2122:19, :2123:19, :2126:28, :2129:24, :2148:19, :2149:19
        _csr_error <= _csr_n123_T | _csr_n102_T | _csr_n78_T ? 2'h0 : {~_csr_n54_T, 1'h0};	// src/main/scala/Design.scala:1869:27, :2042:23, :2063:18, :2064:18, :2070:23, :2099:23, :2121:19, :2129:24, :2147:19
      end
      if (io_compare_write_commit_0)	// src/main/scala/Design.scala:2100:24, :2116:24, :2117:24
        _csr_value2 <= _csr_value2 & ~_csr_n86 | io_wdata & _csr_n86;	// src/main/scala/Design.scala:1870:28, :2030:24, :2034:24, :2038:24, :2108:24, :2110:24, :2111:24, :2112:24
      _csr_value3 <=
        _csr_n105
        & ~(_csr_n131_T & _csr_n123_T & io_write & _csr_n86[0]
              ? io_wdata & {31'h0, _csr_n86[0]}
              : 32'h0) | {31'h0, io_match_bits[0]};	// src/main/scala/Design.scala:1871:28, :2015:28, :2030:24, :2034:24, :2038:24, :2126:28, :2129:24, :2130:25, :2134:25, :2138:25, :2142:26, :2143:26, :2150:19, :2152:26, :2153:26, :2154:30, :2155:26
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:1833:7, :2013:22
  assign io_rsp_valid = _csr_pending;	// src/main/scala/Design.scala:1833:7, :1867:29
  assign io_rdata = _csr_data;	// src/main/scala/Design.scala:1833:7, :1868:26
  assign io_error = _csr_error;	// src/main/scala/Design.scala:1833:7, :1869:27
  assign io_ctrl_write_commit = _csr_n131_T & _csr_n54_T & io_write & (|(_csr_n86[1:0]));	// src/main/scala/Design.scala:1833:7, :2015:28, :2030:24, :2034:24, :2038:24, :2042:23, :2043:24, :2047:24, :2048:24, :2059:24, :2060:24
  assign io_ctrl_candidate =
    _csr_n32 & {30'h3FFFFFFF, ~(_csr_n86[1:0])} | io_wdata & {30'h0, _csr_n86[1:0]};	// src/main/scala/Design.scala:1833:7, :2030:24, :2034:24, :2038:24, :2040:29, :2047:24, :2051:24, :2053:24, :2054:24, :2055:24
  assign io_count_write_commit = _csr_n131_T & _csr_n78_T & io_write & (|_csr_n86);	// src/main/scala/Design.scala:1833:7, :2015:28, :2030:24, :2034:24, :2038:24, :2070:23, :2071:24, :2076:24, :2087:24, :2088:24
  assign io_count_candidate = io_count_value & ~_csr_n86 | io_wdata & _csr_n86;	// src/main/scala/Design.scala:1833:7, :2030:24, :2034:24, :2038:24, :2079:24, :2081:24, :2082:24, :2083:24
  assign io_compare_write_commit = io_compare_write_commit_0;	// src/main/scala/Design.scala:1833:7, :2100:24, :2116:24, :2117:24
  assign io_compare_value = _csr_value2;	// src/main/scala/Design.scala:1833:7, :1870:28
endmodule

