// Generated by CIRCT firtool-1.159.0
module BitloomGpioCsrRegisters(	// src/main/scala/Design.scala:1309:7
  input         clock,	// src/main/scala/Design.scala:1309:7
                reset,	// src/main/scala/Design.scala:1309:7
                io_req_valid,	// src/main/scala/Design.scala:1310:14
                io_write,	// src/main/scala/Design.scala:1310:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:1310:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:1310:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:1310:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:1310:14
  output        io_req_ready,	// src/main/scala/Design.scala:1310:14
                io_rsp_valid,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:1310:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_dir_value,	// src/main/scala/Design.scala:1310:14
  output        io_out_write_commit,	// src/main/scala/Design.scala:1310:14
  input  [31:0] io_out_value,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_out_candidate,	// src/main/scala/Design.scala:1310:14
  input  [31:0] io_in_value,	// src/main/scala/Design.scala:1310:14
  output        io_set_write_commit,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_set_candidate,	// src/main/scala/Design.scala:1310:14
  output        io_clear_write_commit,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_clear_candidate,	// src/main/scala/Design.scala:1310:14
  input  [31:0] io_rise_bits	// src/main/scala/Design.scala:1310:14
);

  reg         _csr_pending;	// src/main/scala/Design.scala:1349:29
  reg  [31:0] _csr_data;	// src/main/scala/Design.scala:1350:26
  reg  [1:0]  _csr_error;	// src/main/scala/Design.scala:1351:27
  reg  [31:0] _csr_value0;	// src/main/scala/Design.scala:1352:28
  reg  [31:0] _csr_value5;	// src/main/scala/Design.scala:1353:28
  wire        io_req_ready_0 = ~_csr_pending & ~reset;	// src/main/scala/Design.scala:1349:29, :1518:27, :1520:34, :1521:22
  wire        _csr_n157_T = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:1521:22, :1523:28
  wire [31:0] _csr_n137 =
    (io_wstrb[0] ? 32'hFF : 32'h0) | (io_wstrb[1] ? 32'hFF00 : 32'h0)
    | (io_wstrb[2] ? 32'hFF0000 : 32'h0) | (io_wstrb[3] ? 32'hFF000000 : 32'h0);	// src/main/scala/Design.scala:1531:23, :1532:12, :1533:18, :1535:23, :1536:12, :1537:18, :1538:24, :1539:23, :1540:12, :1541:18, :1542:24, :1543:23, :1544:12, :1545:18, :1546:24
  wire        _csr_n79_T = io_addr == 16'h4;	// src/main/scala/Design.scala:1579:12, :1580:23
  wire        _csr_n110_T = io_addr == 16'hC;	// src/main/scala/Design.scala:1620:12, :1621:23
  wire        _csr_n129_T = io_addr == 16'h10;	// src/main/scala/Design.scala:1643:13, :1644:24
  wire        _csr_n91_T = io_addr == 16'h8;	// src/main/scala/Design.scala:1607:12, :1608:23
  wire        _csr_n54_T = io_addr == 16'h0;	// src/main/scala/Design.scala:1551:23
  wire        _csr_n149_T = io_addr == 16'h14;	// src/main/scala/Design.scala:1668:13, :1669:24
  always @(posedge clock) begin	// src/main/scala/Design.scala:1309:7
    if (reset) begin	// src/main/scala/Design.scala:1309:7
      _csr_pending <= 1'h0;	// src/main/scala/Design.scala:1349:29
      _csr_data <= 32'h0;	// src/main/scala/Design.scala:1350:26
      _csr_error <= 2'h0;	// src/main/scala/Design.scala:1351:27
      _csr_value0 <= 32'h0;	// src/main/scala/Design.scala:1352:28
      _csr_value5 <= 32'h0;	// src/main/scala/Design.scala:1353:28
    end
    else begin	// src/main/scala/Design.scala:1309:7
      _csr_pending <= _csr_n157_T | ~io_rsp_ready & _csr_pending;	// src/main/scala/Design.scala:1349:29, :1523:28, :1526:18, :1527:18
      if (_csr_n157_T) begin	// src/main/scala/Design.scala:1523:28
        _csr_data <=
          _csr_n149_T
            ? (io_write ? 32'h0 : _csr_value5)
            : _csr_n129_T | _csr_n110_T
                ? 32'h0
                : _csr_n91_T
                    ? (io_write ? 32'h0 : io_in_value)
                    : _csr_n79_T
                        ? (io_write ? 32'h0 : io_out_value)
                        : _csr_n54_T & ~io_write ? _csr_value0 : 32'h0;	// src/main/scala/Design.scala:1350:26, :1352:28, :1353:28, :1525:24, :1551:23, :1574:18, :1575:18, :1580:23, :1603:18, :1604:18, :1608:23, :1617:18, :1618:18, :1621:23, :1641:19, :1644:24, :1664:19, :1669:24, :1688:19, :1689:19
        _csr_error <=
          _csr_n149_T
            ? 2'h0
            : _csr_n129_T
                ? {~io_write, 1'h0}
                : _csr_n110_T
                    ? {~io_write, 1'h0}
                    : _csr_n91_T
                        ? {io_write, 1'h0}
                        : _csr_n79_T ? 2'h0 : {~_csr_n54_T, 1'h0};	// src/main/scala/Design.scala:1351:27, :1551:23, :1572:18, :1573:18, :1580:23, :1602:18, :1608:23, :1615:18, :1616:18, :1621:23, :1638:19, :1639:19, :1644:24, :1661:19, :1662:19, :1669:24, :1687:19
      end
      if (_csr_n157_T & _csr_n54_T & io_write & (|_csr_n137))	// src/main/scala/Design.scala:1523:28, :1538:24, :1542:24, :1546:24, :1551:23, :1552:24, :1557:24, :1568:24, :1569:24
        _csr_value0 <= _csr_value0 & ~_csr_n137 | io_wdata & _csr_n137;	// src/main/scala/Design.scala:1352:28, :1538:24, :1542:24, :1546:24, :1560:24, :1562:24, :1563:24, :1564:24
      _csr_value5 <=
        _csr_value5
        & ~(_csr_n157_T & _csr_n149_T & io_write & (|_csr_n137)
              ? io_wdata & _csr_n137
              : 32'h0) | io_rise_bits;	// src/main/scala/Design.scala:1353:28, :1523:28, :1538:24, :1542:24, :1546:24, :1669:24, :1670:25, :1675:26, :1678:25, :1682:26, :1683:26, :1690:19, :1692:26, :1693:26, :1695:26
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:1309:7, :1521:22
  assign io_rsp_valid = _csr_pending;	// src/main/scala/Design.scala:1309:7, :1349:29
  assign io_rdata = _csr_data;	// src/main/scala/Design.scala:1309:7, :1350:26
  assign io_error = _csr_error;	// src/main/scala/Design.scala:1309:7, :1351:27
  assign io_dir_value = _csr_value0;	// src/main/scala/Design.scala:1309:7, :1352:28
  assign io_out_write_commit = _csr_n157_T & _csr_n79_T & io_write & (|_csr_n137);	// src/main/scala/Design.scala:1309:7, :1523:28, :1538:24, :1542:24, :1546:24, :1580:23, :1581:24, :1586:24, :1597:24, :1598:24
  assign io_out_candidate = io_out_value & ~_csr_n137 | io_wdata & _csr_n137;	// src/main/scala/Design.scala:1309:7, :1538:24, :1542:24, :1546:24, :1589:24, :1591:24, :1592:24, :1593:24
  assign io_set_write_commit = _csr_n157_T & _csr_n110_T & io_write & (|_csr_n137);	// src/main/scala/Design.scala:1309:7, :1523:28, :1538:24, :1542:24, :1546:24, :1621:23, :1622:24, :1627:24, :1634:26, :1635:25
  assign io_set_candidate = io_wdata & _csr_n137;	// src/main/scala/Design.scala:1309:7, :1538:24, :1542:24, :1546:24, :1630:25
  assign io_clear_write_commit = _csr_n157_T & _csr_n129_T & io_write & (|_csr_n137);	// src/main/scala/Design.scala:1309:7, :1523:28, :1538:24, :1542:24, :1546:24, :1644:24, :1645:25, :1650:26, :1657:26, :1658:26
  assign io_clear_candidate = io_wdata & _csr_n137;	// src/main/scala/Design.scala:1309:7, :1538:24, :1542:24, :1546:24, :1653:25
endmodule

