// Generated by CIRCT firtool-1.159.0
module Fr198Bridge(	// src/main/scala/Design.scala:7:7
  input         clock,	// src/main/scala/Design.scala:7:7
                reset,	// src/main/scala/Design.scala:7:7
  input  [15:0] io_s_axi_awaddr,	// src/main/scala/Design.scala:8:14
  input         io_s_axi_awvalid,	// src/main/scala/Design.scala:8:14
  input  [31:0] io_s_axi_wdata,	// src/main/scala/Design.scala:8:14
  input  [3:0]  io_s_axi_wstrb,	// src/main/scala/Design.scala:8:14
  input         io_s_axi_wvalid,	// src/main/scala/Design.scala:8:14
                io_s_axi_bready,	// src/main/scala/Design.scala:8:14
  input  [15:0] io_s_axi_araddr,	// src/main/scala/Design.scala:8:14
  input         io_s_axi_arvalid,	// src/main/scala/Design.scala:8:14
                io_s_axi_rready,	// src/main/scala/Design.scala:8:14
                io_csr_req_ready,	// src/main/scala/Design.scala:8:14
                io_csr_rsp_valid,	// src/main/scala/Design.scala:8:14
  input  [31:0] io_csr_rdata,	// src/main/scala/Design.scala:8:14
  input  [1:0]  io_csr_error,	// src/main/scala/Design.scala:8:14
  output        io_s_axi_awready,	// src/main/scala/Design.scala:8:14
                io_s_axi_wready,	// src/main/scala/Design.scala:8:14
                io_s_axi_arready,	// src/main/scala/Design.scala:8:14
                io_s_axi_bvalid,	// src/main/scala/Design.scala:8:14
  output [1:0]  io_s_axi_bresp,	// src/main/scala/Design.scala:8:14
  output        io_s_axi_rvalid,	// src/main/scala/Design.scala:8:14
  output [31:0] io_s_axi_rdata,	// src/main/scala/Design.scala:8:14
  output [1:0]  io_s_axi_rresp,	// src/main/scala/Design.scala:8:14
  output        io_csr_req_valid,	// src/main/scala/Design.scala:8:14
                io_csr_write,	// src/main/scala/Design.scala:8:14
  output [15:0] io_csr_addr,	// src/main/scala/Design.scala:8:14
  output [31:0] io_csr_wdata,	// src/main/scala/Design.scala:8:14
  output [3:0]  io_csr_wstrb,	// src/main/scala/Design.scala:8:14
  output        io_csr_rsp_ready	// src/main/scala/Design.scala:8:14
);

  reg         aw_full;	// src/main/scala/Design.scala:39:24
  reg         w_full;	// src/main/scala/Design.scala:40:23
  reg         ar_full;	// src/main/scala/Design.scala:41:24
  reg  [15:0] aw_addr;	// src/main/scala/Design.scala:42:24
  reg  [31:0] w_data;	// src/main/scala/Design.scala:43:23
  reg  [3:0]  w_strb;	// src/main/scala/Design.scala:44:23
  reg  [15:0] ar_addr;	// src/main/scala/Design.scala:45:24
  reg         offer;	// src/main/scala/Design.scala:46:22
  reg         offer_write;	// src/main/scala/Design.scala:47:28
  reg         exec;	// src/main/scala/Design.scala:48:21
  reg         owner;	// src/main/scala/Design.scala:49:22
  reg         prefer_write;	// src/main/scala/Design.scala:50:29
  reg         b_full;	// src/main/scala/Design.scala:51:23
  reg         r_full;	// src/main/scala/Design.scala:52:23
  reg  [1:0]  b_error;	// src/main/scala/Design.scala:53:24
  reg  [1:0]  r_error;	// src/main/scala/Design.scala:54:24
  reg  [31:0] r_data;	// src/main/scala/Design.scala:55:23
  reg  [31:0] offer_data;	// src/main/scala/Design.scala:56:27
  reg  [3:0]  offer_strb;	// src/main/scala/Design.scala:57:27
  wire        io_csr_req_valid_0 = offer & ~reset;	// src/main/scala/Design.scala:46:22, :109:33, :123:29
  wire        io_csr_rsp_ready_0 = exec & ~reset;	// src/main/scala/Design.scala:48:21, :109:33, :128:28
  wire        aw_take = ~aw_full & io_s_axi_awvalid;	// src/main/scala/Design.scala:39:24, :103:31, :104:31
  wire        w_take = ~w_full & io_s_axi_wvalid;	// src/main/scala/Design.scala:40:23, :105:29, :106:29
  wire        ar_take = ~ar_full & io_s_axi_arvalid;	// src/main/scala/Design.scala:41:24, :107:31, :108:31
  wire        we = aw_full & w_full & ~b_full;	// src/main/scala/Design.scala:39:24, :40:23, :51:23, :113:21, :115:29, :116:24
  wire        re = ar_full & ~r_full;	// src/main/scala/Design.scala:41:24, :52:23, :114:21, :117:17
  wire        select = ~offer & ~exec & (we | re);	// src/main/scala/Design.scala:46:22, :48:21, :110:21, :111:19, :112:20, :115:29, :116:24, :117:17, :118:18, :119:18
  wire        commit = io_csr_req_valid_0 & io_csr_req_ready;	// src/main/scala/Design.scala:123:29, :124:30
  wire        write_commit = commit & offer_write;	// src/main/scala/Design.scala:47:28, :124:30, :126:26
  wire        response = io_csr_rsp_ready_0 & io_csr_rsp_valid;	// src/main/scala/Design.scala:128:28, :129:32
  wire        write_response = response & owner;	// src/main/scala/Design.scala:49:22, :129:32, :130:30
  wire        read_response = response & ~owner;	// src/main/scala/Design.scala:49:22, :129:32, :131:23, :132:29
  always @(posedge clock) begin	// src/main/scala/Design.scala:7:7
    if (reset) begin	// src/main/scala/Design.scala:7:7
      aw_full <= 1'h0;	// src/main/scala/Design.scala:39:24
      w_full <= 1'h0;	// src/main/scala/Design.scala:39:24, :40:23
      ar_full <= 1'h0;	// src/main/scala/Design.scala:39:24, :41:24
      aw_addr <= 16'h0;	// src/main/scala/Design.scala:42:24
      w_data <= 32'h0;	// src/main/scala/Design.scala:43:23
      w_strb <= 4'h0;	// src/main/scala/Design.scala:44:23
      ar_addr <= 16'h0;	// src/main/scala/Design.scala:42:24, :45:24
      offer <= 1'h0;	// src/main/scala/Design.scala:39:24, :46:22
      offer_write <= 1'h0;	// src/main/scala/Design.scala:39:24, :47:28
      exec <= 1'h0;	// src/main/scala/Design.scala:39:24, :48:21
      owner <= 1'h0;	// src/main/scala/Design.scala:39:24, :49:22
      prefer_write <= 1'h0;	// src/main/scala/Design.scala:39:24, :50:29
      b_full <= 1'h0;	// src/main/scala/Design.scala:39:24, :51:23
      r_full <= 1'h0;	// src/main/scala/Design.scala:39:24, :52:23
      b_error <= 2'h0;	// src/main/scala/Design.scala:53:24
      r_error <= 2'h0;	// src/main/scala/Design.scala:53:24, :54:24
      r_data <= 32'h0;	// src/main/scala/Design.scala:43:23, :55:23
      offer_data <= 32'h0;	// src/main/scala/Design.scala:43:23, :56:27
      offer_strb <= 4'h0;	// src/main/scala/Design.scala:44:23, :57:27
    end
    else begin	// src/main/scala/Design.scala:7:7
      aw_full <= ~write_commit & (aw_take | aw_full);	// src/main/scala/Design.scala:39:24, :104:31, :126:26, :135:21, :136:17
      w_full <= ~write_commit & (w_take | w_full);	// src/main/scala/Design.scala:40:23, :106:29, :126:26, :136:17, :137:20, :138:16
      ar_full <= ~(commit & ~offer_write) & (ar_take | ar_full);	// src/main/scala/Design.scala:41:24, :47:28, :108:31, :124:30, :125:29, :127:25, :139:21, :140:17
      if (aw_take)	// src/main/scala/Design.scala:104:31
        aw_addr <= io_s_axi_awaddr;	// src/main/scala/Design.scala:42:24
      if (w_take) begin	// src/main/scala/Design.scala:106:29
        w_data <= io_s_axi_wdata;	// src/main/scala/Design.scala:43:23
        w_strb <= io_s_axi_wstrb;	// src/main/scala/Design.scala:44:23
      end
      if (ar_take)	// src/main/scala/Design.scala:108:31
        ar_addr <= io_s_axi_araddr;	// src/main/scala/Design.scala:45:24
      offer <= ~commit & (select | offer);	// src/main/scala/Design.scala:46:22, :112:20, :119:18, :124:30, :141:23, :142:20
      if (select) begin	// src/main/scala/Design.scala:112:20, :119:18
        offer_write <= we & (prefer_write | ~re);	// src/main/scala/Design.scala:47:28, :50:29, :115:29, :116:24, :117:17, :120:17, :121:35, :122:22
        offer_data <= w_data;	// src/main/scala/Design.scala:43:23, :56:27
        offer_strb <= w_strb;	// src/main/scala/Design.scala:44:23, :57:27
      end
      exec <= ~response & (commit | exec);	// src/main/scala/Design.scala:48:21, :124:30, :129:32, :143:22, :144:19
      if (commit) begin	// src/main/scala/Design.scala:124:30
        owner <= offer_write;	// src/main/scala/Design.scala:47:28, :49:22
        prefer_write <= ~offer_write;	// src/main/scala/Design.scala:47:28, :50:29, :125:29
      end
      b_full <= write_response | ~(b_full & io_s_axi_bready) & b_full;	// src/main/scala/Design.scala:51:23, :130:30, :133:20, :145:20, :146:16
      r_full <= read_response | ~(r_full & io_s_axi_rready) & r_full;	// src/main/scala/Design.scala:52:23, :132:29, :134:20, :147:20, :148:16
      if (write_response)	// src/main/scala/Design.scala:130:30
        b_error <= io_csr_error;	// src/main/scala/Design.scala:53:24
      if (read_response) begin	// src/main/scala/Design.scala:132:29
        r_error <= io_csr_error;	// src/main/scala/Design.scala:54:24
        r_data <= io_csr_rdata;	// src/main/scala/Design.scala:55:23
      end
    end
  end // always @(posedge)
  assign io_s_axi_awready = ~aw_full;	// src/main/scala/Design.scala:7:7, :39:24, :103:31
  assign io_s_axi_wready = ~w_full;	// src/main/scala/Design.scala:7:7, :40:23, :105:29
  assign io_s_axi_arready = ~ar_full;	// src/main/scala/Design.scala:7:7, :41:24, :107:31
  assign io_s_axi_bvalid = b_full;	// src/main/scala/Design.scala:7:7, :51:23
  assign io_s_axi_bresp = b_error;	// src/main/scala/Design.scala:7:7, :53:24
  assign io_s_axi_rvalid = r_full;	// src/main/scala/Design.scala:7:7, :52:23
  assign io_s_axi_rdata = r_data;	// src/main/scala/Design.scala:7:7, :55:23
  assign io_s_axi_rresp = r_error;	// src/main/scala/Design.scala:7:7, :54:24
  assign io_csr_req_valid = io_csr_req_valid_0;	// src/main/scala/Design.scala:7:7, :123:29
  assign io_csr_write = offer_write;	// src/main/scala/Design.scala:7:7, :47:28
  assign io_csr_addr = offer_write ? aw_addr : ar_addr;	// src/main/scala/Design.scala:7:7, :42:24, :45:24, :47:28, :149:21
  assign io_csr_wdata = offer_data;	// src/main/scala/Design.scala:7:7, :56:27
  assign io_csr_wstrb = offer_strb;	// src/main/scala/Design.scala:7:7, :57:27
  assign io_csr_rsp_ready = io_csr_rsp_ready_0;	// src/main/scala/Design.scala:7:7, :128:28
endmodule

