//! FR85 — export SVA from a real Counter design (not `check_sva_text` toy).
//!
//! Usage:
//!   cargo run -p rhdl-formal --example export_fr85_counter -- [out.sv]
//! Default out: fixtures/fr85_counter_sva.sv under this crate.

use bitloom_builder::{ElaborateSession, GroundType, Span};
use rhdl_formal::{AssertProp, emit_sva};
use std::env;
use std::fs;
use std::path::PathBuf;

fn counter_hir() -> bitloom_hir::FrozenHir {
    let mut s = ElaborateSession::new("fr85_counter");
    s.begin_module("Counter", Span::default());
    s.add_input("clk", GroundType::Clock, Span::default());
    s.add_input("rst", GroundType::Reset, Span::default());
    s.add_output("data_out", GroundType::UInt { width: 8 }, Span::default());
    s.end_module();
    s.finish().expect("elaborate Counter")
}

fn main() {
    let default_out =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/fr85_counter_sva.sv");
    let out = env::args().nth(1).map(PathBuf::from).unwrap_or(default_out);

    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).expect("create parent dir");
    }

    let art = emit_sva(
        &counter_hir(),
        &[AssertProp {
            name: "out_lt_16".into(),
            signal: "data_out".into(),
            value: 15,
        }],
    );
    let body = &art.files[0].contents;
    // Tag FR85 provenance without changing assert shape.
    let tagged = if body.contains("FR85") {
        body.clone()
    } else {
        body.replacen(
            "// generated by rhdl formal export (FR39)\n",
            "// generated by rhdl formal export (FR39); FR85 Counter fixture\n",
            1,
        )
    };
    fs::write(&out, tagged).unwrap_or_else(|e| panic!("write {}: {e}", out.display()));
    eprintln!("fr85: wrote {}", out.display());
}
