// Generated by CIRCT firtool-1.159.0
module Fr198Timer(	// src/main/scala/Design.scala:2165:7
  input         clock,	// src/main/scala/Design.scala:2165:7
                reset,	// src/main/scala/Design.scala:2165:7
                io_req_valid,	// src/main/scala/Design.scala:2166:14
                io_write,	// src/main/scala/Design.scala:2166:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:2166:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:2166:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:2166:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:2166:14
  output        io_req_ready,	// src/main/scala/Design.scala:2166:14
                io_rsp_valid,	// src/main/scala/Design.scala:2166:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:2166:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:2166:14
  output        io_match_event	// src/main/scala/Design.scala:2166:14
);

  wire        _csr_io_ctrl_write_commit;	// src/main/scala/Design.scala:2223:19
  wire [31:0] _csr_io_ctrl_candidate;	// src/main/scala/Design.scala:2223:19
  wire        _csr_io_count_write_commit;	// src/main/scala/Design.scala:2223:19
  wire [31:0] _csr_io_count_candidate;	// src/main/scala/Design.scala:2223:19
  wire        _csr_io_compare_write_commit;	// src/main/scala/Design.scala:2223:19
  wire [31:0] _csr_io_compare_value;	// src/main/scala/Design.scala:2223:19
  reg  [31:0] ctrl_value;	// src/main/scala/Design.scala:2179:27
  reg  [31:0] count_value;	// src/main/scala/Design.scala:2180:28
  wire        advance =
    ctrl_value[0] & ~reset
    & ~(_csr_io_ctrl_write_commit | _csr_io_count_write_commit
        | _csr_io_compare_write_commit);	// src/main/scala/Design.scala:2179:27, :2223:19, :2259:33, :2260:24, :2263:33, :2264:28, :2265:28, :2266:22, :2267:22
  wire [31:0] _increment_T = count_value + 32'h1;	// src/main/scala/Design.scala:2180:28, :2268:28
  wire        io_match_event_0 = advance & _increment_T == _csr_io_compare_value;	// src/main/scala/Design.scala:2223:19, :2266:22, :2267:22, :2268:28, :2269:22, :2270:29
  always @(posedge clock) begin	// src/main/scala/Design.scala:2165:7
    if (reset) begin	// src/main/scala/Design.scala:2165:7
      ctrl_value <= 32'h0;	// src/main/scala/Design.scala:2179:27
      count_value <= 32'h0;	// src/main/scala/Design.scala:2180:28
    end
    else begin	// src/main/scala/Design.scala:2165:7
      if (_csr_io_ctrl_write_commit)	// src/main/scala/Design.scala:2223:19
        ctrl_value <= _csr_io_ctrl_candidate;	// src/main/scala/Design.scala:2179:27, :2223:19
      else if (io_match_event_0 & ~(ctrl_value[1]))	// src/main/scala/Design.scala:2179:27, :2261:25, :2262:28, :2270:29, :2273:26
        ctrl_value <= {30'h0, ctrl_value[1], 1'h0};	// src/main/scala/Design.scala:2179:27, :2274:30
      if (_csr_io_count_write_commit)	// src/main/scala/Design.scala:2223:19
        count_value <= _csr_io_count_candidate;	// src/main/scala/Design.scala:2180:28, :2223:19
      else if (advance)	// src/main/scala/Design.scala:2266:22, :2267:22
        count_value <= io_match_event_0 & ctrl_value[1] ? 32'h0 : _increment_T;	// src/main/scala/Design.scala:2179:27, :2180:28, :2261:25, :2268:28, :2270:29, :2272:29, :2277:20
    end
  end // always @(posedge)
  BitloomTimerCsr csr (	// src/main/scala/Design.scala:2223:19
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid),
    .io_write                (io_write),
    .io_addr                 (io_addr),
    .io_wdata                (io_wdata),
    .io_wstrb                (io_wstrb),
    .io_rsp_ready            (io_rsp_ready),
    .io_req_ready            (io_req_ready),
    .io_rsp_valid            (io_rsp_valid),
    .io_rdata                (io_rdata),
    .io_error                (io_error),
    .io_ctrl_write_commit    (_csr_io_ctrl_write_commit),
    .io_ctrl_value           (ctrl_value),	// src/main/scala/Design.scala:2179:27
    .io_ctrl_candidate       (_csr_io_ctrl_candidate),
    .io_count_write_commit   (_csr_io_count_write_commit),
    .io_count_value          (count_value),	// src/main/scala/Design.scala:2180:28
    .io_count_candidate      (_csr_io_count_candidate),
    .io_compare_write_commit (_csr_io_compare_write_commit),
    .io_compare_value        (_csr_io_compare_value),
    .io_match_bits           ({31'h0, io_match_event_0})	// src/main/scala/Design.scala:2270:29, :2271:20
  );	// src/main/scala/Design.scala:2223:19
  assign io_match_event = io_match_event_0;	// src/main/scala/Design.scala:2165:7, :2270:29
endmodule

