// Generated by CIRCT firtool-1.159.0
module BitloomUartCsrRegisters(	// src/main/scala/Design.scala:406:7
  input         clock,	// src/main/scala/Design.scala:406:7
                reset,	// src/main/scala/Design.scala:406:7
                io_req_valid,	// src/main/scala/Design.scala:407:14
                io_write,	// src/main/scala/Design.scala:407:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:407:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:407:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:407:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:407:14
  output        io_req_ready,	// src/main/scala/Design.scala:407:14
                io_rsp_valid,	// src/main/scala/Design.scala:407:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:407:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:407:14
  output        io_ctrl_write_commit,	// src/main/scala/Design.scala:407:14
  output [31:0] io_ctrl_value,	// src/main/scala/Design.scala:407:14
                io_ctrl_candidate,	// src/main/scala/Design.scala:407:14
  input         io_ctrl_write_reject,	// src/main/scala/Design.scala:407:14
  output        io_baud_div_write_commit,	// src/main/scala/Design.scala:407:14
  output [31:0] io_baud_div_value,	// src/main/scala/Design.scala:407:14
                io_baud_div_candidate,	// src/main/scala/Design.scala:407:14
  input         io_baud_div_write_reject,	// src/main/scala/Design.scala:407:14
  input  [31:0] io_status_value,	// src/main/scala/Design.scala:407:14
  output        io_tx_data_write_commit,	// src/main/scala/Design.scala:407:14
  output [31:0] io_tx_data_candidate,	// src/main/scala/Design.scala:407:14
  input         io_tx_data_write_reject,	// src/main/scala/Design.scala:407:14
  output        io_rx_data_read_commit,	// src/main/scala/Design.scala:407:14
  input  [31:0] io_rx_data_value,	// src/main/scala/Design.scala:407:14
  input         io_rx_data_read_reject,	// src/main/scala/Design.scala:407:14
  input  [31:0] io_event_bits	// src/main/scala/Design.scala:407:14
);

  reg         _csr_pending;	// src/main/scala/Design.scala:449:29
  reg  [31:0] _csr_data;	// src/main/scala/Design.scala:450:26
  reg  [1:0]  _csr_error;	// src/main/scala/Design.scala:451:27
  reg  [31:0] _csr_value0;	// src/main/scala/Design.scala:452:28
  reg  [31:0] _csr_value1;	// src/main/scala/Design.scala:453:28
  reg  [31:0] _csr_value5;	// src/main/scala/Design.scala:454:28
  wire        io_req_ready_0 = ~_csr_pending & ~reset;	// src/main/scala/Design.scala:449:29, :624:27, :626:34, :627:22
  wire        _csr_n162_T = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:627:22, :629:28
  wire [31:0] _csr_n66 =
    (io_wstrb[0] ? 32'hFF : 32'h0) | (io_wstrb[1] ? 32'hFF00 : 32'h0)
    | (io_wstrb[2] ? 32'hFF0000 : 32'h0) | (io_wstrb[3] ? 32'hFF000000 : 32'h0);	// src/main/scala/Design.scala:637:23, :638:12, :639:18, :641:23, :642:12, :643:18, :644:24, :645:23, :646:12, :647:18, :648:24, :649:23, :650:12, :651:18, :652:24
  wire [31:0] io_ctrl_value_0 = {31'h0, _csr_value0[0]};	// src/main/scala/Design.scala:452:28, :654:27
  wire        _csr_n57_T = io_addr == 16'h0;	// src/main/scala/Design.scala:657:23
  wire [31:0] io_ctrl_candidate_0 =
    io_ctrl_value_0 & {31'h7FFFFFFF, ~(_csr_n66[0])} | io_wdata & {31'h0, _csr_n66[0]};	// src/main/scala/Design.scala:644:24, :648:24, :652:24, :654:27, :662:24, :666:24, :668:24, :669:24, :670:24
  wire        _csr_n50 = io_write & (~(_csr_n66[0]) | ~io_ctrl_write_reject);	// src/main/scala/Design.scala:644:24, :648:24, :652:24, :662:24, :663:24, :674:36, :675:24, :676:24
  wire        io_ctrl_write_commit_0 = _csr_n162_T & _csr_n57_T & _csr_n50 & _csr_n66[0];	// src/main/scala/Design.scala:629:28, :644:24, :648:24, :652:24, :657:23, :658:24, :662:24, :676:24, :677:24, :678:24
  wire        _csr_n85_T = io_addr == 16'h4;	// src/main/scala/Design.scala:689:12, :690:23
  wire        _csr_n69 = |_csr_n66;	// src/main/scala/Design.scala:644:24, :648:24, :652:24, :696:24
  wire [31:0] io_baud_div_candidate_0 = _csr_value1 & ~_csr_n66 | io_wdata & _csr_n66;	// src/main/scala/Design.scala:453:28, :644:24, :648:24, :652:24, :699:24, :701:24, :702:24, :703:24
  wire        _csr_n78 = io_write & (~_csr_n69 | ~io_baud_div_write_reject);	// src/main/scala/Design.scala:696:24, :707:40, :708:24, :709:24
  wire        io_baud_div_write_commit_0 = _csr_n162_T & _csr_n85_T & _csr_n78 & _csr_n69;	// src/main/scala/Design.scala:629:28, :690:23, :691:24, :696:24, :709:24, :710:24, :711:24
  wire        _csr_n120_T = io_addr == 16'hC;	// src/main/scala/Design.scala:734:13, :735:24
  wire        _csr_n108 = |(_csr_n66[7:0]);	// src/main/scala/Design.scala:644:24, :648:24, :652:24, :740:25, :741:26
  wire        _csr_n117_T = io_write & (~_csr_n108 | ~io_tx_data_write_reject);	// src/main/scala/Design.scala:741:26, :748:40, :749:26, :750:25
  wire        _csr_n134_T = io_addr == 16'h10;	// src/main/scala/Design.scala:761:13, :762:24
  wire        _csr_n131_T = ~io_write & ~io_rx_data_read_reject;	// src/main/scala/Design.scala:631:24, :765:39, :766:25
  wire        _csr_n98_T = io_addr == 16'h8;	// src/main/scala/Design.scala:721:12, :722:23
  wire [31:0] _csr_n136 = {28'h0, _csr_value5[3:0]};	// src/main/scala/Design.scala:454:28, :776:28
  wire        _csr_n154_T = io_addr == 16'h14;	// src/main/scala/Design.scala:778:13, :779:24
  always @(posedge clock) begin	// src/main/scala/Design.scala:406:7
    if (reset) begin	// src/main/scala/Design.scala:406:7
      _csr_pending <= 1'h0;	// src/main/scala/Design.scala:449:29
      _csr_data <= 32'h0;	// src/main/scala/Design.scala:450:26
      _csr_error <= 2'h0;	// src/main/scala/Design.scala:451:27
      _csr_value0 <= 32'h0;	// src/main/scala/Design.scala:452:28
      _csr_value1 <= 32'h0;	// src/main/scala/Design.scala:453:28
      _csr_value5 <= 32'h0;	// src/main/scala/Design.scala:454:28
    end
    else begin	// src/main/scala/Design.scala:406:7
      _csr_pending <= _csr_n162_T | ~io_rsp_ready & _csr_pending;	// src/main/scala/Design.scala:449:29, :629:28, :632:18, :633:18
      if (_csr_n162_T) begin	// src/main/scala/Design.scala:629:28
        _csr_data <=
          _csr_n154_T
            ? (io_write ? 32'h0 : _csr_n136)
            : _csr_n134_T
                ? (_csr_n131_T ? {24'h0, io_rx_data_value[7:0]} : 32'h0)
                : _csr_n120_T
                    ? 32'h0
                    : _csr_n98_T
                        ? (io_write ? 32'h0 : {28'h0, io_status_value[3:0]})
                        : _csr_n85_T
                            ? (io_write ? 32'h0 : _csr_value1)
                            : _csr_n57_T & ~io_write ? io_ctrl_value_0 : 32'h0;	// src/main/scala/Design.scala:450:26, :453:28, :631:24, :654:27, :657:23, :683:18, :684:18, :690:23, :716:18, :717:18, :720:31, :722:23, :731:18, :732:18, :735:24, :758:19, :760:33, :762:24, :766:25, :773:19, :774:19, :776:28, :779:24, :798:19, :799:19
        _csr_error <=
          _csr_n154_T
            ? 2'h0
            : {_csr_n134_T
                 ? ~_csr_n131_T
                 : _csr_n120_T
                     ? ~_csr_n117_T
                     : _csr_n98_T
                         ? io_write
                         : _csr_n85_T
                             ? ~(~io_write | _csr_n78)
                             : ~(_csr_n57_T & (~io_write | _csr_n50)),
               1'h0};	// src/main/scala/Design.scala:451:27, :631:24, :657:23, :676:24, :680:24, :681:18, :682:18, :690:23, :709:24, :713:24, :714:18, :715:18, :722:23, :730:18, :735:24, :750:25, :755:19, :756:19, :762:24, :766:25, :771:19, :772:19, :779:24, :797:19
      end
      _csr_value0 <= io_ctrl_write_commit_0 ? io_ctrl_candidate_0 : io_ctrl_value_0;	// src/main/scala/Design.scala:452:28, :654:27, :658:24, :670:24, :677:24, :678:24, :685:18
      if (io_baud_div_write_commit_0)	// src/main/scala/Design.scala:691:24, :710:24, :711:24
        _csr_value1 <= io_baud_div_candidate_0;	// src/main/scala/Design.scala:453:28, :703:24
      _csr_value5 <=
        _csr_n136
        & ~(_csr_n162_T & _csr_n154_T & io_write & (|(_csr_n66[3:0]))
              ? io_wdata & {28'h0, _csr_n66[3:0]}
              : 32'h0) | {28'h0, io_event_bits[3:0]};	// src/main/scala/Design.scala:454:28, :629:28, :644:24, :648:24, :652:24, :776:28, :779:24, :780:25, :784:25, :785:26, :788:25, :792:26, :793:26, :800:19, :802:26, :803:26, :804:30, :805:26
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:406:7, :627:22
  assign io_rsp_valid = _csr_pending;	// src/main/scala/Design.scala:406:7, :449:29
  assign io_rdata = _csr_data;	// src/main/scala/Design.scala:406:7, :450:26
  assign io_error = _csr_error;	// src/main/scala/Design.scala:406:7, :451:27
  assign io_ctrl_write_commit = io_ctrl_write_commit_0;	// src/main/scala/Design.scala:406:7, :658:24, :677:24, :678:24
  assign io_ctrl_value = io_ctrl_value_0;	// src/main/scala/Design.scala:406:7, :654:27
  assign io_ctrl_candidate = io_ctrl_candidate_0;	// src/main/scala/Design.scala:406:7, :670:24
  assign io_baud_div_write_commit = io_baud_div_write_commit_0;	// src/main/scala/Design.scala:406:7, :691:24, :710:24, :711:24
  assign io_baud_div_value = _csr_value1;	// src/main/scala/Design.scala:406:7, :453:28
  assign io_baud_div_candidate = io_baud_div_candidate_0;	// src/main/scala/Design.scala:406:7, :703:24
  assign io_tx_data_write_commit = _csr_n162_T & _csr_n120_T & _csr_n117_T & _csr_n108;	// src/main/scala/Design.scala:406:7, :629:28, :735:24, :736:25, :741:26, :750:25, :751:26, :752:26
  assign io_tx_data_candidate = io_wdata & {24'h0, _csr_n66[7:0]};	// src/main/scala/Design.scala:406:7, :644:24, :648:24, :652:24, :740:25, :744:25
  assign io_rx_data_read_commit = _csr_n162_T & _csr_n134_T & _csr_n131_T;	// src/main/scala/Design.scala:406:7, :629:28, :762:24, :763:25, :766:25, :767:26
endmodule

