// Generated by CIRCT firtool-1.159.0
module Fr198Decoder(	// src/main/scala/Design.scala:179:7
  input         clock,	// src/main/scala/Design.scala:179:7
                reset,	// src/main/scala/Design.scala:179:7
                io_req_valid,	// src/main/scala/Design.scala:180:14
                io_write,	// src/main/scala/Design.scala:180:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:180:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:180:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:180:14
  output        io_req_ready,	// src/main/scala/Design.scala:180:14
                io_rsp_valid,	// src/main/scala/Design.scala:180:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:180:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:180:14
  input         io_uart_req_ready,	// src/main/scala/Design.scala:180:14
                io_uart_rsp_valid,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_uart_rdata,	// src/main/scala/Design.scala:180:14
  input  [1:0]  io_uart_error,	// src/main/scala/Design.scala:180:14
  output        io_uart_req_valid,	// src/main/scala/Design.scala:180:14
                io_uart_write,	// src/main/scala/Design.scala:180:14
  output [15:0] io_uart_addr,	// src/main/scala/Design.scala:180:14
  output [31:0] io_uart_wdata,	// src/main/scala/Design.scala:180:14
  output [3:0]  io_uart_wstrb,	// src/main/scala/Design.scala:180:14
  output        io_uart_rsp_ready,	// src/main/scala/Design.scala:180:14
  input         io_gpio_req_ready,	// src/main/scala/Design.scala:180:14
                io_gpio_rsp_valid,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_gpio_rdata,	// src/main/scala/Design.scala:180:14
  input  [1:0]  io_gpio_error,	// src/main/scala/Design.scala:180:14
  output        io_gpio_req_valid,	// src/main/scala/Design.scala:180:14
                io_gpio_write,	// src/main/scala/Design.scala:180:14
  output [15:0] io_gpio_addr,	// src/main/scala/Design.scala:180:14
  output [31:0] io_gpio_wdata,	// src/main/scala/Design.scala:180:14
  output [3:0]  io_gpio_wstrb,	// src/main/scala/Design.scala:180:14
  output        io_gpio_rsp_ready,	// src/main/scala/Design.scala:180:14
  input         io_timer_req_ready,	// src/main/scala/Design.scala:180:14
                io_timer_rsp_valid,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_timer_rdata,	// src/main/scala/Design.scala:180:14
  input  [1:0]  io_timer_error,	// src/main/scala/Design.scala:180:14
  output        io_timer_req_valid,	// src/main/scala/Design.scala:180:14
                io_timer_write,	// src/main/scala/Design.scala:180:14
  output [15:0] io_timer_addr,	// src/main/scala/Design.scala:180:14
  output [31:0] io_timer_wdata,	// src/main/scala/Design.scala:180:14
  output [3:0]  io_timer_wstrb,	// src/main/scala/Design.scala:180:14
  output        io_timer_rsp_ready,	// src/main/scala/Design.scala:180:14
  input         io_irq_req_ready,	// src/main/scala/Design.scala:180:14
                io_irq_rsp_valid,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_irq_rdata,	// src/main/scala/Design.scala:180:14
  input  [1:0]  io_irq_error,	// src/main/scala/Design.scala:180:14
  output        io_irq_req_valid,	// src/main/scala/Design.scala:180:14
                io_irq_write,	// src/main/scala/Design.scala:180:14
  output [15:0] io_irq_addr,	// src/main/scala/Design.scala:180:14
  output [31:0] io_irq_wdata,	// src/main/scala/Design.scala:180:14
  output [3:0]  io_irq_wstrb,	// src/main/scala/Design.scala:180:14
  output        io_irq_rsp_ready	// src/main/scala/Design.scala:180:14
);

  reg        busy;	// src/main/scala/Design.scala:232:21
  reg        miss;	// src/main/scala/Design.scala:233:21
  reg  [1:0] owner;	// src/main/scala/Design.scala:234:22
  wire       available = ~busy & ~reset;	// src/main/scala/Design.scala:232:21, :311:33, :312:16, :313:21
  wire       offering = available & io_req_valid;	// src/main/scala/Design.scala:313:21, :314:25
  wire       leaf_owned = busy & ~miss;	// src/main/scala/Design.scala:232:21, :233:21, :315:20, :316:22
  wire       ready_active = io_rsp_ready & ~reset;	// src/main/scala/Design.scala:311:33, :317:32
  wire       valid_0 = busy & miss;	// src/main/scala/Design.scala:232:21, :233:21, :318:22
  wire       hit_1 = io_addr[15:8] == 8'h0;	// src/main/scala/Design.scala:309:18, :327:20
  wire       uart_owned = leaf_owned & owner == 2'h0;	// src/main/scala/Design.scala:234:22, :316:22, :335:26, :336:28
  wire       gpio_hit = io_addr[15:8] == 8'h1;	// src/main/scala/Design.scala:309:18, :341:13, :344:20
  wire       gpio_owned = leaf_owned & owner == 2'h1;	// src/main/scala/Design.scala:234:22, :316:22, :343:11, :352:26, :353:28
  wire       timer_hit = io_addr[15:8] == 8'h2;	// src/main/scala/Design.scala:309:18, :358:14, :361:21
  wire       timer_owned = leaf_owned & owner == 2'h2;	// src/main/scala/Design.scala:234:22, :316:22, :358:14, :369:27, :370:29
  wire       irq_hit = io_addr[15:8] == 8'h3;	// src/main/scala/Design.scala:309:18, :375:12, :378:19
  wire       irq_owned = leaf_owned & (&owner);	// src/main/scala/Design.scala:234:22, :316:22, :386:25, :387:27
  wire       valid_4 =
    irq_owned
      ? io_irq_rsp_valid
      : timer_owned
          ? io_timer_rsp_valid
          : gpio_owned ? io_gpio_rsp_valid : uart_owned ? io_uart_rsp_valid : valid_0;	// src/main/scala/Design.scala:318:22, :336:28, :338:17, :353:28, :355:17, :370:29, :372:17, :387:27, :389:17
  wire       io_req_ready_0 =
    available
    & (irq_hit
         ? io_irq_req_ready
         : timer_hit
             ? io_timer_req_ready
             : gpio_hit ? io_gpio_req_ready : ~hit_1 | io_uart_req_ready);	// src/main/scala/Design.scala:313:21, :327:20, :329:17, :344:20, :346:17, :361:21, :363:17, :378:19, :380:17, :393:29
  wire       commit = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:393:29, :397:26
  always @(posedge clock) begin	// src/main/scala/Design.scala:179:7
    if (reset) begin	// src/main/scala/Design.scala:179:7
      busy <= 1'h0;	// src/main/scala/Design.scala:232:21
      miss <= 1'h0;	// src/main/scala/Design.scala:232:21, :233:21
      owner <= 2'h0;	// src/main/scala/Design.scala:234:22
    end
    else begin	// src/main/scala/Design.scala:179:7
      busy <= ~(valid_4 & ready_active) & (busy | commit);	// src/main/scala/Design.scala:232:21, :317:32, :389:17, :397:26, :398:27, :399:24, :400:19
      if (commit) begin	// src/main/scala/Design.scala:397:26
        miss <= ~(hit_1 | gpio_hit | timer_hit | irq_hit);	// src/main/scala/Design.scala:233:21, :327:20, :344:20, :345:18, :361:21, :362:18, :378:19, :379:18, :392:19
        owner <= io_addr[9:8];	// src/main/scala/Design.scala:234:22, :310:26
      end
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:179:7, :393:29
  assign io_rsp_valid = valid_4;	// src/main/scala/Design.scala:179:7, :389:17
  assign io_rdata =
    irq_owned
      ? io_irq_rdata
      : timer_owned
          ? io_timer_rdata
          : gpio_owned ? io_gpio_rdata : uart_owned ? io_uart_rdata : 32'h0;	// src/main/scala/Design.scala:179:7, :306:10, :336:28, :339:16, :353:28, :356:16, :370:29, :373:16, :387:27, :390:16
  assign io_error =
    irq_owned
      ? io_irq_error
      : timer_owned
          ? io_timer_error
          : gpio_owned ? io_gpio_error : uart_owned ? io_uart_error : {2{valid_0}};	// src/main/scala/Design.scala:179:7, :318:22, :323:17, :336:28, :340:17, :353:28, :357:17, :370:29, :374:17, :387:27, :391:17
  assign io_uart_req_valid = offering & hit_1;	// src/main/scala/Design.scala:179:7, :314:25, :327:20, :330:33
  assign io_uart_write = io_write;	// src/main/scala/Design.scala:179:7
  assign io_uart_addr = io_addr;	// src/main/scala/Design.scala:179:7
  assign io_uart_wdata = io_wdata;	// src/main/scala/Design.scala:179:7
  assign io_uart_wstrb = io_wstrb;	// src/main/scala/Design.scala:179:7
  assign io_uart_rsp_ready = uart_owned & ready_active;	// src/main/scala/Design.scala:179:7, :317:32, :336:28, :337:35
  assign io_gpio_req_valid = offering & gpio_hit;	// src/main/scala/Design.scala:179:7, :314:25, :344:20, :347:33
  assign io_gpio_write = io_write;	// src/main/scala/Design.scala:179:7
  assign io_gpio_addr = io_addr - 16'h100;	// src/main/scala/Design.scala:179:7, :348:27
  assign io_gpio_wdata = io_wdata;	// src/main/scala/Design.scala:179:7
  assign io_gpio_wstrb = io_wstrb;	// src/main/scala/Design.scala:179:7
  assign io_gpio_rsp_ready = gpio_owned & ready_active;	// src/main/scala/Design.scala:179:7, :317:32, :353:28, :354:35
  assign io_timer_req_valid = offering & timer_hit;	// src/main/scala/Design.scala:179:7, :314:25, :361:21, :364:34
  assign io_timer_write = io_write;	// src/main/scala/Design.scala:179:7
  assign io_timer_addr = io_addr - 16'h200;	// src/main/scala/Design.scala:179:7, :365:28
  assign io_timer_wdata = io_wdata;	// src/main/scala/Design.scala:179:7
  assign io_timer_wstrb = io_wstrb;	// src/main/scala/Design.scala:179:7
  assign io_timer_rsp_ready = timer_owned & ready_active;	// src/main/scala/Design.scala:179:7, :317:32, :370:29, :371:37
  assign io_irq_req_valid = offering & irq_hit;	// src/main/scala/Design.scala:179:7, :314:25, :378:19, :381:32
  assign io_irq_write = io_write;	// src/main/scala/Design.scala:179:7
  assign io_irq_addr = io_addr - 16'h300;	// src/main/scala/Design.scala:179:7, :382:26
  assign io_irq_wdata = io_wdata;	// src/main/scala/Design.scala:179:7
  assign io_irq_wstrb = io_wstrb;	// src/main/scala/Design.scala:179:7
  assign io_irq_rsp_ready = irq_owned & ready_active;	// src/main/scala/Design.scala:179:7, :317:32, :387:27, :388:33
endmodule

