// Generated by CIRCT firtool-1.159.0
module Fr198Uart(	// src/main/scala/Design.scala:907:7
  input         clock,	// src/main/scala/Design.scala:907:7
                reset,	// src/main/scala/Design.scala:907:7
                io_req_valid,	// src/main/scala/Design.scala:908:14
                io_write,	// src/main/scala/Design.scala:908:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:908:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:908:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:908:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:908:14
  output        io_req_ready,	// src/main/scala/Design.scala:908:14
                io_rsp_valid,	// src/main/scala/Design.scala:908:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:908:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:908:14
  input         io_rx,	// src/main/scala/Design.scala:908:14
  output        io_tx,	// src/main/scala/Design.scala:908:14
  output [3:0]  io_raw_events	// src/main/scala/Design.scala:908:14
);

  wire        _rxq_io_input_ready;	// src/main/scala/Design.scala:1015:19
  wire        _rxq_io_output_valid;	// src/main/scala/Design.scala:1015:19
  wire [7:0]  _rxq_io_output_data;	// src/main/scala/Design.scala:1015:19
  wire        _txq_io_input_ready;	// src/main/scala/Design.scala:1001:19
  wire        _txq_io_output_valid;	// src/main/scala/Design.scala:1001:19
  wire [7:0]  _txq_io_output_data;	// src/main/scala/Design.scala:1001:19
  wire        _csr_io_ctrl_write_commit;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_ctrl_value;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_ctrl_candidate;	// src/main/scala/Design.scala:953:19
  wire        _csr_io_baud_div_write_commit;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_baud_div_value;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_baud_div_candidate;	// src/main/scala/Design.scala:953:19
  wire        _csr_io_tx_data_write_commit;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_tx_data_candidate;	// src/main/scala/Design.scala:953:19
  wire        _csr_io_rx_data_read_commit;	// src/main/scala/Design.scala:953:19
  reg         sync1;	// src/main/scala/Design.scala:1023:22
  reg         sync2;	// src/main/scala/Design.scala:1024:22
  reg         history;	// src/main/scala/Design.scala:1025:24
  reg         tx_busy;	// src/main/scala/Design.scala:1026:24
  reg         tx_line;	// src/main/scala/Design.scala:1027:24
  reg  [3:0]  tx_index;	// src/main/scala/Design.scala:1028:25
  reg  [7:0]  tx_shift;	// src/main/scala/Design.scala:1029:25
  reg  [31:0] tx_timer;	// src/main/scala/Design.scala:1030:25
  reg  [31:0] tx_div;	// src/main/scala/Design.scala:1031:23
  reg  [3:0]  rx_state;	// src/main/scala/Design.scala:1032:25
  reg  [7:0]  rx_shift;	// src/main/scala/Design.scala:1033:25
  reg  [31:0] rx_timer;	// src/main/scala/Design.scala:1034:25
  reg  [31:0] rx_div;	// src/main/scala/Design.scala:1035:23
  wire        _uart_n97_T = |rx_state;	// src/main/scala/Design.scala:1032:25, :1166:24
  wire        _uart_n11 = tx_busy | _uart_n97_T;	// src/main/scala/Design.scala:1026:24, :1166:24, :1169:24
  wire        _uart_n29 =
    _csr_io_ctrl_write_commit ? _csr_io_ctrl_candidate[0] : _csr_io_ctrl_value[0];	// src/main/scala/Design.scala:953:19, :1170:26, :1171:30, :1191:19
  wire        txq_output_ready = ~tx_busy & _uart_n29 & _txq_io_output_valid & ~reset;	// src/main/scala/Design.scala:1001:19, :1026:24, :1165:35, :1191:19, :1208:24, :1209:26, :1210:26, :1211:26
  wire        _uart_n96_T = rx_timer == 32'h0;	// src/main/scala/Design.scala:1030:25, :1034:25, :1253:25
  wire        _uart_n92_T = _uart_n97_T & _uart_n96_T;	// src/main/scala/Design.scala:1166:24, :1253:25, :1254:26
  wire        _uart_n87 = rx_state == 4'hA;	// src/main/scala/Design.scala:1032:25, :1256:13, :1257:25
  wire        _uart_n110 = _uart_n92_T & _uart_n87 & ~reset;	// src/main/scala/Design.scala:1165:35, :1254:26, :1257:25, :1279:27, :1280:28
  wire        _uart_n111 = _uart_n110 & sync2;	// src/main/scala/Design.scala:1024:22, :1279:27, :1280:28, :1281:28
  wire        rxq_input_valid = _uart_n111 & _rxq_io_input_ready;	// src/main/scala/Design.scala:1015:19, :1281:28, :1282:28
  wire        _uart_n115 = _uart_n111 & ~_rxq_io_input_ready;	// src/main/scala/Design.scala:1015:19, :1281:28, :1284:33, :1285:28
  wire        _uart_n116 = _uart_n110 & ~sync2;	// src/main/scala/Design.scala:1024:22, :1241:22, :1279:27, :1280:28, :1286:28
  wire [31:0] _uart_n30 =
    _csr_io_baud_div_write_commit ? _csr_io_baud_div_candidate : _csr_io_baud_div_value;	// src/main/scala/Design.scala:953:19, :1192:19
  wire        _uart_n55_T = tx_timer == 32'h0;	// src/main/scala/Design.scala:1030:25, :1213:25
  wire        _uart_n67_T = tx_busy & _uart_n55_T;	// src/main/scala/Design.scala:1026:24, :1213:25, :1214:24
  wire        _uart_n85 = rx_state == 4'h1;	// src/main/scala/Design.scala:1032:25, :1255:25
  always @(posedge clock) begin	// src/main/scala/Design.scala:907:7
    if (reset) begin	// src/main/scala/Design.scala:907:7
      sync1 <= 1'h0;	// src/main/scala/Design.scala:1023:22
      sync2 <= 1'h0;	// src/main/scala/Design.scala:1024:22
      history <= 1'h0;	// src/main/scala/Design.scala:1025:24
      tx_busy <= 1'h0;	// src/main/scala/Design.scala:1026:24
      tx_line <= 1'h0;	// src/main/scala/Design.scala:1027:24
      tx_index <= 4'h0;	// src/main/scala/Design.scala:1028:25
      tx_shift <= 8'h0;	// src/main/scala/Design.scala:1029:25
      tx_timer <= 32'h0;	// src/main/scala/Design.scala:1030:25
      tx_div <= 32'h0;	// src/main/scala/Design.scala:1030:25, :1031:23
      rx_state <= 4'h0;	// src/main/scala/Design.scala:1032:25
      rx_shift <= 8'h0;	// src/main/scala/Design.scala:1029:25, :1033:25
      rx_timer <= 32'h0;	// src/main/scala/Design.scala:1030:25, :1034:25
      rx_div <= 32'h0;	// src/main/scala/Design.scala:1030:25, :1035:23
    end
    else begin	// src/main/scala/Design.scala:907:7
      sync1 <= io_rx;	// src/main/scala/Design.scala:1023:22
      sync2 <= sync1;	// src/main/scala/Design.scala:1023:22, :1024:22
      history <= sync2;	// src/main/scala/Design.scala:1024:22, :1025:24
      tx_busy <= txq_output_ready | ~(_uart_n67_T & tx_index == 4'h9) & tx_busy;	// src/main/scala/Design.scala:1026:24, :1028:25, :1209:26, :1210:26, :1211:26, :1214:24, :1215:13, :1216:25, :1217:26, :1218:19, :1219:19
      tx_line <=
        ~txq_output_ready & (_uart_n67_T ? tx_index == 4'h8 | tx_shift[0] : tx_line);	// src/main/scala/Design.scala:1027:24, :1028:25, :1029:25, :1209:26, :1210:26, :1211:26, :1214:24, :1232:13, :1233:25, :1234:24, :1235:19, :1236:19, :1237:19
      if (txq_output_ready) begin	// src/main/scala/Design.scala:1209:26, :1210:26, :1211:26
        tx_index <= 4'h0;	// src/main/scala/Design.scala:1028:25
        tx_shift <= _txq_io_output_data;	// src/main/scala/Design.scala:1001:19, :1029:25
        tx_timer <= _uart_n30;	// src/main/scala/Design.scala:1030:25, :1192:19
        tx_div <= _uart_n30;	// src/main/scala/Design.scala:1031:23, :1192:19
      end
      else begin	// src/main/scala/Design.scala:1209:26, :1210:26, :1211:26
        if (_uart_n67_T) begin	// src/main/scala/Design.scala:1214:24
          tx_index <= tx_index + 4'h1;	// src/main/scala/Design.scala:1028:25, :1220:25
          tx_shift <= {1'h0, tx_shift[7:1]};	// src/main/scala/Design.scala:1029:25, :1228:24, :1229:32
        end
        if (tx_busy)	// src/main/scala/Design.scala:1026:24
          tx_timer <= _uart_n55_T ? tx_div : tx_timer - 32'h1;	// src/main/scala/Design.scala:1030:25, :1031:23, :1213:25, :1223:25, :1224:19
      end
      if (~_uart_n97_T & ~sync2 & history & _uart_n29 & ~reset) begin	// src/main/scala/Design.scala:1024:22, :1025:24, :1165:35, :1166:24, :1191:19, :1241:22, :1242:26, :1243:25, :1244:26, :1245:26
        rx_state <= 4'h1;	// src/main/scala/Design.scala:1032:25
        rx_timer <= {1'h0, _uart_n30[31:1]} + {31'h0, _uart_n30[0]} - 32'h1;	// src/main/scala/Design.scala:1034:25, :1192:19, :1246:25, :1248:25, :1251:26, :1252:26
        rx_div <= _uart_n30;	// src/main/scala/Design.scala:1035:23, :1192:19
      end
      else begin	// src/main/scala/Design.scala:1242:26, :1243:25, :1244:26, :1245:26
        if (_uart_n92_T & (_uart_n85 & sync2 | _uart_n87))	// src/main/scala/Design.scala:1024:22, :1254:26, :1255:25, :1257:25, :1258:26, :1259:26, :1260:26
          rx_state <= 4'h0;	// src/main/scala/Design.scala:1032:25
        else if (_uart_n92_T)	// src/main/scala/Design.scala:1254:26
          rx_state <= rx_state + 4'h1;	// src/main/scala/Design.scala:1032:25, :1261:25
        if (_uart_n97_T)	// src/main/scala/Design.scala:1166:24
          rx_timer <= _uart_n96_T ? rx_div : rx_timer - 32'h1;	// src/main/scala/Design.scala:1034:25, :1035:23, :1253:25, :1265:25, :1266:19
      end
      if (_uart_n92_T & ~_uart_n85 & ~_uart_n87)	// src/main/scala/Design.scala:1254:26, :1255:25, :1257:25, :1271:27, :1273:27, :1274:28, :1275:27
        rx_shift <= {sync2, rx_shift[7:1]};	// src/main/scala/Design.scala:1024:22, :1033:25, :1276:25, :1277:33
    end
  end // always @(posedge)
  BitloomUartCsrRegisters csr (	// src/main/scala/Design.scala:953:19
    .clock                    (clock),
    .reset                    (reset),
    .io_req_valid             (io_req_valid),
    .io_write                 (io_write),
    .io_addr                  (io_addr),
    .io_wdata                 (io_wdata),
    .io_wstrb                 (io_wstrb),
    .io_rsp_ready             (io_rsp_ready),
    .io_req_ready             (io_req_ready),
    .io_rsp_valid             (io_rsp_valid),
    .io_rdata                 (io_rdata),
    .io_error                 (io_error),
    .io_ctrl_write_commit     (_csr_io_ctrl_write_commit),
    .io_ctrl_value            (_csr_io_ctrl_value),
    .io_ctrl_candidate        (_csr_io_ctrl_candidate),
    .io_ctrl_write_reject
      (_uart_n11 & _csr_io_ctrl_value[0] != _csr_io_ctrl_candidate[0]
       | _csr_io_ctrl_candidate[0] & _csr_io_baud_div_value < 32'h3),	// src/main/scala/Design.scala:953:19, :1169:24, :1170:26, :1171:30, :1172:26, :1175:26, :1176:13, :1177:31, :1178:26, :1179:26
    .io_baud_div_write_commit (_csr_io_baud_div_write_commit),
    .io_baud_div_value        (_csr_io_baud_div_value),
    .io_baud_div_candidate    (_csr_io_baud_div_candidate),
    .io_baud_div_write_reject
      (_uart_n11 | _csr_io_ctrl_value[0] & _csr_io_baud_div_candidate < 32'h3),	// src/main/scala/Design.scala:953:19, :1169:24, :1170:26, :1176:13, :1181:35, :1182:26, :1183:26
    .io_status_value
      ({28'h0, _uart_n97_T, tx_busy, ~_txq_io_input_ready, _rxq_io_output_valid}),	// src/main/scala/Design.scala:1001:19, :1015:19, :1026:24, :1166:24, :1186:32, :1196:13, :1197:32
    .io_tx_data_write_commit  (_csr_io_tx_data_write_commit),
    .io_tx_data_candidate     (_csr_io_tx_data_candidate),
    .io_tx_data_write_reject  (~_txq_io_input_ready),	// src/main/scala/Design.scala:1001:19, :1186:32
    .io_rx_data_read_commit   (_csr_io_rx_data_read_commit),
    .io_rx_data_value         ({24'h0, _rxq_io_output_data}),	// src/main/scala/Design.scala:1015:19, :1199:13, :1200:32
    .io_rx_data_read_reject   (~_rxq_io_output_valid),	// src/main/scala/Design.scala:1015:19, :1189:33
    .io_event_bits
      ({28'h0, _uart_n116, _uart_n115, txq_output_ready, rxq_input_valid})	// src/main/scala/Design.scala:1196:13, :1209:26, :1210:26, :1211:26, :1282:28, :1285:28, :1286:28, :1292:33
  );	// src/main/scala/Design.scala:953:19
  BitloomUartCsrFifo8x4 txq (	// src/main/scala/Design.scala:1001:19
    .clock           (clock),
    .reset           (reset),
    .io_input_valid  (_csr_io_tx_data_write_commit),	// src/main/scala/Design.scala:953:19
    .io_output_ready (txq_output_ready),	// src/main/scala/Design.scala:1209:26, :1210:26, :1211:26
    .io_input_data   (_csr_io_tx_data_candidate[7:0]),	// src/main/scala/Design.scala:953:19, :1203:33
    .io_input_ready  (_txq_io_input_ready),
    .io_output_valid (_txq_io_output_valid),
    .io_output_data  (_txq_io_output_data)
  );	// src/main/scala/Design.scala:1001:19
  BitloomUartCsrFifo8x4 rxq (	// src/main/scala/Design.scala:1015:19
    .clock           (clock),
    .reset           (reset),
    .io_input_valid  (rxq_input_valid),	// src/main/scala/Design.scala:1282:28
    .io_output_ready (_csr_io_rx_data_read_commit),	// src/main/scala/Design.scala:953:19
    .io_input_data   (rx_shift),	// src/main/scala/Design.scala:1033:25
    .io_input_ready  (_rxq_io_input_ready),
    .io_output_valid (_rxq_io_output_valid),
    .io_output_data  (_rxq_io_output_data)
  );	// src/main/scala/Design.scala:1015:19
  assign io_tx = ~tx_busy | tx_line;	// src/main/scala/Design.scala:907:7, :1026:24, :1027:24, :1238:19
  assign io_raw_events = {_uart_n116, _uart_n115, txq_output_ready, rxq_input_valid};	// src/main/scala/Design.scala:907:7, :1209:26, :1210:26, :1211:26, :1282:28, :1285:28, :1286:28, :1290:33
endmodule

