// Generated by CIRCT firtool-1.159.0
module Fr198Bridge(
  input         clk,
                rst,
  input  [15:0] s_axi_awaddr,
  input         s_axi_awvalid,
  input  [31:0] s_axi_wdata,
  input  [3:0]  s_axi_wstrb,
  input         s_axi_wvalid,
                s_axi_bready,
  input  [15:0] s_axi_araddr,
  input         s_axi_arvalid,
                s_axi_rready,
                csr_req_ready,
                csr_rsp_valid,
  input  [31:0] csr_rdata,
  input  [1:0]  csr_error,
  output        s_axi_awready,
                s_axi_wready,
                s_axi_arready,
                s_axi_bvalid,
  output [1:0]  s_axi_bresp,
  output        s_axi_rvalid,
  output [31:0] s_axi_rdata,
  output [1:0]  s_axi_rresp,
  output        csr_req_valid,
                csr_write,
  output [15:0] csr_addr,
  output [31:0] csr_wdata,
  output [3:0]  csr_wstrb,
  output        csr_rsp_ready
);

  reg         aw_full;
  reg         w_full;
  reg         ar_full;
  reg  [15:0] aw_addr;
  reg  [31:0] w_data;
  reg  [3:0]  w_strb;
  reg  [15:0] ar_addr;
  reg         offer;
  reg         offer_write;
  reg         exec;
  reg         owner;
  reg         prefer_write;
  reg         b_full;
  reg         r_full;
  reg  [1:0]  b_error;
  reg  [1:0]  r_error;
  reg  [31:0] r_data;
  reg  [31:0] offer_data;
  reg  [3:0]  offer_strb;
  wire        _csr_req_valid_output = offer & ~rst;
  wire        _csr_rsp_ready_output = exec & ~rst;
  wire        aw_take = ~aw_full & s_axi_awvalid;
  wire        w_take = ~w_full & s_axi_wvalid;
  wire        ar_take = ~ar_full & s_axi_arvalid;
  wire        we = aw_full & w_full & ~b_full;
  wire        re = ar_full & ~r_full;
  wire        select = ~offer & ~exec & (we | re);
  wire        commit = _csr_req_valid_output & csr_req_ready;
  wire        write_commit = commit & offer_write;
  wire        response = _csr_rsp_ready_output & csr_rsp_valid;
  wire        write_response = response & owner;
  wire        read_response = response & ~owner;
  always @(posedge clk) begin
    if (rst) begin
      aw_full <= 1'h0;
      w_full <= 1'h0;
      ar_full <= 1'h0;
      aw_addr <= 16'h0;
      w_data <= 32'h0;
      w_strb <= 4'h0;
      ar_addr <= 16'h0;
      offer <= 1'h0;
      offer_write <= 1'h0;
      exec <= 1'h0;
      owner <= 1'h0;
      prefer_write <= 1'h0;
      b_full <= 1'h0;
      r_full <= 1'h0;
      b_error <= 2'h0;
      r_error <= 2'h0;
      r_data <= 32'h0;
      offer_data <= 32'h0;
      offer_strb <= 4'h0;
    end
    else begin
      aw_full <= ~write_commit & (aw_take | aw_full);
      w_full <= ~write_commit & (w_take | w_full);
      ar_full <= ~(commit & ~offer_write) & (ar_take | ar_full);
      if (aw_take)
        aw_addr <= s_axi_awaddr;
      if (w_take) begin
        w_data <= s_axi_wdata;
        w_strb <= s_axi_wstrb;
      end
      if (ar_take)
        ar_addr <= s_axi_araddr;
      offer <= ~commit & (select | offer);
      if (select) begin
        offer_write <= we & (prefer_write | ~re);
        offer_data <= w_data;
        offer_strb <= w_strb;
      end
      exec <= ~response & (commit | exec);
      if (commit) begin
        owner <= offer_write;
        prefer_write <= ~offer_write;
      end
      b_full <= write_response | ~(b_full & s_axi_bready) & b_full;
      r_full <= read_response | ~(r_full & s_axi_rready) & r_full;
      if (write_response)
        b_error <= csr_error;
      if (read_response) begin
        r_error <= csr_error;
        r_data <= csr_rdata;
      end
    end
  end // always @(posedge)
  assign s_axi_awready = ~aw_full;
  assign s_axi_wready = ~w_full;
  assign s_axi_arready = ~ar_full;
  assign s_axi_bvalid = b_full;
  assign s_axi_bresp = b_error;
  assign s_axi_rvalid = r_full;
  assign s_axi_rdata = r_data;
  assign s_axi_rresp = r_error;
  assign csr_req_valid = _csr_req_valid_output;
  assign csr_write = offer_write;
  assign csr_addr = offer_write ? aw_addr : ar_addr;
  assign csr_wdata = offer_data;
  assign csr_wstrb = offer_strb;
  assign csr_rsp_ready = _csr_rsp_ready_output;
endmodule

module Fr198Decoder(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  input         uart_req_ready,
                uart_rsp_valid,
  input  [31:0] uart_rdata,
  input  [1:0]  uart_error,
  output        uart_req_valid,
                uart_write,
  output [15:0] uart_addr,
  output [31:0] uart_wdata,
  output [3:0]  uart_wstrb,
  output        uart_rsp_ready,
  input         gpio_req_ready,
                gpio_rsp_valid,
  input  [31:0] gpio_rdata,
  input  [1:0]  gpio_error,
  output        gpio_req_valid,
                gpio_write,
  output [15:0] gpio_addr,
  output [31:0] gpio_wdata,
  output [3:0]  gpio_wstrb,
  output        gpio_rsp_ready,
  input         timer_req_ready,
                timer_rsp_valid,
  input  [31:0] timer_rdata,
  input  [1:0]  timer_error,
  output        timer_req_valid,
                timer_write,
  output [15:0] timer_addr,
  output [31:0] timer_wdata,
  output [3:0]  timer_wstrb,
  output        timer_rsp_ready,
  input         irq_req_ready,
                irq_rsp_valid,
  input  [31:0] irq_rdata,
  input  [1:0]  irq_error,
  output        irq_req_valid,
                irq_write,
  output [15:0] irq_addr,
  output [31:0] irq_wdata,
  output [3:0]  irq_wstrb,
  output        irq_rsp_ready
);

  reg        busy;
  reg        miss;
  reg  [1:0] owner;
  wire       available = ~busy & ~rst;
  wire       offering = available & req_valid;
  wire       leaf_owned = busy & ~miss;
  wire       ready_active = rsp_ready & ~rst;
  wire       valid_0 = busy & miss;
  wire       hit_1 = addr[15:8] == 8'h0;
  wire       uart_owned = leaf_owned & owner == 2'h0;
  wire       gpio_hit = addr[15:8] == 8'h1;
  wire       gpio_owned = leaf_owned & owner == 2'h1;
  wire       timer_hit = addr[15:8] == 8'h2;
  wire       timer_owned = leaf_owned & owner == 2'h2;
  wire       irq_hit = addr[15:8] == 8'h3;
  wire       irq_owned = leaf_owned & (&owner);
  wire       valid_4 =
    irq_owned
      ? irq_rsp_valid
      : timer_owned
          ? timer_rsp_valid
          : gpio_owned ? gpio_rsp_valid : uart_owned ? uart_rsp_valid : valid_0;
  wire       _req_ready_output =
    available
    & (irq_hit
         ? irq_req_ready
         : timer_hit
             ? timer_req_ready
             : gpio_hit ? gpio_req_ready : ~hit_1 | uart_req_ready);
  wire       commit = req_valid & _req_ready_output;
  always @(posedge clk) begin
    if (rst) begin
      busy <= 1'h0;
      miss <= 1'h0;
      owner <= 2'h0;
    end
    else begin
      busy <= ~(valid_4 & ready_active) & (busy | commit);
      if (commit) begin
        miss <= ~(hit_1 | gpio_hit | timer_hit | irq_hit);
        owner <= addr[9:8];
      end
    end
  end // always @(posedge)
  assign req_ready = _req_ready_output;
  assign rsp_valid = valid_4;
  assign rdata =
    irq_owned
      ? irq_rdata
      : timer_owned
          ? timer_rdata
          : gpio_owned ? gpio_rdata : uart_owned ? uart_rdata : 32'h0;
  assign error =
    irq_owned
      ? irq_error
      : timer_owned
          ? timer_error
          : gpio_owned ? gpio_error : uart_owned ? uart_error : {2{valid_0}};
  assign uart_req_valid = offering & hit_1;
  assign uart_write = write;
  assign uart_addr = addr;
  assign uart_wdata = wdata;
  assign uart_wstrb = wstrb;
  assign uart_rsp_ready = uart_owned & ready_active;
  assign gpio_req_valid = offering & gpio_hit;
  assign gpio_write = write;
  assign gpio_addr = addr - 16'h100;
  assign gpio_wdata = wdata;
  assign gpio_wstrb = wstrb;
  assign gpio_rsp_ready = gpio_owned & ready_active;
  assign timer_req_valid = offering & timer_hit;
  assign timer_write = write;
  assign timer_addr = addr - 16'h200;
  assign timer_wdata = wdata;
  assign timer_wstrb = wstrb;
  assign timer_rsp_ready = timer_owned & ready_active;
  assign irq_req_valid = offering & irq_hit;
  assign irq_write = write;
  assign irq_addr = addr - 16'h300;
  assign irq_wdata = wdata;
  assign irq_wstrb = wstrb;
  assign irq_rsp_ready = irq_owned & ready_active;
endmodule

module BitloomUartCsrRegisters(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  output        ctrl_write_commit,
  output [31:0] ctrl_value,
                ctrl_candidate,
  input         ctrl_write_reject,
  output        baud_div_write_commit,
  output [31:0] baud_div_value,
                baud_div_candidate,
  input         baud_div_write_reject,
  input  [31:0] status_value,
  output        tx_data_write_commit,
  output [31:0] tx_data_candidate,
  input         tx_data_write_reject,
  output        rx_data_read_commit,
  input  [31:0] rx_data_value,
  input         rx_data_read_reject,
  input  [31:0] event_bits
);

  reg         _csr_pending;
  reg  [31:0] _csr_data;
  reg  [1:0]  _csr_error;
  reg  [31:0] _csr_value0;
  reg  [31:0] _csr_value1;
  reg  [31:0] _csr_value5;
  wire        _csr_n9 = ~_csr_pending & ~rst;
  wire        _csr_n10 = req_valid & _csr_n9;
  wire [31:0] _csr_n66 =
    (wstrb[0] ? 32'hFF : 32'h0) | (wstrb[1] ? 32'hFF00 : 32'h0)
    | (wstrb[2] ? 32'hFF0000 : 32'h0) | (wstrb[3] ? 32'hFF000000 : 32'h0);
  wire [31:0] _csr_n32 = {31'h0, _csr_value0[0]};
  wire        _csr_n34 = addr == 16'h0;
  wire [31:0] _csr_n46 =
    _csr_n32 & {31'h7FFFFFFF, ~(_csr_n66[0])} | wdata & {31'h0, _csr_n66[0]};
  wire        _csr_n50 = write & (~(_csr_n66[0]) | ~ctrl_write_reject);
  wire        _csr_n52 = _csr_n10 & _csr_n34 & _csr_n50 & _csr_n66[0];
  wire        _csr_n62 = addr == 16'h4;
  wire        _csr_n69 = |_csr_n66;
  wire [31:0] _csr_n74 = _csr_value1 & ~_csr_n66 | wdata & _csr_n66;
  wire        _csr_n78 = write & (~_csr_n69 | ~baud_div_write_reject);
  wire        _csr_n80 = _csr_n10 & _csr_n62 & _csr_n78 & _csr_n69;
  wire        _csr_n101 = addr == 16'hC;
  wire        _csr_n108 = |(_csr_n66[7:0]);
  wire        _csr_n116 = write & (~_csr_n108 | ~tx_data_write_reject);
  wire        _csr_n124 = addr == 16'h10;
  wire        _csr_n130 = ~write & ~rx_data_read_reject;
  wire        _csr_n90 = addr == 16'h8;
  wire [31:0] _csr_n136 = {28'h0, _csr_value5[3:0]};
  wire        _csr_n138 = addr == 16'h14;
  always @(posedge clk) begin
    if (rst) begin
      _csr_pending <= 1'h0;
      _csr_data <= 32'h0;
      _csr_error <= 2'h0;
      _csr_value0 <= 32'h0;
      _csr_value1 <= 32'h0;
      _csr_value5 <= 32'h0;
    end
    else begin
      _csr_pending <= _csr_n10 | ~rsp_ready & _csr_pending;
      if (_csr_n10) begin
        _csr_data <=
          _csr_n138
            ? (write ? 32'h0 : _csr_n136)
            : _csr_n124
                ? (_csr_n130 ? {24'h0, rx_data_value[7:0]} : 32'h0)
                : _csr_n101
                    ? 32'h0
                    : _csr_n90
                        ? (write ? 32'h0 : {28'h0, status_value[3:0]})
                        : _csr_n62
                            ? (write ? 32'h0 : _csr_value1)
                            : _csr_n34 & ~write ? _csr_n32 : 32'h0;
        _csr_error <=
          _csr_n138
            ? 2'h0
            : {_csr_n124
                 ? ~_csr_n130
                 : _csr_n101
                     ? ~_csr_n116
                     : _csr_n90
                         ? write
                         : _csr_n62
                             ? ~(~write | _csr_n78)
                             : ~(_csr_n34 & (~write | _csr_n50)),
               1'h0};
      end
      _csr_value0 <= _csr_n52 ? _csr_n46 : _csr_n32;
      if (_csr_n80)
        _csr_value1 <= _csr_n74;
      _csr_value5 <=
        _csr_n136
        & ~(_csr_n10 & _csr_n138 & write & (|(_csr_n66[3:0]))
              ? wdata & {28'h0, _csr_n66[3:0]}
              : 32'h0) | {28'h0, event_bits[3:0]};
    end
  end // always @(posedge)
  assign req_ready = _csr_n9;
  assign rsp_valid = _csr_pending;
  assign rdata = _csr_data;
  assign error = _csr_error;
  assign ctrl_write_commit = _csr_n52;
  assign ctrl_value = _csr_n32;
  assign ctrl_candidate = _csr_n46;
  assign baud_div_write_commit = _csr_n80;
  assign baud_div_value = _csr_value1;
  assign baud_div_candidate = _csr_n74;
  assign tx_data_write_commit = _csr_n10 & _csr_n101 & _csr_n116 & _csr_n108;
  assign tx_data_candidate = wdata & {24'h0, _csr_n66[7:0]};
  assign rx_data_read_commit = _csr_n10 & _csr_n124 & _csr_n130;
endmodule

module BitloomUartCsrFifo8x4(
  input        clk,
               rst,
               input_valid,
               output_ready,
  input  [7:0] input_data,
  output       input_ready,
               output_valid,
  output [7:0] output_data
);

  reg  [2:0] count;
  reg  [7:0] slot_0;
  reg  [7:0] slot_1;
  reg  [7:0] slot_2;
  reg  [7:0] slot_3;
  wire       _output_valid_output = |count;
  wire       _input_ready_output = count != 3'h4;
  wire       push = input_valid & _input_ready_output;
  wire       pop = _output_valid_output & output_ready;
  wire [2:0] decremented = count - 3'h1;
  wire [2:0] after_pop = pop ? decremented : count;
  always @(posedge clk) begin
    if (rst) begin
      count <= 3'h0;
      slot_0 <= 8'h0;
      slot_1 <= 8'h0;
      slot_2 <= 8'h0;
      slot_3 <= 8'h0;
    end
    else begin
      if (push)
        count <= after_pop + 3'h1;
      else if (pop)
        count <= decremented;
      if (push & after_pop == 3'h0)
        slot_0 <= input_data;
      else if (pop)
        slot_0 <= slot_1;
      if (push & after_pop == 3'h1)
        slot_1 <= input_data;
      else if (pop)
        slot_1 <= slot_2;
      if (push & after_pop == 3'h2)
        slot_2 <= input_data;
      else if (pop)
        slot_2 <= slot_3;
      if (push & after_pop == 3'h3)
        slot_3 <= input_data;
    end
  end // always @(posedge)
  assign input_ready = _input_ready_output;
  assign output_valid = _output_valid_output;
  assign output_data = slot_0;
endmodule

module Fr198Uart(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  input         rx,
  output        tx,
  output [3:0]  raw_events
);

  wire        _rxq_input_ready;
  wire        _rxq_output_valid;
  wire [7:0]  _rxq_output_data;
  wire        _txq_input_ready;
  wire        _txq_output_valid;
  wire [7:0]  _txq_output_data;
  wire        _csr_ctrl_write_commit;
  wire [31:0] _csr_ctrl_value;
  wire [31:0] _csr_ctrl_candidate;
  wire        _csr_baud_div_write_commit;
  wire [31:0] _csr_baud_div_value;
  wire [31:0] _csr_baud_div_candidate;
  wire        _csr_tx_data_write_commit;
  wire [31:0] _csr_tx_data_candidate;
  wire        _csr_rx_data_read_commit;
  reg         sync1;
  reg         sync2;
  reg         history;
  reg         tx_busy;
  reg         tx_line;
  reg  [3:0]  tx_index;
  reg  [7:0]  tx_shift;
  reg  [31:0] tx_timer;
  reg  [31:0] tx_div;
  reg  [3:0]  rx_state;
  reg  [7:0]  rx_shift;
  reg  [31:0] rx_timer;
  reg  [31:0] rx_div;
  wire        _uart_n10 = |rx_state;
  wire        _uart_n11 = tx_busy | _uart_n10;
  wire        _uart_n29 =
    _csr_ctrl_write_commit ? _csr_ctrl_candidate[0] : _csr_ctrl_value[0];
  wire        txq_output_ready = ~tx_busy & _uart_n29 & _txq_output_valid & ~rst;
  wire        _uart_n83 = rx_timer == 32'h0;
  wire        _uart_n84 = _uart_n10 & _uart_n83;
  wire        _uart_n87 = rx_state == 4'hA;
  wire        _uart_n110 = _uart_n84 & _uart_n87 & ~rst;
  wire        _uart_n111 = _uart_n110 & sync2;
  wire        rxq_input_valid = _uart_n111 & _rxq_input_ready;
  wire        _uart_n115 = _uart_n111 & ~_rxq_input_ready;
  wire        _uart_n116 = _uart_n110 & ~sync2;
  wire [31:0] _uart_n30 =
    _csr_baud_div_write_commit ? _csr_baud_div_candidate : _csr_baud_div_value;
  wire        _uart_n44 = tx_timer == 32'h0;
  wire        _uart_n45 = tx_busy & _uart_n44;
  wire        _uart_n85 = rx_state == 4'h1;
  always @(posedge clk) begin
    if (rst) begin
      sync1 <= 1'h0;
      sync2 <= 1'h0;
      history <= 1'h0;
      tx_busy <= 1'h0;
      tx_line <= 1'h0;
      tx_index <= 4'h0;
      tx_shift <= 8'h0;
      tx_timer <= 32'h0;
      tx_div <= 32'h0;
      rx_state <= 4'h0;
      rx_shift <= 8'h0;
      rx_timer <= 32'h0;
      rx_div <= 32'h0;
    end
    else begin
      sync1 <= rx;
      sync2 <= sync1;
      history <= sync2;
      tx_busy <= txq_output_ready | ~(_uart_n45 & tx_index == 4'h9) & tx_busy;
      tx_line <=
        ~txq_output_ready & (_uart_n45 ? tx_index == 4'h8 | tx_shift[0] : tx_line);
      if (txq_output_ready) begin
        tx_index <= 4'h0;
        tx_shift <= _txq_output_data;
        tx_timer <= _uart_n30;
        tx_div <= _uart_n30;
      end
      else begin
        if (_uart_n45) begin
          tx_index <= tx_index + 4'h1;
          tx_shift <= {1'h0, tx_shift[7:1]};
        end
        if (tx_busy)
          tx_timer <= _uart_n44 ? tx_div : tx_timer - 32'h1;
      end
      if (~_uart_n10 & ~sync2 & history & _uart_n29 & ~rst) begin
        rx_state <= 4'h1;
        rx_timer <= {1'h0, _uart_n30[31:1]} + {31'h0, _uart_n30[0]} - 32'h1;
        rx_div <= _uart_n30;
      end
      else begin
        if (_uart_n84 & (_uart_n85 & sync2 | _uart_n87))
          rx_state <= 4'h0;
        else if (_uart_n84)
          rx_state <= rx_state + 4'h1;
        if (_uart_n10)
          rx_timer <= _uart_n83 ? rx_div : rx_timer - 32'h1;
      end
      if (_uart_n84 & ~_uart_n85 & ~_uart_n87)
        rx_shift <= {sync2, rx_shift[7:1]};
    end
  end // always @(posedge)
  BitloomUartCsrRegisters csr (
    .clk                   (clk),
    .rst                   (rst),
    .req_valid             (req_valid),
    .write                 (write),
    .addr                  (addr),
    .wdata                 (wdata),
    .wstrb                 (wstrb),
    .rsp_ready             (rsp_ready),
    .req_ready             (req_ready),
    .rsp_valid             (rsp_valid),
    .rdata                 (rdata),
    .error                 (error),
    .ctrl_write_commit     (_csr_ctrl_write_commit),
    .ctrl_value            (_csr_ctrl_value),
    .ctrl_candidate        (_csr_ctrl_candidate),
    .ctrl_write_reject
      (_uart_n11 & _csr_ctrl_value[0] != _csr_ctrl_candidate[0] | _csr_ctrl_candidate[0]
       & _csr_baud_div_value < 32'h3),
    .baud_div_write_commit (_csr_baud_div_write_commit),
    .baud_div_value        (_csr_baud_div_value),
    .baud_div_candidate    (_csr_baud_div_candidate),
    .baud_div_write_reject
      (_uart_n11 | _csr_ctrl_value[0] & _csr_baud_div_candidate < 32'h3),
    .status_value
      ({28'h0, _uart_n10, tx_busy, ~_txq_input_ready, _rxq_output_valid}),
    .tx_data_write_commit  (_csr_tx_data_write_commit),
    .tx_data_candidate     (_csr_tx_data_candidate),
    .tx_data_write_reject  (~_txq_input_ready),
    .rx_data_read_commit   (_csr_rx_data_read_commit),
    .rx_data_value         ({24'h0, _rxq_output_data}),
    .rx_data_read_reject   (~_rxq_output_valid),
    .event_bits
      ({28'h0, _uart_n116, _uart_n115, txq_output_ready, rxq_input_valid})
  );
  BitloomUartCsrFifo8x4 txq (
    .clk          (clk),
    .rst          (rst),
    .input_valid  (_csr_tx_data_write_commit),
    .output_ready (txq_output_ready),
    .input_data   (_csr_tx_data_candidate[7:0]),
    .input_ready  (_txq_input_ready),
    .output_valid (_txq_output_valid),
    .output_data  (_txq_output_data)
  );
  BitloomUartCsrFifo8x4 rxq (
    .clk          (clk),
    .rst          (rst),
    .input_valid  (rxq_input_valid),
    .output_ready (_csr_rx_data_read_commit),
    .input_data   (rx_shift),
    .input_ready  (_rxq_input_ready),
    .output_valid (_rxq_output_valid),
    .output_data  (_rxq_output_data)
  );
  assign tx = ~tx_busy | tx_line;
  assign raw_events = {_uart_n116, _uart_n115, txq_output_ready, rxq_input_valid};
endmodule

module BitloomGpioCsrRegisters(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  output [31:0] dir_value,
  output        out_write_commit,
  input  [31:0] out_value,
  output [31:0] out_candidate,
  input  [31:0] in_value,
  output        set_write_commit,
  output [31:0] set_candidate,
  output        clear_write_commit,
  output [31:0] clear_candidate,
  input  [31:0] rise_bits
);

  reg         _csr_pending;
  reg  [31:0] _csr_data;
  reg  [1:0]  _csr_error;
  reg  [31:0] _csr_value0;
  reg  [31:0] _csr_value5;
  wire        _csr_n9 = ~_csr_pending & ~rst;
  wire        _csr_n10 = req_valid & _csr_n9;
  wire [31:0] _csr_n137 =
    (wstrb[0] ? 32'hFF : 32'h0) | (wstrb[1] ? 32'hFF00 : 32'h0)
    | (wstrb[2] ? 32'hFF0000 : 32'h0) | (wstrb[3] ? 32'hFF000000 : 32'h0);
  wire        _csr_n59 = addr == 16'h4;
  wire        _csr_n94 = addr == 16'hC;
  wire        _csr_n113 = addr == 16'h10;
  wire        _csr_n83 = addr == 16'h8;
  wire        _csr_n34 = addr == 16'h0;
  wire        _csr_n133 = addr == 16'h14;
  always @(posedge clk) begin
    if (rst) begin
      _csr_pending <= 1'h0;
      _csr_data <= 32'h0;
      _csr_error <= 2'h0;
      _csr_value0 <= 32'h0;
      _csr_value5 <= 32'h0;
    end
    else begin
      _csr_pending <= _csr_n10 | ~rsp_ready & _csr_pending;
      if (_csr_n10) begin
        _csr_data <=
          _csr_n133
            ? (write ? 32'h0 : _csr_value5)
            : _csr_n113 | _csr_n94
                ? 32'h0
                : _csr_n83
                    ? (write ? 32'h0 : in_value)
                    : _csr_n59
                        ? (write ? 32'h0 : out_value)
                        : _csr_n34 & ~write ? _csr_value0 : 32'h0;
        _csr_error <=
          _csr_n133
            ? 2'h0
            : _csr_n113
                ? {~write, 1'h0}
                : _csr_n94
                    ? {~write, 1'h0}
                    : _csr_n83 ? {write, 1'h0} : _csr_n59 ? 2'h0 : {~_csr_n34, 1'h0};
      end
      if (_csr_n10 & _csr_n34 & write & (|_csr_n137))
        _csr_value0 <= _csr_value0 & ~_csr_n137 | wdata & _csr_n137;
      _csr_value5 <=
        _csr_value5
        & ~(_csr_n10 & _csr_n133 & write & (|_csr_n137) ? wdata & _csr_n137 : 32'h0)
        | rise_bits;
    end
  end // always @(posedge)
  assign req_ready = _csr_n9;
  assign rsp_valid = _csr_pending;
  assign rdata = _csr_data;
  assign error = _csr_error;
  assign dir_value = _csr_value0;
  assign out_write_commit = _csr_n10 & _csr_n59 & write & (|_csr_n137);
  assign out_candidate = out_value & ~_csr_n137 | wdata & _csr_n137;
  assign set_write_commit = _csr_n10 & _csr_n94 & write & (|_csr_n137);
  assign set_candidate = wdata & _csr_n137;
  assign clear_write_commit = _csr_n10 & _csr_n113 & write & (|_csr_n137);
  assign clear_candidate = wdata & _csr_n137;
endmodule

module Fr198Gpio(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  input  [31:0] pad_in,
  output [31:0] pad_out,
                pad_oe,
  output        raw_event
);

  wire [31:0] _csr_dir_value;
  wire        _csr_out_write_commit;
  wire [31:0] _csr_out_candidate;
  wire        _csr_set_write_commit;
  wire [31:0] _csr_set_candidate;
  wire        _csr_clear_write_commit;
  wire [31:0] _csr_clear_candidate;
  reg  [31:0] out_r;
  reg  [31:0] sync1;
  reg  [31:0] sync2;
  reg  [31:0] history;
  wire [31:0] rise_bits = sync2 & ~history & ~_csr_dir_value;
  always @(posedge clk) begin
    if (rst) begin
      out_r <= 32'h0;
      sync1 <= 32'h0;
      sync2 <= 32'h0;
      history <= 32'h0;
    end
    else begin
      out_r <=
        _csr_out_write_commit
          ? _csr_out_candidate
          : _csr_set_write_commit
              ? out_r | _csr_set_candidate
              : ({32{~_csr_clear_write_commit}} | ~_csr_clear_candidate) & out_r;
      sync1 <= pad_in;
      sync2 <= sync1;
      history <= sync2;
    end
  end // always @(posedge)
  BitloomGpioCsrRegisters csr (
    .clk                (clk),
    .rst                (rst),
    .req_valid          (req_valid),
    .write              (write),
    .addr               (addr),
    .wdata              (wdata),
    .wstrb              (wstrb),
    .rsp_ready          (rsp_ready),
    .req_ready          (req_ready),
    .rsp_valid          (rsp_valid),
    .rdata              (rdata),
    .error              (error),
    .dir_value          (_csr_dir_value),
    .out_write_commit   (_csr_out_write_commit),
    .out_value          (out_r),
    .out_candidate      (_csr_out_candidate),
    .in_value           (sync2),
    .set_write_commit   (_csr_set_write_commit),
    .set_candidate      (_csr_set_candidate),
    .clear_write_commit (_csr_clear_write_commit),
    .clear_candidate    (_csr_clear_candidate),
    .rise_bits          (rise_bits)
  );
  assign pad_out = out_r & _csr_dir_value;
  assign pad_oe = _csr_dir_value;
  assign raw_event = (|rise_bits) & ~rst;
endmodule

module BitloomTimerCsr(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  output        ctrl_write_commit,
  input  [31:0] ctrl_value,
  output [31:0] ctrl_candidate,
  output        count_write_commit,
  input  [31:0] count_value,
  output [31:0] count_candidate,
  output        compare_write_commit,
  output [31:0] compare_value,
  input  [31:0] match_bits
);

  reg         _csr_pending;
  reg  [31:0] _csr_data;
  reg  [1:0]  _csr_error;
  reg  [31:0] _csr_value2;
  reg  [31:0] _csr_value3;
  wire        _csr_n9 = ~_csr_pending & ~rst;
  wire        _csr_n10 = req_valid & _csr_n9;
  wire [31:0] _csr_n86 =
    (wstrb[0] ? 32'hFF : 32'h0) | (wstrb[1] ? 32'hFF00 : 32'h0)
    | (wstrb[2] ? 32'hFF0000 : 32'h0) | (wstrb[3] ? 32'hFF000000 : 32'h0);
  wire [31:0] _csr_n32 = {30'h0, ctrl_value[1:0]};
  wire        _csr_n34 = addr == 16'h0;
  wire        _csr_n58 = addr == 16'h4;
  wire        _csr_n82 = addr == 16'h8;
  wire        _csr_n97 = _csr_n10 & _csr_n82 & write & (|_csr_n86);
  wire [31:0] _csr_n105 = {31'h0, _csr_value3[0]};
  wire        _csr_n107 = addr == 16'hC;
  always @(posedge clk) begin
    if (rst) begin
      _csr_pending <= 1'h0;
      _csr_data <= 32'h0;
      _csr_error <= 2'h0;
      _csr_value2 <= 32'h0;
      _csr_value3 <= 32'h0;
    end
    else begin
      _csr_pending <= _csr_n10 | ~rsp_ready & _csr_pending;
      if (_csr_n10) begin
        _csr_data <=
          _csr_n107
            ? (write ? 32'h0 : _csr_n105)
            : _csr_n82
                ? (write ? 32'h0 : _csr_value2)
                : _csr_n58
                    ? (write ? 32'h0 : count_value)
                    : _csr_n34 & ~write ? _csr_n32 : 32'h0;
        _csr_error <= _csr_n107 | _csr_n82 | _csr_n58 ? 2'h0 : {~_csr_n34, 1'h0};
      end
      if (_csr_n97)
        _csr_value2 <= _csr_value2 & ~_csr_n86 | wdata & _csr_n86;
      _csr_value3 <=
        _csr_n105
        & ~(_csr_n10 & _csr_n107 & write & _csr_n86[0]
              ? wdata & {31'h0, _csr_n86[0]}
              : 32'h0) | {31'h0, match_bits[0]};
    end
  end // always @(posedge)
  assign req_ready = _csr_n9;
  assign rsp_valid = _csr_pending;
  assign rdata = _csr_data;
  assign error = _csr_error;
  assign ctrl_write_commit = _csr_n10 & _csr_n34 & write & (|(_csr_n86[1:0]));
  assign ctrl_candidate =
    _csr_n32 & {30'h3FFFFFFF, ~(_csr_n86[1:0])} | wdata & {30'h0, _csr_n86[1:0]};
  assign count_write_commit = _csr_n10 & _csr_n58 & write & (|_csr_n86);
  assign count_candidate = count_value & ~_csr_n86 | wdata & _csr_n86;
  assign compare_write_commit = _csr_n97;
  assign compare_value = _csr_value2;
endmodule

module Fr198Timer(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  output        match_event
);

  wire        _csr_ctrl_write_commit;
  wire [31:0] _csr_ctrl_candidate;
  wire        _csr_count_write_commit;
  wire [31:0] _csr_count_candidate;
  wire        _csr_compare_write_commit;
  wire [31:0] _csr_compare_value;
  reg  [31:0] ctrl_value;
  reg  [31:0] count_value;
  wire        advance =
    ctrl_value[0] & ~rst
    & ~(_csr_ctrl_write_commit | _csr_count_write_commit | _csr_compare_write_commit);
  wire [31:0] increment = count_value + 32'h1;
  wire        _match_event_output = advance & increment == _csr_compare_value;
  always @(posedge clk) begin
    if (rst) begin
      ctrl_value <= 32'h0;
      count_value <= 32'h0;
    end
    else begin
      if (_csr_ctrl_write_commit)
        ctrl_value <= _csr_ctrl_candidate;
      else if (_match_event_output & ~(ctrl_value[1]))
        ctrl_value <= {30'h0, ctrl_value[1], 1'h0};
      if (_csr_count_write_commit)
        count_value <= _csr_count_candidate;
      else if (advance)
        count_value <= _match_event_output & ctrl_value[1] ? 32'h0 : increment;
    end
  end // always @(posedge)
  BitloomTimerCsr csr (
    .clk                  (clk),
    .rst                  (rst),
    .req_valid            (req_valid),
    .write                (write),
    .addr                 (addr),
    .wdata                (wdata),
    .wstrb                (wstrb),
    .rsp_ready            (rsp_ready),
    .req_ready            (req_ready),
    .rsp_valid            (rsp_valid),
    .rdata                (rdata),
    .error                (error),
    .ctrl_write_commit    (_csr_ctrl_write_commit),
    .ctrl_value           (ctrl_value),
    .ctrl_candidate       (_csr_ctrl_candidate),
    .count_write_commit   (_csr_count_write_commit),
    .count_value          (count_value),
    .count_candidate      (_csr_count_candidate),
    .compare_write_commit (_csr_compare_write_commit),
    .compare_value        (_csr_compare_value),
    .match_bits           ({31'h0, _match_event_output})
  );
  assign match_event = _match_event_output;
endmodule

module BitloomIrqCsr(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  output [31:0] pending_value,
  input  [31:0] event_bits,
  output [31:0] enable_value,
  output        test_write_commit,
  output [31:0] test_candidate,
  input  [31:0] raw_value
);

  reg         _csr_pending;
  reg  [31:0] _csr_data;
  reg  [1:0]  _csr_error;
  reg  [31:0] _csr_value0;
  reg  [31:0] _csr_value1;
  wire        _csr_n9 = ~_csr_pending & ~rst;
  wire        _csr_n10 = req_valid & _csr_n9;
  wire [4:0]  _csr_n18 = {5{wstrb[0]}};
  wire [31:0] _csr_n32 = {27'h0, _csr_value0[4:0]};
  wire [31:0] _csr_n58 = {27'h0, _csr_value1[4:0]};
  wire        _csr_n84 = addr == 16'h8;
  wire        _csr_n104 = addr == 16'hC;
  wire        _csr_n34 = addr == 16'h0;
  wire        _csr_n60 = addr == 16'h4;
  always @(posedge clk) begin
    if (rst) begin
      _csr_pending <= 1'h0;
      _csr_data <= 32'h0;
      _csr_error <= 2'h0;
      _csr_value0 <= 32'h0;
      _csr_value1 <= 32'h0;
    end
    else begin
      _csr_pending <= _csr_n10 | ~rsp_ready & _csr_pending;
      if (_csr_n10) begin
        _csr_data <=
          _csr_n104
            ? (write ? 32'h0 : {27'h0, raw_value[4:0]})
            : _csr_n84
                ? 32'h0
                : _csr_n60
                    ? (write ? 32'h0 : _csr_n58)
                    : _csr_n34 & ~write ? _csr_n32 : 32'h0;
        _csr_error <=
          _csr_n104
            ? {write, 1'h0}
            : _csr_n84 ? {~write, 1'h0} : _csr_n60 ? 2'h0 : {~_csr_n34, 1'h0};
      end
      _csr_value0 <=
        _csr_n32
        & ~(_csr_n10 & _csr_n34 & write & wstrb[0] ? wdata & {27'h0, _csr_n18} : 32'h0)
        | {27'h0, event_bits[4:0]};
      _csr_value1 <=
        _csr_n10 & _csr_n60 & write & wstrb[0]
          ? _csr_n58 & {27'h7FFFFFF, ~_csr_n18} | wdata & {27'h0, _csr_n18}
          : _csr_n58;
    end
  end // always @(posedge)
  assign req_ready = _csr_n9;
  assign rsp_valid = _csr_pending;
  assign rdata = _csr_data;
  assign error = _csr_error;
  assign pending_value = _csr_n32;
  assign enable_value = _csr_n58;
  assign test_write_commit = _csr_n10 & _csr_n84 & write & wstrb[0];
  assign test_candidate = wdata & {27'h0, _csr_n18};
endmodule

module Fr198Irq(
  input         clk,
                rst,
                req_valid,
                write,
  input  [15:0] addr,
  input  [31:0] wdata,
  input  [3:0]  wstrb,
  input         rsp_ready,
  output        req_ready,
                rsp_valid,
  output [31:0] rdata,
  output [1:0]  error,
  input  [4:0]  raw_events,
  output        irq
);

  wire [31:0] _csr_pending_value;
  wire [31:0] _csr_enable_value;
  wire        _csr_test_write_commit;
  wire [31:0] _csr_test_candidate;
  wire [31:0] raw_value = {27'h0, raw_events};
  BitloomIrqCsr csr (
    .clk               (clk),
    .rst               (rst),
    .req_valid         (req_valid),
    .write             (write),
    .addr              (addr),
    .wdata             (wdata),
    .wstrb             (wstrb),
    .rsp_ready         (rsp_ready),
    .req_ready         (req_ready),
    .rsp_valid         (rsp_valid),
    .rdata             (rdata),
    .error             (error),
    .pending_value     (_csr_pending_value),
    .event_bits
      (raw_value | (_csr_test_write_commit ? _csr_test_candidate : 32'h0)),
    .enable_value      (_csr_enable_value),
    .test_write_commit (_csr_test_write_commit),
    .test_candidate    (_csr_test_candidate),
    .raw_value         (raw_value)
  );
  assign irq = |(_csr_pending_value & _csr_enable_value);
endmodule

module Fr198AxiCore(
  input         clk,
                rst,
  input  [15:0] axi_s_axi_awaddr,
  input  [2:0]  axi_s_axi_awprot,
  input         axi_s_axi_awvalid,
  input  [31:0] axi_s_axi_wdata,
  input  [3:0]  axi_s_axi_wstrb,
  input         axi_s_axi_wvalid,
                axi_s_axi_bready,
  input  [15:0] axi_s_axi_araddr,
  input  [2:0]  axi_s_axi_arprot,
  input         axi_s_axi_arvalid,
                axi_s_axi_rready,
  output        axi_s_axi_awready,
                axi_s_axi_wready,
                axi_s_axi_arready,
                axi_s_axi_bvalid,
  output [1:0]  axi_s_axi_bresp,
  output        axi_s_axi_rvalid,
  output [31:0] axi_s_axi_rdata,
  output [1:0]  axi_s_axi_rresp,
  input         u_rx,
  output        u_tx,
  input  [31:0] g_pad_in,
  output [31:0] g_pad_out,
                g_pad_oe,
  output        i_irq
);

  wire        _decoder_req_ready;
  wire        _decoder_rsp_valid;
  wire [31:0] _decoder_rdata;
  wire [1:0]  _decoder_error;
  wire        _decoder_uart_req_valid;
  wire        _decoder_uart_write;
  wire [15:0] _decoder_uart_addr;
  wire [31:0] _decoder_uart_wdata;
  wire [3:0]  _decoder_uart_wstrb;
  wire        _decoder_uart_rsp_ready;
  wire        _decoder_gpio_req_valid;
  wire        _decoder_gpio_write;
  wire [15:0] _decoder_gpio_addr;
  wire [31:0] _decoder_gpio_wdata;
  wire [3:0]  _decoder_gpio_wstrb;
  wire        _decoder_gpio_rsp_ready;
  wire        _decoder_timer_req_valid;
  wire        _decoder_timer_write;
  wire [15:0] _decoder_timer_addr;
  wire [31:0] _decoder_timer_wdata;
  wire [3:0]  _decoder_timer_wstrb;
  wire        _decoder_timer_rsp_ready;
  wire        _decoder_irq_req_valid;
  wire        _decoder_irq_write;
  wire [15:0] _decoder_irq_addr;
  wire [31:0] _decoder_irq_wdata;
  wire [3:0]  _decoder_irq_wstrb;
  wire        _decoder_irq_rsp_ready;
  wire        _bridge_csr_req_valid;
  wire        _bridge_csr_write;
  wire [15:0] _bridge_csr_addr;
  wire [31:0] _bridge_csr_wdata;
  wire [3:0]  _bridge_csr_wstrb;
  wire        _bridge_csr_rsp_ready;
  wire        _irq_req_ready;
  wire        _irq_rsp_valid;
  wire [31:0] _irq_rdata;
  wire [1:0]  _irq_error;
  wire        _timer_req_ready;
  wire        _timer_rsp_valid;
  wire [31:0] _timer_rdata;
  wire [1:0]  _timer_error;
  wire        _timer_match_event;
  wire        _gpio_req_ready;
  wire        _gpio_rsp_valid;
  wire [31:0] _gpio_rdata;
  wire [1:0]  _gpio_error;
  wire        _gpio_raw_event;
  wire        _uart_req_ready;
  wire        _uart_rsp_valid;
  wire [31:0] _uart_rdata;
  wire [1:0]  _uart_error;
  wire [3:0]  _uart_raw_events;
  Fr198Uart uart (
    .clk        (clk),
    .rst        (rst),
    .req_valid  (_decoder_uart_req_valid),
    .write      (_decoder_uart_write),
    .addr       (_decoder_uart_addr),
    .wdata      (_decoder_uart_wdata),
    .wstrb      (_decoder_uart_wstrb),
    .rsp_ready  (_decoder_uart_rsp_ready),
    .req_ready  (_uart_req_ready),
    .rsp_valid  (_uart_rsp_valid),
    .rdata      (_uart_rdata),
    .error      (_uart_error),
    .rx         (u_rx),
    .tx         (u_tx),
    .raw_events (_uart_raw_events)
  );
  Fr198Gpio gpio (
    .clk       (clk),
    .rst       (rst),
    .req_valid (_decoder_gpio_req_valid),
    .write     (_decoder_gpio_write),
    .addr      (_decoder_gpio_addr),
    .wdata     (_decoder_gpio_wdata),
    .wstrb     (_decoder_gpio_wstrb),
    .rsp_ready (_decoder_gpio_rsp_ready),
    .req_ready (_gpio_req_ready),
    .rsp_valid (_gpio_rsp_valid),
    .rdata     (_gpio_rdata),
    .error     (_gpio_error),
    .pad_in    (g_pad_in),
    .pad_out   (g_pad_out),
    .pad_oe    (g_pad_oe),
    .raw_event (_gpio_raw_event)
  );
  Fr198Timer timer (
    .clk         (clk),
    .rst         (rst),
    .req_valid   (_decoder_timer_req_valid),
    .write       (_decoder_timer_write),
    .addr        (_decoder_timer_addr),
    .wdata       (_decoder_timer_wdata),
    .wstrb       (_decoder_timer_wstrb),
    .rsp_ready   (_decoder_timer_rsp_ready),
    .req_ready   (_timer_req_ready),
    .rsp_valid   (_timer_rsp_valid),
    .rdata       (_timer_rdata),
    .error       (_timer_error),
    .match_event (_timer_match_event)
  );
  Fr198Irq irq (
    .clk        (clk),
    .rst        (rst),
    .req_valid  (_decoder_irq_req_valid),
    .write      (_decoder_irq_write),
    .addr       (_decoder_irq_addr),
    .wdata      (_decoder_irq_wdata),
    .wstrb      (_decoder_irq_wstrb),
    .rsp_ready  (_decoder_irq_rsp_ready),
    .req_ready  (_irq_req_ready),
    .rsp_valid  (_irq_rsp_valid),
    .rdata      (_irq_rdata),
    .error      (_irq_error),
    .raw_events
      ({_gpio_raw_event,
        _uart_raw_events[2] | _uart_raw_events[3],
        _uart_raw_events[1:0],
        _timer_match_event}),
    .irq        (i_irq)
  );
  Fr198Bridge bridge (
    .clk           (clk),
    .rst           (rst),
    .s_axi_awaddr  (axi_s_axi_awaddr),
    .s_axi_awvalid (axi_s_axi_awvalid),
    .s_axi_wdata   (axi_s_axi_wdata),
    .s_axi_wstrb   (axi_s_axi_wstrb),
    .s_axi_wvalid  (axi_s_axi_wvalid),
    .s_axi_bready  (axi_s_axi_bready),
    .s_axi_araddr  (axi_s_axi_araddr),
    .s_axi_arvalid (axi_s_axi_arvalid),
    .s_axi_rready  (axi_s_axi_rready),
    .csr_req_ready (_decoder_req_ready),
    .csr_rsp_valid (_decoder_rsp_valid),
    .csr_rdata     (_decoder_rdata),
    .csr_error     (_decoder_error),
    .s_axi_awready (axi_s_axi_awready),
    .s_axi_wready  (axi_s_axi_wready),
    .s_axi_arready (axi_s_axi_arready),
    .s_axi_bvalid  (axi_s_axi_bvalid),
    .s_axi_bresp   (axi_s_axi_bresp),
    .s_axi_rvalid  (axi_s_axi_rvalid),
    .s_axi_rdata   (axi_s_axi_rdata),
    .s_axi_rresp   (axi_s_axi_rresp),
    .csr_req_valid (_bridge_csr_req_valid),
    .csr_write     (_bridge_csr_write),
    .csr_addr      (_bridge_csr_addr),
    .csr_wdata     (_bridge_csr_wdata),
    .csr_wstrb     (_bridge_csr_wstrb),
    .csr_rsp_ready (_bridge_csr_rsp_ready)
  );
  Fr198Decoder decoder (
    .clk             (clk),
    .rst             (rst),
    .req_valid       (_bridge_csr_req_valid),
    .write           (_bridge_csr_write),
    .addr            (_bridge_csr_addr),
    .wdata           (_bridge_csr_wdata),
    .wstrb           (_bridge_csr_wstrb),
    .rsp_ready       (_bridge_csr_rsp_ready),
    .req_ready       (_decoder_req_ready),
    .rsp_valid       (_decoder_rsp_valid),
    .rdata           (_decoder_rdata),
    .error           (_decoder_error),
    .uart_req_ready  (_uart_req_ready),
    .uart_rsp_valid  (_uart_rsp_valid),
    .uart_rdata      (_uart_rdata),
    .uart_error      (_uart_error),
    .uart_req_valid  (_decoder_uart_req_valid),
    .uart_write      (_decoder_uart_write),
    .uart_addr       (_decoder_uart_addr),
    .uart_wdata      (_decoder_uart_wdata),
    .uart_wstrb      (_decoder_uart_wstrb),
    .uart_rsp_ready  (_decoder_uart_rsp_ready),
    .gpio_req_ready  (_gpio_req_ready),
    .gpio_rsp_valid  (_gpio_rsp_valid),
    .gpio_rdata      (_gpio_rdata),
    .gpio_error      (_gpio_error),
    .gpio_req_valid  (_decoder_gpio_req_valid),
    .gpio_write      (_decoder_gpio_write),
    .gpio_addr       (_decoder_gpio_addr),
    .gpio_wdata      (_decoder_gpio_wdata),
    .gpio_wstrb      (_decoder_gpio_wstrb),
    .gpio_rsp_ready  (_decoder_gpio_rsp_ready),
    .timer_req_ready (_timer_req_ready),
    .timer_rsp_valid (_timer_rsp_valid),
    .timer_rdata     (_timer_rdata),
    .timer_error     (_timer_error),
    .timer_req_valid (_decoder_timer_req_valid),
    .timer_write     (_decoder_timer_write),
    .timer_addr      (_decoder_timer_addr),
    .timer_wdata     (_decoder_timer_wdata),
    .timer_wstrb     (_decoder_timer_wstrb),
    .timer_rsp_ready (_decoder_timer_rsp_ready),
    .irq_req_ready   (_irq_req_ready),
    .irq_rsp_valid   (_irq_rsp_valid),
    .irq_rdata       (_irq_rdata),
    .irq_error       (_irq_error),
    .irq_req_valid   (_decoder_irq_req_valid),
    .irq_write       (_decoder_irq_write),
    .irq_addr        (_decoder_irq_addr),
    .irq_wdata       (_decoder_irq_wdata),
    .irq_wstrb       (_decoder_irq_wstrb),
    .irq_rsp_ready   (_decoder_irq_rsp_ready)
  );
endmodule

