// generated by rhdl formal export (FR39); FR85 Counter fixture
module Counter_sva (
  input logic [1-1:0] clk,
  input logic [1-1:0] rst,
  input logic [8-1:0] data_out
);
  // assert:out_lt_16
  assert property (@(posedge clk) disable iff (rst)
    data_out == 8'd15);
endmodule
