//! Legacy crate name: product HLS path lives in `bitloom` (`cargo bitloom hls` / `bitloom::hls`).
//! Kept for workspace continuity; mirrors AD-25 / FR35 / FR76 (no in-crate scheduling).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Pinned external HLS backend (AD-25).
pub const HLS_BACKEND: &str = "bambu";

/// Pinned PandA Bambu release (NFR14 / Epic 24).
pub const HLS_BACKEND_VERSION: &str = "2024.10";

#[derive(Debug)]
pub enum HlsError {
    Message(String),
}

impl std::fmt::Display for HlsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            HlsError::Message(m) => write!(f, "{m}"),
        }
    }
}

impl std::error::Error for HlsError {}

/// D1 / FR76 constraint class (mirror of `bitloom::hls`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HlsClosureConstraintClass {
    HlsFree,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HlsDataflowClosureViolationKind {
    CapturingOrStateful,
    WrongPathForSynthesizable,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HlsDataflowClosureViolation {
    pub kind: HlsDataflowClosureViolationKind,
    pub message: String,
}

impl HlsDataflowClosureViolation {
    pub fn capturing(message: impl Into<String>) -> Self {
        Self {
            kind: HlsDataflowClosureViolationKind::CapturingOrStateful,
            message: message.into(),
        }
    }

    pub fn wrong_path_synthesizable(message: impl Into<String>) -> Self {
        Self {
            kind: HlsDataflowClosureViolationKind::WrongPathForSynthesizable,
            message: message.into(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HlsDataflowOp {
    Identity,
    AddConst(u32),
    XorConst(u32),
    MulConst(u32),
    AddInputs,
}

#[derive(Debug, Clone)]
pub struct DissolvedHlsDataflow {
    pub fn_name: String,
    pub constraint_class: HlsClosureConstraintClass,
    pub op: HlsDataflowOp,
    pub c_source: String,
}

pub fn resolve_bambu() -> Result<PathBuf, HlsError> {
    if let Some(p) = std::env::var_os("BITLOOM_BAMBU_PATH").map(PathBuf::from) {
        return Ok(p);
    }
    if let Some(p) = std::env::var_os("RHDL_BAMBU_PATH").map(PathBuf::from) {
        return Ok(p);
    }
    which("bambu").ok_or_else(|| {
        HlsError::Message(format!(
            "pinned HLS backend {HLS_BACKEND} {HLS_BACKEND_VERSION} not found; \
             set BITLOOM_BAMBU_PATH or install bambu-{HLS_BACKEND_VERSION}.AppImage"
        ))
    })
}

pub fn check_hls_dataflow_closure(
    class: HlsClosureConstraintClass,
    violations: &[HlsDataflowClosureViolation],
) -> Result<(), HlsError> {
    match class {
        HlsClosureConstraintClass::HlsFree => {
            if violations.is_empty() {
                Ok(())
            } else {
                let detail = violations
                    .iter()
                    .map(|v| format!("{:?}: {}", v.kind, v.message))
                    .collect::<Vec<_>>()
                    .join("; ");
                Err(HlsError::Message(format!(
                    "HLS dataflow closure rejected (D1 / Cap-R-62, class={class:?}): {detail}"
                )))
            }
        }
    }
}

fn c_source_for_op(fn_name: &str, op: &HlsDataflowOp) -> String {
    let header = format!(
        "/* generated by bitloom for {HLS_BACKEND} {HLS_BACKEND_VERSION}; no scheduling in bitloom */\n\
         /* FR76: dataflow transform expanded before external HLS lower (NFR36 clean) */\n"
    );
    let body = match op {
        HlsDataflowOp::Identity => format!("unsigned {fn_name}(unsigned x) {{\n  return x;\n}}\n"),
        HlsDataflowOp::AddConst(k) => {
            format!("unsigned {fn_name}(unsigned x) {{\n  return x + {k}u;\n}}\n")
        }
        HlsDataflowOp::XorConst(k) => {
            format!("unsigned {fn_name}(unsigned x) {{\n  return x ^ {k}u;\n}}\n")
        }
        HlsDataflowOp::MulConst(k) => {
            format!("unsigned {fn_name}(unsigned x) {{\n  return x * {k}u;\n}}\n")
        }
        HlsDataflowOp::AddInputs => {
            format!("unsigned {fn_name}(unsigned a, unsigned b) {{\n  return a + b;\n}}\n")
        }
    };
    format!("{header}{body}")
}

pub fn dissolve_dataflow_transform<F>(
    fn_name: &str,
    violations: &[HlsDataflowClosureViolation],
    transform: F,
) -> Result<DissolvedHlsDataflow, HlsError>
where
    F: FnOnce() -> HlsDataflowOp,
{
    check_hls_dataflow_closure(HlsClosureConstraintClass::HlsFree, violations)?;
    let op = transform();
    let c_source = c_source_for_op(fn_name, &op);
    if c_source.contains("||") || c_source.to_lowercase().contains("closure") {
        return Err(HlsError::Message(
            "NFR36: dissolved HLS C must not contain closure residue".into(),
        ));
    }
    Ok(DissolvedHlsDataflow {
        fn_name: fn_name.to_string(),
        constraint_class: HlsClosureConstraintClass::HlsFree,
        op,
        c_source,
    })
}

/// Emit a trivial C stub the external tool accepts (no in-crate scheduling).
pub fn emit_c_stub(fn_name: &str, out_dir: &Path) -> Result<PathBuf, HlsError> {
    let dissolved = dissolve_dataflow_transform(fn_name, &[], || HlsDataflowOp::AddInputs)?;
    fs::create_dir_all(out_dir).map_err(|e| HlsError::Message(e.to_string()))?;
    let path = out_dir.join(format!("{fn_name}.c"));
    fs::write(&path, &dissolved.c_source).map_err(|e| HlsError::Message(e.to_string()))?;
    Ok(path)
}

/// Run pinned Bambu; missing backend fails readably (never silent success).
pub fn run_hls(fn_name: &str, out_dir: &Path) -> Result<PathBuf, HlsError> {
    let c = emit_c_stub(fn_name, out_dir)?;
    let bambu = resolve_bambu()?;
    let status = Command::new(&bambu)
        .arg(&c)
        .arg(format!("--top-fname={fn_name}"))
        .current_dir(out_dir)
        .status()
        .map_err(|e| HlsError::Message(format!("spawn bambu: {e}")))?;
    if !status.success() {
        return Err(HlsError::Message("bambu exited non-zero".into()));
    }
    let v = out_dir.join(format!("{fn_name}.v"));
    if v.is_file() {
        return Ok(v);
    }
    Ok(c)
}

fn which(name: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        let cand = dir.join(name);
        if cand.is_file() {
            return Some(cand);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_bambu_is_readable_error() {
        let dir = std::env::temp_dir().join("rhdl_hls_stub_v");
        let p = emit_c_stub("add", &dir).unwrap();
        let text = std::fs::read_to_string(p).unwrap();
        assert!(text.contains("no scheduling in bitloom"));
        assert!(text.contains(HLS_BACKEND_VERSION));
    }

    #[test]
    fn emit_stub_without_scheduling() {
        let dir = std::env::temp_dir().join("rhdl_hls_stub");
        let p = emit_c_stub("add", &dir).unwrap();
        let text = std::fs::read_to_string(p).unwrap();
        assert!(text.contains("no scheduling in bitloom"));
        assert!(!text.contains("schedule"));
    }

    #[test]
    fn dissolve_before_schedule() {
        let d =
            dissolve_dataflow_transform("map_xor", &[], || HlsDataflowOp::XorConst(0xa5)).unwrap();
        assert!(d.c_source.contains("^ 165u"));
        assert!(!d.c_source.contains("Fn"));
    }
}
