//! Legacy crate name: product HLS path lives in `bitloom` CLI (`cargo bitloom hls`).
//! Kept for workspace continuity; mirrors AD-25 / FR35 constants (no in-crate scheduling).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Pinned external HLS backend (AD-25).
pub const HLS_BACKEND: &str = "bambu";

/// Pinned PandA Bambu release (NFR14 / Epic 24).
pub const HLS_BACKEND_VERSION: &str = "2024.10";

#[derive(Debug)]
pub enum HlsError {
    Message(String),
}

impl std::fmt::Display for HlsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            HlsError::Message(m) => write!(f, "{m}"),
        }
    }
}

impl std::error::Error for HlsError {}

pub fn resolve_bambu() -> Result<PathBuf, HlsError> {
    if let Some(p) = std::env::var_os("BITLOOM_BAMBU_PATH").map(PathBuf::from) {
        return Ok(p);
    }
    if let Some(p) = std::env::var_os("RHDL_BAMBU_PATH").map(PathBuf::from) {
        return Ok(p);
    }
    which("bambu").ok_or_else(|| {
        HlsError::Message(format!(
            "pinned HLS backend {HLS_BACKEND} {HLS_BACKEND_VERSION} not found; \
             set BITLOOM_BAMBU_PATH or install bambu-{HLS_BACKEND_VERSION}.AppImage"
        ))
    })
}

/// Emit a trivial C stub the external tool accepts (no in-crate scheduling).
pub fn emit_c_stub(fn_name: &str, out_dir: &Path) -> Result<PathBuf, HlsError> {
    fs::create_dir_all(out_dir).map_err(|e| HlsError::Message(e.to_string()))?;
    let path = out_dir.join(format!("{fn_name}.c"));
    let body = format!(
        "/* generated by bitloom for {HLS_BACKEND} {HLS_BACKEND_VERSION}; no scheduling in bitloom */\n\
         unsigned {fn_name}(unsigned a, unsigned b) {{\n\
           return a + b;\n\
         }}\n"
    );
    fs::write(&path, body).map_err(|e| HlsError::Message(e.to_string()))?;
    Ok(path)
}

/// Run pinned Bambu; missing backend fails readably (never silent success).
pub fn run_hls(fn_name: &str, out_dir: &Path) -> Result<PathBuf, HlsError> {
    let c = emit_c_stub(fn_name, out_dir)?;
    let bambu = resolve_bambu()?;
    let status = Command::new(&bambu)
        .arg(&c)
        .arg(format!("--top-fname={fn_name}"))
        .current_dir(out_dir)
        .status()
        .map_err(|e| HlsError::Message(format!("spawn bambu: {e}")))?;
    if !status.success() {
        return Err(HlsError::Message("bambu exited non-zero".into()));
    }
    let v = out_dir.join(format!("{fn_name}.v"));
    if v.is_file() {
        return Ok(v);
    }
    Ok(c)
}

fn which(name: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        let cand = dir.join(name);
        if cand.is_file() {
            return Some(cand);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_bambu_is_readable_error() {
        // Prefer unit coverage via emit; integration tests clear PATH.
        let dir = std::env::temp_dir().join("rhdl_hls_stub_v");
        let p = emit_c_stub("add", &dir).unwrap();
        let text = std::fs::read_to_string(p).unwrap();
        assert!(text.contains("no scheduling in bitloom"));
        assert!(text.contains(HLS_BACKEND_VERSION));
    }

    #[test]
    fn emit_stub_without_scheduling() {
        let dir = std::env::temp_dir().join("rhdl_hls_stub");
        let p = emit_c_stub("add", &dir).unwrap();
        let text = std::fs::read_to_string(p).unwrap();
        assert!(text.contains("no scheduling in bitloom"));
        assert!(!text.contains("schedule"));
    }
}
