// Generated by CIRCT firtool-1.159.0
module Fr198AxiCore(	// src/main/scala/Design.scala:2656:7
  input         clock,	// src/main/scala/Design.scala:2656:7
                reset,	// src/main/scala/Design.scala:2656:7
  input  [15:0] io_axi_s_axi_awaddr,	// src/main/scala/Design.scala:2657:14
  input  [2:0]  io_axi_s_axi_awprot,	// src/main/scala/Design.scala:2657:14
  input         io_axi_s_axi_awvalid,	// src/main/scala/Design.scala:2657:14
  input  [31:0] io_axi_s_axi_wdata,	// src/main/scala/Design.scala:2657:14
  input  [3:0]  io_axi_s_axi_wstrb,	// src/main/scala/Design.scala:2657:14
  input         io_axi_s_axi_wvalid,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_bready,	// src/main/scala/Design.scala:2657:14
  input  [15:0] io_axi_s_axi_araddr,	// src/main/scala/Design.scala:2657:14
  input  [2:0]  io_axi_s_axi_arprot,	// src/main/scala/Design.scala:2657:14
  input         io_axi_s_axi_arvalid,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_rready,	// src/main/scala/Design.scala:2657:14
  output        io_axi_s_axi_awready,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_wready,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_arready,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_bvalid,	// src/main/scala/Design.scala:2657:14
  output [1:0]  io_axi_s_axi_bresp,	// src/main/scala/Design.scala:2657:14
  output        io_axi_s_axi_rvalid,	// src/main/scala/Design.scala:2657:14
  output [31:0] io_axi_s_axi_rdata,	// src/main/scala/Design.scala:2657:14
  output [1:0]  io_axi_s_axi_rresp,	// src/main/scala/Design.scala:2657:14
  input         io_u_rx,	// src/main/scala/Design.scala:2657:14
  output        io_u_tx,	// src/main/scala/Design.scala:2657:14
  input  [31:0] io_g_pad_in,	// src/main/scala/Design.scala:2657:14
  output [31:0] io_g_pad_out,	// src/main/scala/Design.scala:2657:14
                io_g_pad_oe,	// src/main/scala/Design.scala:2657:14
  output        io_i_irq	// src/main/scala/Design.scala:2657:14
);

  wire        _decoder_io_req_ready;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_rsp_valid;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_rdata;	// src/main/scala/Design.scala:2881:23
  wire [1:0]  _decoder_io_error;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_uart_req_valid;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_uart_write;	// src/main/scala/Design.scala:2881:23
  wire [15:0] _decoder_io_uart_addr;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_uart_wdata;	// src/main/scala/Design.scala:2881:23
  wire [3:0]  _decoder_io_uart_wstrb;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_uart_rsp_ready;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_gpio_req_valid;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_gpio_write;	// src/main/scala/Design.scala:2881:23
  wire [15:0] _decoder_io_gpio_addr;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_gpio_wdata;	// src/main/scala/Design.scala:2881:23
  wire [3:0]  _decoder_io_gpio_wstrb;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_gpio_rsp_ready;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_timer_req_valid;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_timer_write;	// src/main/scala/Design.scala:2881:23
  wire [15:0] _decoder_io_timer_addr;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_timer_wdata;	// src/main/scala/Design.scala:2881:23
  wire [3:0]  _decoder_io_timer_wstrb;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_timer_rsp_ready;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_irq_req_valid;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_irq_write;	// src/main/scala/Design.scala:2881:23
  wire [15:0] _decoder_io_irq_addr;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_irq_wdata;	// src/main/scala/Design.scala:2881:23
  wire [3:0]  _decoder_io_irq_wstrb;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_irq_rsp_ready;	// src/main/scala/Design.scala:2881:23
  wire        _bridge_io_csr_req_valid;	// src/main/scala/Design.scala:2851:22
  wire        _bridge_io_csr_write;	// src/main/scala/Design.scala:2851:22
  wire [15:0] _bridge_io_csr_addr;	// src/main/scala/Design.scala:2851:22
  wire [31:0] _bridge_io_csr_wdata;	// src/main/scala/Design.scala:2851:22
  wire [3:0]  _bridge_io_csr_wstrb;	// src/main/scala/Design.scala:2851:22
  wire        _bridge_io_csr_rsp_ready;	// src/main/scala/Design.scala:2851:22
  wire        _irq_io_req_ready;	// src/main/scala/Design.scala:2838:19
  wire        _irq_io_rsp_valid;	// src/main/scala/Design.scala:2838:19
  wire [31:0] _irq_io_rdata;	// src/main/scala/Design.scala:2838:19
  wire [1:0]  _irq_io_error;	// src/main/scala/Design.scala:2838:19
  wire        _timer_io_req_ready;	// src/main/scala/Design.scala:2826:21
  wire        _timer_io_rsp_valid;	// src/main/scala/Design.scala:2826:21
  wire [31:0] _timer_io_rdata;	// src/main/scala/Design.scala:2826:21
  wire [1:0]  _timer_io_error;	// src/main/scala/Design.scala:2826:21
  wire        _timer_io_match_event;	// src/main/scala/Design.scala:2826:21
  wire        _gpio_io_req_ready;	// src/main/scala/Design.scala:2811:20
  wire        _gpio_io_rsp_valid;	// src/main/scala/Design.scala:2811:20
  wire [31:0] _gpio_io_rdata;	// src/main/scala/Design.scala:2811:20
  wire [1:0]  _gpio_io_error;	// src/main/scala/Design.scala:2811:20
  wire        _gpio_io_raw_event;	// src/main/scala/Design.scala:2811:20
  wire        _uart_io_req_ready;	// src/main/scala/Design.scala:2797:20
  wire        _uart_io_rsp_valid;	// src/main/scala/Design.scala:2797:20
  wire [31:0] _uart_io_rdata;	// src/main/scala/Design.scala:2797:20
  wire [1:0]  _uart_io_error;	// src/main/scala/Design.scala:2797:20
  wire [3:0]  _uart_io_raw_events;	// src/main/scala/Design.scala:2797:20
  Fr198Uart uart (	// src/main/scala/Design.scala:2797:20
    .clock         (clock),
    .reset         (reset),
    .io_req_valid  (_decoder_io_uart_req_valid),	// src/main/scala/Design.scala:2881:23
    .io_write      (_decoder_io_uart_write),	// src/main/scala/Design.scala:2881:23
    .io_addr       (_decoder_io_uart_addr),	// src/main/scala/Design.scala:2881:23
    .io_wdata      (_decoder_io_uart_wdata),	// src/main/scala/Design.scala:2881:23
    .io_wstrb      (_decoder_io_uart_wstrb),	// src/main/scala/Design.scala:2881:23
    .io_rsp_ready  (_decoder_io_uart_rsp_ready),	// src/main/scala/Design.scala:2881:23
    .io_req_ready  (_uart_io_req_ready),
    .io_rsp_valid  (_uart_io_rsp_valid),
    .io_rdata      (_uart_io_rdata),
    .io_error      (_uart_io_error),
    .io_rx         (io_u_rx),
    .io_tx         (io_u_tx),
    .io_raw_events (_uart_io_raw_events)
  );	// src/main/scala/Design.scala:2797:20
  Fr198Gpio gpio (	// src/main/scala/Design.scala:2811:20
    .clock        (clock),
    .reset        (reset),
    .io_req_valid (_decoder_io_gpio_req_valid),	// src/main/scala/Design.scala:2881:23
    .io_write     (_decoder_io_gpio_write),	// src/main/scala/Design.scala:2881:23
    .io_addr      (_decoder_io_gpio_addr),	// src/main/scala/Design.scala:2881:23
    .io_wdata     (_decoder_io_gpio_wdata),	// src/main/scala/Design.scala:2881:23
    .io_wstrb     (_decoder_io_gpio_wstrb),	// src/main/scala/Design.scala:2881:23
    .io_rsp_ready (_decoder_io_gpio_rsp_ready),	// src/main/scala/Design.scala:2881:23
    .io_req_ready (_gpio_io_req_ready),
    .io_rsp_valid (_gpio_io_rsp_valid),
    .io_rdata     (_gpio_io_rdata),
    .io_error     (_gpio_io_error),
    .io_pad_in    (io_g_pad_in),
    .io_pad_out   (io_g_pad_out),
    .io_pad_oe    (io_g_pad_oe),
    .io_raw_event (_gpio_io_raw_event)
  );	// src/main/scala/Design.scala:2811:20
  Fr198Timer timer (	// src/main/scala/Design.scala:2826:21
    .clock          (clock),
    .reset          (reset),
    .io_req_valid   (_decoder_io_timer_req_valid),	// src/main/scala/Design.scala:2881:23
    .io_write       (_decoder_io_timer_write),	// src/main/scala/Design.scala:2881:23
    .io_addr        (_decoder_io_timer_addr),	// src/main/scala/Design.scala:2881:23
    .io_wdata       (_decoder_io_timer_wdata),	// src/main/scala/Design.scala:2881:23
    .io_wstrb       (_decoder_io_timer_wstrb),	// src/main/scala/Design.scala:2881:23
    .io_rsp_ready   (_decoder_io_timer_rsp_ready),	// src/main/scala/Design.scala:2881:23
    .io_req_ready   (_timer_io_req_ready),
    .io_rsp_valid   (_timer_io_rsp_valid),
    .io_rdata       (_timer_io_rdata),
    .io_error       (_timer_io_error),
    .io_match_event (_timer_io_match_event)
  );	// src/main/scala/Design.scala:2826:21
  Fr198Irq irq (	// src/main/scala/Design.scala:2838:19
    .clock         (clock),
    .reset         (reset),
    .io_req_valid  (_decoder_io_irq_req_valid),	// src/main/scala/Design.scala:2881:23
    .io_write      (_decoder_io_irq_write),	// src/main/scala/Design.scala:2881:23
    .io_addr       (_decoder_io_irq_addr),	// src/main/scala/Design.scala:2881:23
    .io_wdata      (_decoder_io_irq_wdata),	// src/main/scala/Design.scala:2881:23
    .io_wstrb      (_decoder_io_irq_wstrb),	// src/main/scala/Design.scala:2881:23
    .io_rsp_ready  (_decoder_io_irq_rsp_ready),	// src/main/scala/Design.scala:2881:23
    .io_req_ready  (_irq_io_req_ready),
    .io_rsp_valid  (_irq_io_rsp_valid),
    .io_rdata      (_irq_io_rdata),
    .io_error      (_irq_io_error),
    .io_raw_events
      ({_gpio_io_raw_event,
        _uart_io_raw_events[2] | _uart_io_raw_events[3],
        _uart_io_raw_events[1:0],
        _timer_io_match_event}),	// src/main/scala/Design.scala:2797:20, :2811:20, :2826:21, :2984:30, :2985:34, :2986:35, :2990:33
    .io_irq        (io_i_irq)
  );	// src/main/scala/Design.scala:2838:19
  Fr198Bridge bridge (	// src/main/scala/Design.scala:2851:22
    .clock            (clock),
    .reset            (reset),
    .io_s_axi_awaddr  (io_axi_s_axi_awaddr),
    .io_s_axi_awvalid (io_axi_s_axi_awvalid),
    .io_s_axi_wdata   (io_axi_s_axi_wdata),
    .io_s_axi_wstrb   (io_axi_s_axi_wstrb),
    .io_s_axi_wvalid  (io_axi_s_axi_wvalid),
    .io_s_axi_bready  (io_axi_s_axi_bready),
    .io_s_axi_araddr  (io_axi_s_axi_araddr),
    .io_s_axi_arvalid (io_axi_s_axi_arvalid),
    .io_s_axi_rready  (io_axi_s_axi_rready),
    .io_csr_req_ready (_decoder_io_req_ready),	// src/main/scala/Design.scala:2881:23
    .io_csr_rsp_valid (_decoder_io_rsp_valid),	// src/main/scala/Design.scala:2881:23
    .io_csr_rdata     (_decoder_io_rdata),	// src/main/scala/Design.scala:2881:23
    .io_csr_error     (_decoder_io_error),	// src/main/scala/Design.scala:2881:23
    .io_s_axi_awready (io_axi_s_axi_awready),
    .io_s_axi_wready  (io_axi_s_axi_wready),
    .io_s_axi_arready (io_axi_s_axi_arready),
    .io_s_axi_bvalid  (io_axi_s_axi_bvalid),
    .io_s_axi_bresp   (io_axi_s_axi_bresp),
    .io_s_axi_rvalid  (io_axi_s_axi_rvalid),
    .io_s_axi_rdata   (io_axi_s_axi_rdata),
    .io_s_axi_rresp   (io_axi_s_axi_rresp),
    .io_csr_req_valid (_bridge_io_csr_req_valid),
    .io_csr_write     (_bridge_io_csr_write),
    .io_csr_addr      (_bridge_io_csr_addr),
    .io_csr_wdata     (_bridge_io_csr_wdata),
    .io_csr_wstrb     (_bridge_io_csr_wstrb),
    .io_csr_rsp_ready (_bridge_io_csr_rsp_ready)
  );	// src/main/scala/Design.scala:2851:22
  Fr198Decoder decoder (	// src/main/scala/Design.scala:2881:23
    .clock              (clock),
    .reset              (reset),
    .io_req_valid       (_bridge_io_csr_req_valid),	// src/main/scala/Design.scala:2851:22
    .io_write           (_bridge_io_csr_write),	// src/main/scala/Design.scala:2851:22
    .io_addr            (_bridge_io_csr_addr),	// src/main/scala/Design.scala:2851:22
    .io_wdata           (_bridge_io_csr_wdata),	// src/main/scala/Design.scala:2851:22
    .io_wstrb           (_bridge_io_csr_wstrb),	// src/main/scala/Design.scala:2851:22
    .io_rsp_ready       (_bridge_io_csr_rsp_ready),	// src/main/scala/Design.scala:2851:22
    .io_req_ready       (_decoder_io_req_ready),
    .io_rsp_valid       (_decoder_io_rsp_valid),
    .io_rdata           (_decoder_io_rdata),
    .io_error           (_decoder_io_error),
    .io_uart_req_ready  (_uart_io_req_ready),	// src/main/scala/Design.scala:2797:20
    .io_uart_rsp_valid  (_uart_io_rsp_valid),	// src/main/scala/Design.scala:2797:20
    .io_uart_rdata      (_uart_io_rdata),	// src/main/scala/Design.scala:2797:20
    .io_uart_error      (_uart_io_error),	// src/main/scala/Design.scala:2797:20
    .io_uart_req_valid  (_decoder_io_uart_req_valid),
    .io_uart_write      (_decoder_io_uart_write),
    .io_uart_addr       (_decoder_io_uart_addr),
    .io_uart_wdata      (_decoder_io_uart_wdata),
    .io_uart_wstrb      (_decoder_io_uart_wstrb),
    .io_uart_rsp_ready  (_decoder_io_uart_rsp_ready),
    .io_gpio_req_ready  (_gpio_io_req_ready),	// src/main/scala/Design.scala:2811:20
    .io_gpio_rsp_valid  (_gpio_io_rsp_valid),	// src/main/scala/Design.scala:2811:20
    .io_gpio_rdata      (_gpio_io_rdata),	// src/main/scala/Design.scala:2811:20
    .io_gpio_error      (_gpio_io_error),	// src/main/scala/Design.scala:2811:20
    .io_gpio_req_valid  (_decoder_io_gpio_req_valid),
    .io_gpio_write      (_decoder_io_gpio_write),
    .io_gpio_addr       (_decoder_io_gpio_addr),
    .io_gpio_wdata      (_decoder_io_gpio_wdata),
    .io_gpio_wstrb      (_decoder_io_gpio_wstrb),
    .io_gpio_rsp_ready  (_decoder_io_gpio_rsp_ready),
    .io_timer_req_ready (_timer_io_req_ready),	// src/main/scala/Design.scala:2826:21
    .io_timer_rsp_valid (_timer_io_rsp_valid),	// src/main/scala/Design.scala:2826:21
    .io_timer_rdata     (_timer_io_rdata),	// src/main/scala/Design.scala:2826:21
    .io_timer_error     (_timer_io_error),	// src/main/scala/Design.scala:2826:21
    .io_timer_req_valid (_decoder_io_timer_req_valid),
    .io_timer_write     (_decoder_io_timer_write),
    .io_timer_addr      (_decoder_io_timer_addr),
    .io_timer_wdata     (_decoder_io_timer_wdata),
    .io_timer_wstrb     (_decoder_io_timer_wstrb),
    .io_timer_rsp_ready (_decoder_io_timer_rsp_ready),
    .io_irq_req_ready   (_irq_io_req_ready),	// src/main/scala/Design.scala:2838:19
    .io_irq_rsp_valid   (_irq_io_rsp_valid),	// src/main/scala/Design.scala:2838:19
    .io_irq_rdata       (_irq_io_rdata),	// src/main/scala/Design.scala:2838:19
    .io_irq_error       (_irq_io_error),	// src/main/scala/Design.scala:2838:19
    .io_irq_req_valid   (_decoder_io_irq_req_valid),
    .io_irq_write       (_decoder_io_irq_write),
    .io_irq_addr        (_decoder_io_irq_addr),
    .io_irq_wdata       (_decoder_io_irq_wdata),
    .io_irq_wstrb       (_decoder_io_irq_wstrb),
    .io_irq_rsp_ready   (_decoder_io_irq_rsp_ready)
  );	// src/main/scala/Design.scala:2881:23
endmodule

