// Generated by CIRCT firtool-1.159.0
module BitloomUartCsrFifo8x4(	// src/main/scala/Design.scala:816:7
  input        clock,	// src/main/scala/Design.scala:816:7
               reset,	// src/main/scala/Design.scala:816:7
               io_input_valid,	// src/main/scala/Design.scala:817:14
               io_output_ready,	// src/main/scala/Design.scala:817:14
  input  [7:0] io_input_data,	// src/main/scala/Design.scala:817:14
  output       io_input_ready,	// src/main/scala/Design.scala:817:14
               io_output_valid,	// src/main/scala/Design.scala:817:14
  output [7:0] io_output_data	// src/main/scala/Design.scala:817:14
);

  reg  [2:0] count;	// src/main/scala/Design.scala:826:22
  reg  [7:0] slot_0;	// src/main/scala/Design.scala:840:23
  reg  [7:0] slot_1;	// src/main/scala/Design.scala:846:23
  reg  [7:0] slot_2;	// src/main/scala/Design.scala:852:23
  reg  [7:0] slot_3;	// src/main/scala/Design.scala:858:23
  wire       io_output_valid_0 = |count;	// src/main/scala/Design.scala:826:22, :868:18
  wire       io_input_ready_0 = count != 3'h4;	// src/main/scala/Design.scala:826:22, :866:12, :869:17
  wire       push = io_input_valid & io_input_ready_0;	// src/main/scala/Design.scala:869:17, :873:26
  wire       pop = io_output_valid_0 & io_output_ready;	// src/main/scala/Design.scala:868:18, :874:26
  wire [2:0] _decremented_T = count - 3'h1;	// src/main/scala/Design.scala:826:22, :875:24
  wire [2:0] after_pop = pop ? _decremented_T : count;	// src/main/scala/Design.scala:826:22, :874:26, :875:24, :876:19
  always @(posedge clock) begin	// src/main/scala/Design.scala:816:7
    if (reset) begin	// src/main/scala/Design.scala:816:7
      count <= 3'h0;	// src/main/scala/Design.scala:826:22
      slot_0 <= 8'h0;	// src/main/scala/Design.scala:840:23
      slot_1 <= 8'h0;	// src/main/scala/Design.scala:840:23, :846:23
      slot_2 <= 8'h0;	// src/main/scala/Design.scala:840:23, :852:23
      slot_3 <= 8'h0;	// src/main/scala/Design.scala:840:23, :858:23
    end
    else begin	// src/main/scala/Design.scala:816:7
      if (push)	// src/main/scala/Design.scala:873:26
        count <= after_pop + 3'h1;	// src/main/scala/Design.scala:826:22, :876:19, :877:28
      else if (pop)	// src/main/scala/Design.scala:874:26
        count <= _decremented_T;	// src/main/scala/Design.scala:826:22, :875:24
      if (push & after_pop == 3'h0)	// src/main/scala/Design.scala:873:26, :876:19, :881:21, :882:19
        slot_0 <= io_input_data;	// src/main/scala/Design.scala:840:23
      else if (pop)	// src/main/scala/Design.scala:874:26
        slot_0 <= slot_1;	// src/main/scala/Design.scala:840:23, :846:23
      if (push & after_pop == 3'h1)	// src/main/scala/Design.scala:873:26, :876:19, :886:21, :887:19
        slot_1 <= io_input_data;	// src/main/scala/Design.scala:846:23
      else if (pop)	// src/main/scala/Design.scala:874:26
        slot_1 <= slot_2;	// src/main/scala/Design.scala:846:23, :852:23
      if (push & after_pop == 3'h2)	// src/main/scala/Design.scala:873:26, :876:19, :890:11, :891:21, :892:19
        slot_2 <= io_input_data;	// src/main/scala/Design.scala:852:23
      else if (pop)	// src/main/scala/Design.scala:874:26
        slot_2 <= slot_3;	// src/main/scala/Design.scala:852:23, :858:23
      if (push & after_pop == 3'h3)	// src/main/scala/Design.scala:873:26, :876:19, :895:11, :896:21, :897:19
        slot_3 <= io_input_data;	// src/main/scala/Design.scala:858:23
    end
  end // always @(posedge)
  assign io_input_ready = io_input_ready_0;	// src/main/scala/Design.scala:816:7, :869:17
  assign io_output_valid = io_output_valid_0;	// src/main/scala/Design.scala:816:7, :868:18
  assign io_output_data = slot_0;	// src/main/scala/Design.scala:816:7, :840:23
endmodule

