// Generated by CIRCT firtool-1.159.0
module BitloomUartCsrRegisters(	// src/main/scala/Design.scala:406:7
  input         clock,	// src/main/scala/Design.scala:406:7
                reset,	// src/main/scala/Design.scala:406:7
                io_req_valid,	// src/main/scala/Design.scala:407:14
                io_write,	// src/main/scala/Design.scala:407:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:407:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:407:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:407:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:407:14
  output        io_req_ready,	// src/main/scala/Design.scala:407:14
                io_rsp_valid,	// src/main/scala/Design.scala:407:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:407:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:407:14
  output        io_ctrl_write_commit,	// src/main/scala/Design.scala:407:14
  output [31:0] io_ctrl_value,	// src/main/scala/Design.scala:407:14
                io_ctrl_candidate,	// src/main/scala/Design.scala:407:14
  input         io_ctrl_write_reject,	// src/main/scala/Design.scala:407:14
  output        io_baud_div_write_commit,	// src/main/scala/Design.scala:407:14
  output [31:0] io_baud_div_value,	// src/main/scala/Design.scala:407:14
                io_baud_div_candidate,	// src/main/scala/Design.scala:407:14
  input         io_baud_div_write_reject,	// src/main/scala/Design.scala:407:14
  input  [31:0] io_status_value,	// src/main/scala/Design.scala:407:14
  output        io_tx_data_write_commit,	// src/main/scala/Design.scala:407:14
  output [31:0] io_tx_data_candidate,	// src/main/scala/Design.scala:407:14
  input         io_tx_data_write_reject,	// src/main/scala/Design.scala:407:14
  output        io_rx_data_read_commit,	// src/main/scala/Design.scala:407:14
  input  [31:0] io_rx_data_value,	// src/main/scala/Design.scala:407:14
  input         io_rx_data_read_reject,	// src/main/scala/Design.scala:407:14
  input  [31:0] io_event_bits	// src/main/scala/Design.scala:407:14
);

  reg         _csr_pending;	// src/main/scala/Design.scala:449:29
  reg  [31:0] _csr_data;	// src/main/scala/Design.scala:450:26
  reg  [1:0]  _csr_error;	// src/main/scala/Design.scala:451:27
  reg  [31:0] _csr_value0;	// src/main/scala/Design.scala:452:28
  reg  [31:0] _csr_value1;	// src/main/scala/Design.scala:453:28
  reg  [31:0] _csr_value5;	// src/main/scala/Design.scala:454:28
  wire        io_req_ready_0 = ~_csr_pending & ~reset;	// src/main/scala/Design.scala:449:29, :624:27, :626:34, :627:22
  wire        _csr_n162_T = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:627:22, :629:28
  wire [31:0] _csr_n66 =
    (io_wstrb[0] ? 32'hFF : 32'h0) | (io_wstrb[1] ? 32'hFF00 : 32'h0)
    | (io_wstrb[2] ? 32'hFF0000 : 32'h0) | (io_wstrb[3] ? 32'hFF000000 : 32'h0);	// src/main/scala/Design.scala:637:23, :638:12, :639:18, :641:23, :642:12, :643:18, :644:24, :645:23, :646:12, :647:18, :648:24, :649:23, :650:12, :651:18, :652:24
  wire [31:0] io_ctrl_value_0 = {31'h0, _csr_value0[0]};	// src/main/scala/Design.scala:452:28, :654:27
  wire        _csr_n57_T = io_addr == 16'h0;	// src/main/scala/Design.scala:657:23
  wire [31:0] io_ctrl_candidate_0 =
    io_ctrl_value_0 & {31'h7FFFFFFF, ~(_csr_n66[0])} | io_wdata & {31'h0, _csr_n66[0]};	// src/main/scala/Design.scala:644:24, :648:24, :652:24, :654:27, :662:24, :666:24, :668:24, :669:24, :670:24
  wire        _csr_n50 = io_write & (~(_csr_n66[0]) | ~io_ctrl_write_reject);	// src/main/scala/Design.scala:644:24, :648:24, :652:24, :662:24, :663:24, :674:36, :675:24, :676:24
  wire        io_ctrl_write_commit_0 = _csr_n162_T & _csr_n57_T & _csr_n50 & _csr_n66[0];	// src/main/scala/Design.scala:629:28, :644:24, :648:24, :652:24, :657:23, :658:24, :662:24, :676:24, :677:24, :678:24
  wire        _csr_n85_T = io_addr == 16'h4;	// src/main/scala/Design.scala:689:12, :690:23
  wire        _csr_n69 = |_csr_n66;	// src/main/scala/Design.scala:644:24, :648:24, :652:24, :696:24
  wire [31:0] io_baud_div_candidate_0 = _csr_value1 & ~_csr_n66 | io_wdata & _csr_n66;	// src/main/scala/Design.scala:453:28, :644:24, :648:24, :652:24, :699:24, :701:24, :702:24, :703:24
  wire        _csr_n78 = io_write & (~_csr_n69 | ~io_baud_div_write_reject);	// src/main/scala/Design.scala:696:24, :707:40, :708:24, :709:24
  wire        io_baud_div_write_commit_0 = _csr_n162_T & _csr_n85_T & _csr_n78 & _csr_n69;	// src/main/scala/Design.scala:629:28, :690:23, :691:24, :696:24, :709:24, :710:24, :711:24
  wire        _csr_n120_T = io_addr == 16'hC;	// src/main/scala/Design.scala:734:13, :735:24
  wire        _csr_n108 = |(_csr_n66[7:0]);	// src/main/scala/Design.scala:644:24, :648:24, :652:24, :740:25, :741:26
  wire        _csr_n117_T = io_write & (~_csr_n108 | ~io_tx_data_write_reject);	// src/main/scala/Design.scala:741:26, :748:40, :749:26, :750:25
  wire        _csr_n134_T = io_addr == 16'h10;	// src/main/scala/Design.scala:761:13, :762:24
  wire        _csr_n131_T = ~io_write & ~io_rx_data_read_reject;	// src/main/scala/Design.scala:631:24, :765:39, :766:25
  wire        _csr_n98_T = io_addr == 16'h8;	// src/main/scala/Design.scala:721:12, :722:23
  wire [31:0] _csr_n136 = {28'h0, _csr_value5[3:0]};	// src/main/scala/Design.scala:454:28, :776:28
  wire        _csr_n154_T = io_addr == 16'h14;	// src/main/scala/Design.scala:778:13, :779:24
  always @(posedge clock) begin	// src/main/scala/Design.scala:406:7
    if (reset) begin	// src/main/scala/Design.scala:406:7
      _csr_pending <= 1'h0;	// src/main/scala/Design.scala:449:29
      _csr_data <= 32'h0;	// src/main/scala/Design.scala:450:26
      _csr_error <= 2'h0;	// src/main/scala/Design.scala:451:27
      _csr_value0 <= 32'h0;	// src/main/scala/Design.scala:452:28
      _csr_value1 <= 32'h0;	// src/main/scala/Design.scala:453:28
      _csr_value5 <= 32'h0;	// src/main/scala/Design.scala:454:28
    end
    else begin	// src/main/scala/Design.scala:406:7
      _csr_pending <= _csr_n162_T | ~io_rsp_ready & _csr_pending;	// src/main/scala/Design.scala:449:29, :629:28, :632:18, :633:18
      if (_csr_n162_T) begin	// src/main/scala/Design.scala:629:28
        _csr_data <=
          _csr_n154_T
            ? (io_write ? 32'h0 : _csr_n136)
            : _csr_n134_T
                ? (_csr_n131_T ? {24'h0, io_rx_data_value[7:0]} : 32'h0)
                : _csr_n120_T
                    ? 32'h0
                    : _csr_n98_T
                        ? (io_write ? 32'h0 : {28'h0, io_status_value[3:0]})
                        : _csr_n85_T
                            ? (io_write ? 32'h0 : _csr_value1)
                            : _csr_n57_T & ~io_write ? io_ctrl_value_0 : 32'h0;	// src/main/scala/Design.scala:450:26, :453:28, :631:24, :654:27, :657:23, :683:18, :684:18, :690:23, :716:18, :717:18, :720:31, :722:23, :731:18, :732:18, :735:24, :758:19, :760:33, :762:24, :766:25, :773:19, :774:19, :776:28, :779:24, :798:19, :799:19
        _csr_error <=
          _csr_n154_T
            ? 2'h0
            : {_csr_n134_T
                 ? ~_csr_n131_T
                 : _csr_n120_T
                     ? ~_csr_n117_T
                     : _csr_n98_T
                         ? io_write
                         : _csr_n85_T
                             ? ~(~io_write | _csr_n78)
                             : ~(_csr_n57_T & (~io_write | _csr_n50)),
               1'h0};	// src/main/scala/Design.scala:451:27, :631:24, :657:23, :676:24, :680:24, :681:18, :682:18, :690:23, :709:24, :713:24, :714:18, :715:18, :722:23, :730:18, :735:24, :750:25, :755:19, :756:19, :762:24, :766:25, :771:19, :772:19, :779:24, :797:19
      end
      _csr_value0 <= io_ctrl_write_commit_0 ? io_ctrl_candidate_0 : io_ctrl_value_0;	// src/main/scala/Design.scala:452:28, :654:27, :658:24, :670:24, :677:24, :678:24, :685:18
      if (io_baud_div_write_commit_0)	// src/main/scala/Design.scala:691:24, :710:24, :711:24
        _csr_value1 <= io_baud_div_candidate_0;	// src/main/scala/Design.scala:453:28, :703:24
      _csr_value5 <=
        _csr_n136
        & ~(_csr_n162_T & _csr_n154_T & io_write & (|(_csr_n66[3:0]))
              ? io_wdata & {28'h0, _csr_n66[3:0]}
              : 32'h0) | {28'h0, io_event_bits[3:0]};	// src/main/scala/Design.scala:454:28, :629:28, :644:24, :648:24, :652:24, :776:28, :779:24, :780:25, :784:25, :785:26, :788:25, :792:26, :793:26, :800:19, :802:26, :803:26, :804:30, :805:26
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:406:7, :627:22
  assign io_rsp_valid = _csr_pending;	// src/main/scala/Design.scala:406:7, :449:29
  assign io_rdata = _csr_data;	// src/main/scala/Design.scala:406:7, :450:26
  assign io_error = _csr_error;	// src/main/scala/Design.scala:406:7, :451:27
  assign io_ctrl_write_commit = io_ctrl_write_commit_0;	// src/main/scala/Design.scala:406:7, :658:24, :677:24, :678:24
  assign io_ctrl_value = io_ctrl_value_0;	// src/main/scala/Design.scala:406:7, :654:27
  assign io_ctrl_candidate = io_ctrl_candidate_0;	// src/main/scala/Design.scala:406:7, :670:24
  assign io_baud_div_write_commit = io_baud_div_write_commit_0;	// src/main/scala/Design.scala:406:7, :691:24, :710:24, :711:24
  assign io_baud_div_value = _csr_value1;	// src/main/scala/Design.scala:406:7, :453:28
  assign io_baud_div_candidate = io_baud_div_candidate_0;	// src/main/scala/Design.scala:406:7, :703:24
  assign io_tx_data_write_commit = _csr_n162_T & _csr_n120_T & _csr_n117_T & _csr_n108;	// src/main/scala/Design.scala:406:7, :629:28, :735:24, :736:25, :741:26, :750:25, :751:26, :752:26
  assign io_tx_data_candidate = io_wdata & {24'h0, _csr_n66[7:0]};	// src/main/scala/Design.scala:406:7, :644:24, :648:24, :652:24, :740:25, :744:25
  assign io_rx_data_read_commit = _csr_n162_T & _csr_n134_T & _csr_n131_T;	// src/main/scala/Design.scala:406:7, :629:28, :762:24, :763:25, :766:25, :767:26
endmodule


// Generated by CIRCT firtool-1.159.0
module BitloomUartCsrFifo8x4(	// src/main/scala/Design.scala:816:7
  input        clock,	// src/main/scala/Design.scala:816:7
               reset,	// src/main/scala/Design.scala:816:7
               io_input_valid,	// src/main/scala/Design.scala:817:14
               io_output_ready,	// src/main/scala/Design.scala:817:14
  input  [7:0] io_input_data,	// src/main/scala/Design.scala:817:14
  output       io_input_ready,	// src/main/scala/Design.scala:817:14
               io_output_valid,	// src/main/scala/Design.scala:817:14
  output [7:0] io_output_data	// src/main/scala/Design.scala:817:14
);

  reg  [2:0] count;	// src/main/scala/Design.scala:826:22
  reg  [7:0] slot_0;	// src/main/scala/Design.scala:840:23
  reg  [7:0] slot_1;	// src/main/scala/Design.scala:846:23
  reg  [7:0] slot_2;	// src/main/scala/Design.scala:852:23
  reg  [7:0] slot_3;	// src/main/scala/Design.scala:858:23
  wire       io_output_valid_0 = |count;	// src/main/scala/Design.scala:826:22, :868:18
  wire       io_input_ready_0 = count != 3'h4;	// src/main/scala/Design.scala:826:22, :866:12, :869:17
  wire       push = io_input_valid & io_input_ready_0;	// src/main/scala/Design.scala:869:17, :873:26
  wire       pop = io_output_valid_0 & io_output_ready;	// src/main/scala/Design.scala:868:18, :874:26
  wire [2:0] _decremented_T = count - 3'h1;	// src/main/scala/Design.scala:826:22, :875:24
  wire [2:0] after_pop = pop ? _decremented_T : count;	// src/main/scala/Design.scala:826:22, :874:26, :875:24, :876:19
  always @(posedge clock) begin	// src/main/scala/Design.scala:816:7
    if (reset) begin	// src/main/scala/Design.scala:816:7
      count <= 3'h0;	// src/main/scala/Design.scala:826:22
      slot_0 <= 8'h0;	// src/main/scala/Design.scala:840:23
      slot_1 <= 8'h0;	// src/main/scala/Design.scala:840:23, :846:23
      slot_2 <= 8'h0;	// src/main/scala/Design.scala:840:23, :852:23
      slot_3 <= 8'h0;	// src/main/scala/Design.scala:840:23, :858:23
    end
    else begin	// src/main/scala/Design.scala:816:7
      if (push)	// src/main/scala/Design.scala:873:26
        count <= after_pop + 3'h1;	// src/main/scala/Design.scala:826:22, :876:19, :877:28
      else if (pop)	// src/main/scala/Design.scala:874:26
        count <= _decremented_T;	// src/main/scala/Design.scala:826:22, :875:24
      if (push & after_pop == 3'h0)	// src/main/scala/Design.scala:873:26, :876:19, :881:21, :882:19
        slot_0 <= io_input_data;	// src/main/scala/Design.scala:840:23
      else if (pop)	// src/main/scala/Design.scala:874:26
        slot_0 <= slot_1;	// src/main/scala/Design.scala:840:23, :846:23
      if (push & after_pop == 3'h1)	// src/main/scala/Design.scala:873:26, :876:19, :886:21, :887:19
        slot_1 <= io_input_data;	// src/main/scala/Design.scala:846:23
      else if (pop)	// src/main/scala/Design.scala:874:26
        slot_1 <= slot_2;	// src/main/scala/Design.scala:846:23, :852:23
      if (push & after_pop == 3'h2)	// src/main/scala/Design.scala:873:26, :876:19, :890:11, :891:21, :892:19
        slot_2 <= io_input_data;	// src/main/scala/Design.scala:852:23
      else if (pop)	// src/main/scala/Design.scala:874:26
        slot_2 <= slot_3;	// src/main/scala/Design.scala:852:23, :858:23
      if (push & after_pop == 3'h3)	// src/main/scala/Design.scala:873:26, :876:19, :895:11, :896:21, :897:19
        slot_3 <= io_input_data;	// src/main/scala/Design.scala:858:23
    end
  end // always @(posedge)
  assign io_input_ready = io_input_ready_0;	// src/main/scala/Design.scala:816:7, :869:17
  assign io_output_valid = io_output_valid_0;	// src/main/scala/Design.scala:816:7, :868:18
  assign io_output_data = slot_0;	// src/main/scala/Design.scala:816:7, :840:23
endmodule


// Generated by CIRCT firtool-1.159.0
module Fr198Uart(	// src/main/scala/Design.scala:907:7
  input         clock,	// src/main/scala/Design.scala:907:7
                reset,	// src/main/scala/Design.scala:907:7
                io_req_valid,	// src/main/scala/Design.scala:908:14
                io_write,	// src/main/scala/Design.scala:908:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:908:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:908:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:908:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:908:14
  output        io_req_ready,	// src/main/scala/Design.scala:908:14
                io_rsp_valid,	// src/main/scala/Design.scala:908:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:908:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:908:14
  input         io_rx,	// src/main/scala/Design.scala:908:14
  output        io_tx,	// src/main/scala/Design.scala:908:14
  output [3:0]  io_raw_events	// src/main/scala/Design.scala:908:14
);

  wire        _rxq_io_input_ready;	// src/main/scala/Design.scala:1015:19
  wire        _rxq_io_output_valid;	// src/main/scala/Design.scala:1015:19
  wire [7:0]  _rxq_io_output_data;	// src/main/scala/Design.scala:1015:19
  wire        _txq_io_input_ready;	// src/main/scala/Design.scala:1001:19
  wire        _txq_io_output_valid;	// src/main/scala/Design.scala:1001:19
  wire [7:0]  _txq_io_output_data;	// src/main/scala/Design.scala:1001:19
  wire        _csr_io_ctrl_write_commit;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_ctrl_value;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_ctrl_candidate;	// src/main/scala/Design.scala:953:19
  wire        _csr_io_baud_div_write_commit;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_baud_div_value;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_baud_div_candidate;	// src/main/scala/Design.scala:953:19
  wire        _csr_io_tx_data_write_commit;	// src/main/scala/Design.scala:953:19
  wire [31:0] _csr_io_tx_data_candidate;	// src/main/scala/Design.scala:953:19
  wire        _csr_io_rx_data_read_commit;	// src/main/scala/Design.scala:953:19
  reg         sync1;	// src/main/scala/Design.scala:1023:22
  reg         sync2;	// src/main/scala/Design.scala:1024:22
  reg         history;	// src/main/scala/Design.scala:1025:24
  reg         tx_busy;	// src/main/scala/Design.scala:1026:24
  reg         tx_line;	// src/main/scala/Design.scala:1027:24
  reg  [3:0]  tx_index;	// src/main/scala/Design.scala:1028:25
  reg  [7:0]  tx_shift;	// src/main/scala/Design.scala:1029:25
  reg  [31:0] tx_timer;	// src/main/scala/Design.scala:1030:25
  reg  [31:0] tx_div;	// src/main/scala/Design.scala:1031:23
  reg  [3:0]  rx_state;	// src/main/scala/Design.scala:1032:25
  reg  [7:0]  rx_shift;	// src/main/scala/Design.scala:1033:25
  reg  [31:0] rx_timer;	// src/main/scala/Design.scala:1034:25
  reg  [31:0] rx_div;	// src/main/scala/Design.scala:1035:23
  wire        _uart_n97_T = |rx_state;	// src/main/scala/Design.scala:1032:25, :1166:24
  wire        _uart_n11 = tx_busy | _uart_n97_T;	// src/main/scala/Design.scala:1026:24, :1166:24, :1169:24
  wire        _uart_n29 =
    _csr_io_ctrl_write_commit ? _csr_io_ctrl_candidate[0] : _csr_io_ctrl_value[0];	// src/main/scala/Design.scala:953:19, :1170:26, :1171:30, :1191:19
  wire        txq_output_ready = ~tx_busy & _uart_n29 & _txq_io_output_valid & ~reset;	// src/main/scala/Design.scala:1001:19, :1026:24, :1165:35, :1191:19, :1208:24, :1209:26, :1210:26, :1211:26
  wire        _uart_n96_T = rx_timer == 32'h0;	// src/main/scala/Design.scala:1030:25, :1034:25, :1253:25
  wire        _uart_n92_T = _uart_n97_T & _uart_n96_T;	// src/main/scala/Design.scala:1166:24, :1253:25, :1254:26
  wire        _uart_n87 = rx_state == 4'hA;	// src/main/scala/Design.scala:1032:25, :1256:13, :1257:25
  wire        _uart_n110 = _uart_n92_T & _uart_n87 & ~reset;	// src/main/scala/Design.scala:1165:35, :1254:26, :1257:25, :1279:27, :1280:28
  wire        _uart_n111 = _uart_n110 & sync2;	// src/main/scala/Design.scala:1024:22, :1279:27, :1280:28, :1281:28
  wire        rxq_input_valid = _uart_n111 & _rxq_io_input_ready;	// src/main/scala/Design.scala:1015:19, :1281:28, :1282:28
  wire        _uart_n115 = _uart_n111 & ~_rxq_io_input_ready;	// src/main/scala/Design.scala:1015:19, :1281:28, :1284:33, :1285:28
  wire        _uart_n116 = _uart_n110 & ~sync2;	// src/main/scala/Design.scala:1024:22, :1241:22, :1279:27, :1280:28, :1286:28
  wire [31:0] _uart_n30 =
    _csr_io_baud_div_write_commit ? _csr_io_baud_div_candidate : _csr_io_baud_div_value;	// src/main/scala/Design.scala:953:19, :1192:19
  wire        _uart_n55_T = tx_timer == 32'h0;	// src/main/scala/Design.scala:1030:25, :1213:25
  wire        _uart_n67_T = tx_busy & _uart_n55_T;	// src/main/scala/Design.scala:1026:24, :1213:25, :1214:24
  wire        _uart_n85 = rx_state == 4'h1;	// src/main/scala/Design.scala:1032:25, :1255:25
  always @(posedge clock) begin	// src/main/scala/Design.scala:907:7
    if (reset) begin	// src/main/scala/Design.scala:907:7
      sync1 <= 1'h0;	// src/main/scala/Design.scala:1023:22
      sync2 <= 1'h0;	// src/main/scala/Design.scala:1024:22
      history <= 1'h0;	// src/main/scala/Design.scala:1025:24
      tx_busy <= 1'h0;	// src/main/scala/Design.scala:1026:24
      tx_line <= 1'h0;	// src/main/scala/Design.scala:1027:24
      tx_index <= 4'h0;	// src/main/scala/Design.scala:1028:25
      tx_shift <= 8'h0;	// src/main/scala/Design.scala:1029:25
      tx_timer <= 32'h0;	// src/main/scala/Design.scala:1030:25
      tx_div <= 32'h0;	// src/main/scala/Design.scala:1030:25, :1031:23
      rx_state <= 4'h0;	// src/main/scala/Design.scala:1032:25
      rx_shift <= 8'h0;	// src/main/scala/Design.scala:1029:25, :1033:25
      rx_timer <= 32'h0;	// src/main/scala/Design.scala:1030:25, :1034:25
      rx_div <= 32'h0;	// src/main/scala/Design.scala:1030:25, :1035:23
    end
    else begin	// src/main/scala/Design.scala:907:7
      sync1 <= io_rx;	// src/main/scala/Design.scala:1023:22
      sync2 <= sync1;	// src/main/scala/Design.scala:1023:22, :1024:22
      history <= sync2;	// src/main/scala/Design.scala:1024:22, :1025:24
      tx_busy <= txq_output_ready | ~(_uart_n67_T & tx_index == 4'h9) & tx_busy;	// src/main/scala/Design.scala:1026:24, :1028:25, :1209:26, :1210:26, :1211:26, :1214:24, :1215:13, :1216:25, :1217:26, :1218:19, :1219:19
      tx_line <=
        ~txq_output_ready & (_uart_n67_T ? tx_index == 4'h8 | tx_shift[0] : tx_line);	// src/main/scala/Design.scala:1027:24, :1028:25, :1029:25, :1209:26, :1210:26, :1211:26, :1214:24, :1232:13, :1233:25, :1234:24, :1235:19, :1236:19, :1237:19
      if (txq_output_ready) begin	// src/main/scala/Design.scala:1209:26, :1210:26, :1211:26
        tx_index <= 4'h0;	// src/main/scala/Design.scala:1028:25
        tx_shift <= _txq_io_output_data;	// src/main/scala/Design.scala:1001:19, :1029:25
        tx_timer <= _uart_n30;	// src/main/scala/Design.scala:1030:25, :1192:19
        tx_div <= _uart_n30;	// src/main/scala/Design.scala:1031:23, :1192:19
      end
      else begin	// src/main/scala/Design.scala:1209:26, :1210:26, :1211:26
        if (_uart_n67_T) begin	// src/main/scala/Design.scala:1214:24
          tx_index <= tx_index + 4'h1;	// src/main/scala/Design.scala:1028:25, :1220:25
          tx_shift <= {1'h0, tx_shift[7:1]};	// src/main/scala/Design.scala:1029:25, :1228:24, :1229:32
        end
        if (tx_busy)	// src/main/scala/Design.scala:1026:24
          tx_timer <= _uart_n55_T ? tx_div : tx_timer - 32'h1;	// src/main/scala/Design.scala:1030:25, :1031:23, :1213:25, :1223:25, :1224:19
      end
      if (~_uart_n97_T & ~sync2 & history & _uart_n29 & ~reset) begin	// src/main/scala/Design.scala:1024:22, :1025:24, :1165:35, :1166:24, :1191:19, :1241:22, :1242:26, :1243:25, :1244:26, :1245:26
        rx_state <= 4'h1;	// src/main/scala/Design.scala:1032:25
        rx_timer <= {1'h0, _uart_n30[31:1]} + {31'h0, _uart_n30[0]} - 32'h1;	// src/main/scala/Design.scala:1034:25, :1192:19, :1246:25, :1248:25, :1251:26, :1252:26
        rx_div <= _uart_n30;	// src/main/scala/Design.scala:1035:23, :1192:19
      end
      else begin	// src/main/scala/Design.scala:1242:26, :1243:25, :1244:26, :1245:26
        if (_uart_n92_T & (_uart_n85 & sync2 | _uart_n87))	// src/main/scala/Design.scala:1024:22, :1254:26, :1255:25, :1257:25, :1258:26, :1259:26, :1260:26
          rx_state <= 4'h0;	// src/main/scala/Design.scala:1032:25
        else if (_uart_n92_T)	// src/main/scala/Design.scala:1254:26
          rx_state <= rx_state + 4'h1;	// src/main/scala/Design.scala:1032:25, :1261:25
        if (_uart_n97_T)	// src/main/scala/Design.scala:1166:24
          rx_timer <= _uart_n96_T ? rx_div : rx_timer - 32'h1;	// src/main/scala/Design.scala:1034:25, :1035:23, :1253:25, :1265:25, :1266:19
      end
      if (_uart_n92_T & ~_uart_n85 & ~_uart_n87)	// src/main/scala/Design.scala:1254:26, :1255:25, :1257:25, :1271:27, :1273:27, :1274:28, :1275:27
        rx_shift <= {sync2, rx_shift[7:1]};	// src/main/scala/Design.scala:1024:22, :1033:25, :1276:25, :1277:33
    end
  end // always @(posedge)
  BitloomUartCsrRegisters csr (	// src/main/scala/Design.scala:953:19
    .clock                    (clock),
    .reset                    (reset),
    .io_req_valid             (io_req_valid),
    .io_write                 (io_write),
    .io_addr                  (io_addr),
    .io_wdata                 (io_wdata),
    .io_wstrb                 (io_wstrb),
    .io_rsp_ready             (io_rsp_ready),
    .io_req_ready             (io_req_ready),
    .io_rsp_valid             (io_rsp_valid),
    .io_rdata                 (io_rdata),
    .io_error                 (io_error),
    .io_ctrl_write_commit     (_csr_io_ctrl_write_commit),
    .io_ctrl_value            (_csr_io_ctrl_value),
    .io_ctrl_candidate        (_csr_io_ctrl_candidate),
    .io_ctrl_write_reject
      (_uart_n11 & _csr_io_ctrl_value[0] != _csr_io_ctrl_candidate[0]
       | _csr_io_ctrl_candidate[0] & _csr_io_baud_div_value < 32'h3),	// src/main/scala/Design.scala:953:19, :1169:24, :1170:26, :1171:30, :1172:26, :1175:26, :1176:13, :1177:31, :1178:26, :1179:26
    .io_baud_div_write_commit (_csr_io_baud_div_write_commit),
    .io_baud_div_value        (_csr_io_baud_div_value),
    .io_baud_div_candidate    (_csr_io_baud_div_candidate),
    .io_baud_div_write_reject
      (_uart_n11 | _csr_io_ctrl_value[0] & _csr_io_baud_div_candidate < 32'h3),	// src/main/scala/Design.scala:953:19, :1169:24, :1170:26, :1176:13, :1181:35, :1182:26, :1183:26
    .io_status_value
      ({28'h0, _uart_n97_T, tx_busy, ~_txq_io_input_ready, _rxq_io_output_valid}),	// src/main/scala/Design.scala:1001:19, :1015:19, :1026:24, :1166:24, :1186:32, :1196:13, :1197:32
    .io_tx_data_write_commit  (_csr_io_tx_data_write_commit),
    .io_tx_data_candidate     (_csr_io_tx_data_candidate),
    .io_tx_data_write_reject  (~_txq_io_input_ready),	// src/main/scala/Design.scala:1001:19, :1186:32
    .io_rx_data_read_commit   (_csr_io_rx_data_read_commit),
    .io_rx_data_value         ({24'h0, _rxq_io_output_data}),	// src/main/scala/Design.scala:1015:19, :1199:13, :1200:32
    .io_rx_data_read_reject   (~_rxq_io_output_valid),	// src/main/scala/Design.scala:1015:19, :1189:33
    .io_event_bits
      ({28'h0, _uart_n116, _uart_n115, txq_output_ready, rxq_input_valid})	// src/main/scala/Design.scala:1196:13, :1209:26, :1210:26, :1211:26, :1282:28, :1285:28, :1286:28, :1292:33
  );	// src/main/scala/Design.scala:953:19
  BitloomUartCsrFifo8x4 txq (	// src/main/scala/Design.scala:1001:19
    .clock           (clock),
    .reset           (reset),
    .io_input_valid  (_csr_io_tx_data_write_commit),	// src/main/scala/Design.scala:953:19
    .io_output_ready (txq_output_ready),	// src/main/scala/Design.scala:1209:26, :1210:26, :1211:26
    .io_input_data   (_csr_io_tx_data_candidate[7:0]),	// src/main/scala/Design.scala:953:19, :1203:33
    .io_input_ready  (_txq_io_input_ready),
    .io_output_valid (_txq_io_output_valid),
    .io_output_data  (_txq_io_output_data)
  );	// src/main/scala/Design.scala:1001:19
  BitloomUartCsrFifo8x4 rxq (	// src/main/scala/Design.scala:1015:19
    .clock           (clock),
    .reset           (reset),
    .io_input_valid  (rxq_input_valid),	// src/main/scala/Design.scala:1282:28
    .io_output_ready (_csr_io_rx_data_read_commit),	// src/main/scala/Design.scala:953:19
    .io_input_data   (rx_shift),	// src/main/scala/Design.scala:1033:25
    .io_input_ready  (_rxq_io_input_ready),
    .io_output_valid (_rxq_io_output_valid),
    .io_output_data  (_rxq_io_output_data)
  );	// src/main/scala/Design.scala:1015:19
  assign io_tx = ~tx_busy | tx_line;	// src/main/scala/Design.scala:907:7, :1026:24, :1027:24, :1238:19
  assign io_raw_events = {_uart_n116, _uart_n115, txq_output_ready, rxq_input_valid};	// src/main/scala/Design.scala:907:7, :1209:26, :1210:26, :1211:26, :1282:28, :1285:28, :1286:28, :1290:33
endmodule


// Generated by CIRCT firtool-1.159.0
module BitloomGpioCsrRegisters(	// src/main/scala/Design.scala:1309:7
  input         clock,	// src/main/scala/Design.scala:1309:7
                reset,	// src/main/scala/Design.scala:1309:7
                io_req_valid,	// src/main/scala/Design.scala:1310:14
                io_write,	// src/main/scala/Design.scala:1310:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:1310:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:1310:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:1310:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:1310:14
  output        io_req_ready,	// src/main/scala/Design.scala:1310:14
                io_rsp_valid,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:1310:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_dir_value,	// src/main/scala/Design.scala:1310:14
  output        io_out_write_commit,	// src/main/scala/Design.scala:1310:14
  input  [31:0] io_out_value,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_out_candidate,	// src/main/scala/Design.scala:1310:14
  input  [31:0] io_in_value,	// src/main/scala/Design.scala:1310:14
  output        io_set_write_commit,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_set_candidate,	// src/main/scala/Design.scala:1310:14
  output        io_clear_write_commit,	// src/main/scala/Design.scala:1310:14
  output [31:0] io_clear_candidate,	// src/main/scala/Design.scala:1310:14
  input  [31:0] io_rise_bits	// src/main/scala/Design.scala:1310:14
);

  reg         _csr_pending;	// src/main/scala/Design.scala:1349:29
  reg  [31:0] _csr_data;	// src/main/scala/Design.scala:1350:26
  reg  [1:0]  _csr_error;	// src/main/scala/Design.scala:1351:27
  reg  [31:0] _csr_value0;	// src/main/scala/Design.scala:1352:28
  reg  [31:0] _csr_value5;	// src/main/scala/Design.scala:1353:28
  wire        io_req_ready_0 = ~_csr_pending & ~reset;	// src/main/scala/Design.scala:1349:29, :1518:27, :1520:34, :1521:22
  wire        _csr_n157_T = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:1521:22, :1523:28
  wire [31:0] _csr_n137 =
    (io_wstrb[0] ? 32'hFF : 32'h0) | (io_wstrb[1] ? 32'hFF00 : 32'h0)
    | (io_wstrb[2] ? 32'hFF0000 : 32'h0) | (io_wstrb[3] ? 32'hFF000000 : 32'h0);	// src/main/scala/Design.scala:1531:23, :1532:12, :1533:18, :1535:23, :1536:12, :1537:18, :1538:24, :1539:23, :1540:12, :1541:18, :1542:24, :1543:23, :1544:12, :1545:18, :1546:24
  wire        _csr_n79_T = io_addr == 16'h4;	// src/main/scala/Design.scala:1579:12, :1580:23
  wire        _csr_n110_T = io_addr == 16'hC;	// src/main/scala/Design.scala:1620:12, :1621:23
  wire        _csr_n129_T = io_addr == 16'h10;	// src/main/scala/Design.scala:1643:13, :1644:24
  wire        _csr_n91_T = io_addr == 16'h8;	// src/main/scala/Design.scala:1607:12, :1608:23
  wire        _csr_n54_T = io_addr == 16'h0;	// src/main/scala/Design.scala:1551:23
  wire        _csr_n149_T = io_addr == 16'h14;	// src/main/scala/Design.scala:1668:13, :1669:24
  always @(posedge clock) begin	// src/main/scala/Design.scala:1309:7
    if (reset) begin	// src/main/scala/Design.scala:1309:7
      _csr_pending <= 1'h0;	// src/main/scala/Design.scala:1349:29
      _csr_data <= 32'h0;	// src/main/scala/Design.scala:1350:26
      _csr_error <= 2'h0;	// src/main/scala/Design.scala:1351:27
      _csr_value0 <= 32'h0;	// src/main/scala/Design.scala:1352:28
      _csr_value5 <= 32'h0;	// src/main/scala/Design.scala:1353:28
    end
    else begin	// src/main/scala/Design.scala:1309:7
      _csr_pending <= _csr_n157_T | ~io_rsp_ready & _csr_pending;	// src/main/scala/Design.scala:1349:29, :1523:28, :1526:18, :1527:18
      if (_csr_n157_T) begin	// src/main/scala/Design.scala:1523:28
        _csr_data <=
          _csr_n149_T
            ? (io_write ? 32'h0 : _csr_value5)
            : _csr_n129_T | _csr_n110_T
                ? 32'h0
                : _csr_n91_T
                    ? (io_write ? 32'h0 : io_in_value)
                    : _csr_n79_T
                        ? (io_write ? 32'h0 : io_out_value)
                        : _csr_n54_T & ~io_write ? _csr_value0 : 32'h0;	// src/main/scala/Design.scala:1350:26, :1352:28, :1353:28, :1525:24, :1551:23, :1574:18, :1575:18, :1580:23, :1603:18, :1604:18, :1608:23, :1617:18, :1618:18, :1621:23, :1641:19, :1644:24, :1664:19, :1669:24, :1688:19, :1689:19
        _csr_error <=
          _csr_n149_T
            ? 2'h0
            : _csr_n129_T
                ? {~io_write, 1'h0}
                : _csr_n110_T
                    ? {~io_write, 1'h0}
                    : _csr_n91_T
                        ? {io_write, 1'h0}
                        : _csr_n79_T ? 2'h0 : {~_csr_n54_T, 1'h0};	// src/main/scala/Design.scala:1351:27, :1551:23, :1572:18, :1573:18, :1580:23, :1602:18, :1608:23, :1615:18, :1616:18, :1621:23, :1638:19, :1639:19, :1644:24, :1661:19, :1662:19, :1669:24, :1687:19
      end
      if (_csr_n157_T & _csr_n54_T & io_write & (|_csr_n137))	// src/main/scala/Design.scala:1523:28, :1538:24, :1542:24, :1546:24, :1551:23, :1552:24, :1557:24, :1568:24, :1569:24
        _csr_value0 <= _csr_value0 & ~_csr_n137 | io_wdata & _csr_n137;	// src/main/scala/Design.scala:1352:28, :1538:24, :1542:24, :1546:24, :1560:24, :1562:24, :1563:24, :1564:24
      _csr_value5 <=
        _csr_value5
        & ~(_csr_n157_T & _csr_n149_T & io_write & (|_csr_n137)
              ? io_wdata & _csr_n137
              : 32'h0) | io_rise_bits;	// src/main/scala/Design.scala:1353:28, :1523:28, :1538:24, :1542:24, :1546:24, :1669:24, :1670:25, :1675:26, :1678:25, :1682:26, :1683:26, :1690:19, :1692:26, :1693:26, :1695:26
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:1309:7, :1521:22
  assign io_rsp_valid = _csr_pending;	// src/main/scala/Design.scala:1309:7, :1349:29
  assign io_rdata = _csr_data;	// src/main/scala/Design.scala:1309:7, :1350:26
  assign io_error = _csr_error;	// src/main/scala/Design.scala:1309:7, :1351:27
  assign io_dir_value = _csr_value0;	// src/main/scala/Design.scala:1309:7, :1352:28
  assign io_out_write_commit = _csr_n157_T & _csr_n79_T & io_write & (|_csr_n137);	// src/main/scala/Design.scala:1309:7, :1523:28, :1538:24, :1542:24, :1546:24, :1580:23, :1581:24, :1586:24, :1597:24, :1598:24
  assign io_out_candidate = io_out_value & ~_csr_n137 | io_wdata & _csr_n137;	// src/main/scala/Design.scala:1309:7, :1538:24, :1542:24, :1546:24, :1589:24, :1591:24, :1592:24, :1593:24
  assign io_set_write_commit = _csr_n157_T & _csr_n110_T & io_write & (|_csr_n137);	// src/main/scala/Design.scala:1309:7, :1523:28, :1538:24, :1542:24, :1546:24, :1621:23, :1622:24, :1627:24, :1634:26, :1635:25
  assign io_set_candidate = io_wdata & _csr_n137;	// src/main/scala/Design.scala:1309:7, :1538:24, :1542:24, :1546:24, :1630:25
  assign io_clear_write_commit = _csr_n157_T & _csr_n129_T & io_write & (|_csr_n137);	// src/main/scala/Design.scala:1309:7, :1523:28, :1538:24, :1542:24, :1546:24, :1644:24, :1645:25, :1650:26, :1657:26, :1658:26
  assign io_clear_candidate = io_wdata & _csr_n137;	// src/main/scala/Design.scala:1309:7, :1538:24, :1542:24, :1546:24, :1653:25
endmodule


// Generated by CIRCT firtool-1.159.0
module Fr198Gpio(	// src/main/scala/Design.scala:1705:7
  input         clock,	// src/main/scala/Design.scala:1705:7
                reset,	// src/main/scala/Design.scala:1705:7
                io_req_valid,	// src/main/scala/Design.scala:1706:14
                io_write,	// src/main/scala/Design.scala:1706:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:1706:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:1706:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:1706:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:1706:14
  output        io_req_ready,	// src/main/scala/Design.scala:1706:14
                io_rsp_valid,	// src/main/scala/Design.scala:1706:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:1706:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:1706:14
  input  [31:0] io_pad_in,	// src/main/scala/Design.scala:1706:14
  output [31:0] io_pad_out,	// src/main/scala/Design.scala:1706:14
                io_pad_oe,	// src/main/scala/Design.scala:1706:14
  output        io_raw_event	// src/main/scala/Design.scala:1706:14
);

  wire [31:0] _csr_io_dir_value;	// src/main/scala/Design.scala:1768:19
  wire        _csr_io_out_write_commit;	// src/main/scala/Design.scala:1768:19
  wire [31:0] _csr_io_out_candidate;	// src/main/scala/Design.scala:1768:19
  wire        _csr_io_set_write_commit;	// src/main/scala/Design.scala:1768:19
  wire [31:0] _csr_io_set_candidate;	// src/main/scala/Design.scala:1768:19
  wire        _csr_io_clear_write_commit;	// src/main/scala/Design.scala:1768:19
  wire [31:0] _csr_io_clear_candidate;	// src/main/scala/Design.scala:1768:19
  reg  [31:0] out_r;	// src/main/scala/Design.scala:1748:22
  reg  [31:0] sync1;	// src/main/scala/Design.scala:1749:22
  reg  [31:0] sync2;	// src/main/scala/Design.scala:1750:22
  reg  [31:0] history;	// src/main/scala/Design.scala:1751:24
  wire [31:0] rise_bits = sync2 & ~history & ~_csr_io_dir_value;	// src/main/scala/Design.scala:1750:22, :1751:24, :1768:19, :1813:26, :1814:24, :1815:19, :1816:23
  always @(posedge clock) begin	// src/main/scala/Design.scala:1705:7
    if (reset) begin	// src/main/scala/Design.scala:1705:7
      out_r <= 32'h0;	// src/main/scala/Design.scala:1748:22
      sync1 <= 32'h0;	// src/main/scala/Design.scala:1748:22, :1749:22
      sync2 <= 32'h0;	// src/main/scala/Design.scala:1748:22, :1750:22
      history <= 32'h0;	// src/main/scala/Design.scala:1748:22, :1751:24
    end
    else begin	// src/main/scala/Design.scala:1705:7
      out_r <=
        _csr_io_out_write_commit
          ? _csr_io_out_candidate
          : _csr_io_set_write_commit
              ? out_r | _csr_io_set_candidate
              : ({32{~_csr_io_clear_write_commit}} | ~_csr_io_clear_candidate) & out_r;	// src/main/scala/Design.scala:1748:22, :1768:19, :1821:22, :1822:32, :1824:21, :1825:19, :1826:18
      sync1 <= io_pad_in;	// src/main/scala/Design.scala:1749:22
      sync2 <= sync1;	// src/main/scala/Design.scala:1749:22, :1750:22
      history <= sync2;	// src/main/scala/Design.scala:1750:22, :1751:24
    end
  end // always @(posedge)
  BitloomGpioCsrRegisters csr (	// src/main/scala/Design.scala:1768:19
    .clock                 (clock),
    .reset                 (reset),
    .io_req_valid          (io_req_valid),
    .io_write              (io_write),
    .io_addr               (io_addr),
    .io_wdata              (io_wdata),
    .io_wstrb              (io_wstrb),
    .io_rsp_ready          (io_rsp_ready),
    .io_req_ready          (io_req_ready),
    .io_rsp_valid          (io_rsp_valid),
    .io_rdata              (io_rdata),
    .io_error              (io_error),
    .io_dir_value          (_csr_io_dir_value),
    .io_out_write_commit   (_csr_io_out_write_commit),
    .io_out_value          (out_r),	// src/main/scala/Design.scala:1748:22
    .io_out_candidate      (_csr_io_out_candidate),
    .io_in_value           (sync2),	// src/main/scala/Design.scala:1750:22
    .io_set_write_commit   (_csr_io_set_write_commit),
    .io_set_candidate      (_csr_io_set_candidate),
    .io_clear_write_commit (_csr_io_clear_write_commit),
    .io_clear_candidate    (_csr_io_clear_candidate),
    .io_rise_bits          (rise_bits)	// src/main/scala/Design.scala:1815:19, :1816:23
  );	// src/main/scala/Design.scala:1768:19
  assign io_pad_out = out_r & _csr_io_dir_value;	// src/main/scala/Design.scala:1705:7, :1748:22, :1768:19, :1812:23
  assign io_pad_oe = _csr_io_dir_value;	// src/main/scala/Design.scala:1705:7, :1768:19
  assign io_raw_event = (|rise_bits) & ~reset;	// src/main/scala/Design.scala:1705:7, :1815:19, :1816:23, :1817:22, :1819:36, :1820:28
endmodule


// Generated by CIRCT firtool-1.159.0
module BitloomTimerCsr(	// src/main/scala/Design.scala:1833:7
  input         clock,	// src/main/scala/Design.scala:1833:7
                reset,	// src/main/scala/Design.scala:1833:7
                io_req_valid,	// src/main/scala/Design.scala:1834:14
                io_write,	// src/main/scala/Design.scala:1834:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:1834:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:1834:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:1834:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:1834:14
  output        io_req_ready,	// src/main/scala/Design.scala:1834:14
                io_rsp_valid,	// src/main/scala/Design.scala:1834:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:1834:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:1834:14
  output        io_ctrl_write_commit,	// src/main/scala/Design.scala:1834:14
  input  [31:0] io_ctrl_value,	// src/main/scala/Design.scala:1834:14
  output [31:0] io_ctrl_candidate,	// src/main/scala/Design.scala:1834:14
  output        io_count_write_commit,	// src/main/scala/Design.scala:1834:14
  input  [31:0] io_count_value,	// src/main/scala/Design.scala:1834:14
  output [31:0] io_count_candidate,	// src/main/scala/Design.scala:1834:14
  output        io_compare_write_commit,	// src/main/scala/Design.scala:1834:14
  output [31:0] io_compare_value,	// src/main/scala/Design.scala:1834:14
  input  [31:0] io_match_bits	// src/main/scala/Design.scala:1834:14
);

  reg         _csr_pending;	// src/main/scala/Design.scala:1867:29
  reg  [31:0] _csr_data;	// src/main/scala/Design.scala:1868:26
  reg  [1:0]  _csr_error;	// src/main/scala/Design.scala:1869:27
  reg  [31:0] _csr_value2;	// src/main/scala/Design.scala:1870:28
  reg  [31:0] _csr_value3;	// src/main/scala/Design.scala:1871:28
  wire        io_req_ready_0 = ~_csr_pending & ~reset;	// src/main/scala/Design.scala:1867:29, :2010:27, :2012:34, :2013:22
  wire        _csr_n131_T = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:2013:22, :2015:28
  wire [31:0] _csr_n86 =
    (io_wstrb[0] ? 32'hFF : 32'h0) | (io_wstrb[1] ? 32'hFF00 : 32'h0)
    | (io_wstrb[2] ? 32'hFF0000 : 32'h0) | (io_wstrb[3] ? 32'hFF000000 : 32'h0);	// src/main/scala/Design.scala:2023:23, :2024:12, :2025:18, :2027:23, :2028:12, :2029:18, :2030:24, :2031:23, :2032:12, :2033:18, :2034:24, :2035:23, :2036:12, :2037:18, :2038:24
  wire [31:0] _csr_n32 = {30'h0, io_ctrl_value[1:0]};	// src/main/scala/Design.scala:2040:29
  wire        _csr_n54_T = io_addr == 16'h0;	// src/main/scala/Design.scala:2042:23
  wire        _csr_n78_T = io_addr == 16'h4;	// src/main/scala/Design.scala:2069:12, :2070:23
  wire        _csr_n102_T = io_addr == 16'h8;	// src/main/scala/Design.scala:2098:12, :2099:23
  wire        io_compare_write_commit_0 =
    _csr_n131_T & _csr_n102_T & io_write & (|_csr_n86);	// src/main/scala/Design.scala:2015:28, :2030:24, :2034:24, :2038:24, :2099:23, :2100:24, :2105:24, :2116:24, :2117:24
  wire [31:0] _csr_n105 = {31'h0, _csr_value3[0]};	// src/main/scala/Design.scala:1871:28, :2126:28
  wire        _csr_n123_T = io_addr == 16'hC;	// src/main/scala/Design.scala:2128:13, :2129:24
  always @(posedge clock) begin	// src/main/scala/Design.scala:1833:7
    if (reset) begin	// src/main/scala/Design.scala:1833:7
      _csr_pending <= 1'h0;	// src/main/scala/Design.scala:1867:29
      _csr_data <= 32'h0;	// src/main/scala/Design.scala:1868:26
      _csr_error <= 2'h0;	// src/main/scala/Design.scala:1869:27
      _csr_value2 <= 32'h0;	// src/main/scala/Design.scala:1870:28
      _csr_value3 <= 32'h0;	// src/main/scala/Design.scala:1871:28
    end
    else begin	// src/main/scala/Design.scala:1833:7
      _csr_pending <= _csr_n131_T | ~io_rsp_ready & _csr_pending;	// src/main/scala/Design.scala:1867:29, :2015:28, :2018:18, :2019:18
      if (_csr_n131_T) begin	// src/main/scala/Design.scala:2015:28
        _csr_data <=
          _csr_n123_T
            ? (io_write ? 32'h0 : _csr_n105)
            : _csr_n102_T
                ? (io_write ? 32'h0 : _csr_value2)
                : _csr_n78_T
                    ? (io_write ? 32'h0 : io_count_value)
                    : _csr_n54_T & ~io_write ? _csr_n32 : 32'h0;	// src/main/scala/Design.scala:1868:26, :1870:28, :2017:24, :2040:29, :2042:23, :2065:18, :2066:18, :2070:23, :2093:18, :2094:18, :2099:23, :2122:19, :2123:19, :2126:28, :2129:24, :2148:19, :2149:19
        _csr_error <= _csr_n123_T | _csr_n102_T | _csr_n78_T ? 2'h0 : {~_csr_n54_T, 1'h0};	// src/main/scala/Design.scala:1869:27, :2042:23, :2063:18, :2064:18, :2070:23, :2099:23, :2121:19, :2129:24, :2147:19
      end
      if (io_compare_write_commit_0)	// src/main/scala/Design.scala:2100:24, :2116:24, :2117:24
        _csr_value2 <= _csr_value2 & ~_csr_n86 | io_wdata & _csr_n86;	// src/main/scala/Design.scala:1870:28, :2030:24, :2034:24, :2038:24, :2108:24, :2110:24, :2111:24, :2112:24
      _csr_value3 <=
        _csr_n105
        & ~(_csr_n131_T & _csr_n123_T & io_write & _csr_n86[0]
              ? io_wdata & {31'h0, _csr_n86[0]}
              : 32'h0) | {31'h0, io_match_bits[0]};	// src/main/scala/Design.scala:1871:28, :2015:28, :2030:24, :2034:24, :2038:24, :2126:28, :2129:24, :2130:25, :2134:25, :2138:25, :2142:26, :2143:26, :2150:19, :2152:26, :2153:26, :2154:30, :2155:26
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:1833:7, :2013:22
  assign io_rsp_valid = _csr_pending;	// src/main/scala/Design.scala:1833:7, :1867:29
  assign io_rdata = _csr_data;	// src/main/scala/Design.scala:1833:7, :1868:26
  assign io_error = _csr_error;	// src/main/scala/Design.scala:1833:7, :1869:27
  assign io_ctrl_write_commit = _csr_n131_T & _csr_n54_T & io_write & (|(_csr_n86[1:0]));	// src/main/scala/Design.scala:1833:7, :2015:28, :2030:24, :2034:24, :2038:24, :2042:23, :2043:24, :2047:24, :2048:24, :2059:24, :2060:24
  assign io_ctrl_candidate =
    _csr_n32 & {30'h3FFFFFFF, ~(_csr_n86[1:0])} | io_wdata & {30'h0, _csr_n86[1:0]};	// src/main/scala/Design.scala:1833:7, :2030:24, :2034:24, :2038:24, :2040:29, :2047:24, :2051:24, :2053:24, :2054:24, :2055:24
  assign io_count_write_commit = _csr_n131_T & _csr_n78_T & io_write & (|_csr_n86);	// src/main/scala/Design.scala:1833:7, :2015:28, :2030:24, :2034:24, :2038:24, :2070:23, :2071:24, :2076:24, :2087:24, :2088:24
  assign io_count_candidate = io_count_value & ~_csr_n86 | io_wdata & _csr_n86;	// src/main/scala/Design.scala:1833:7, :2030:24, :2034:24, :2038:24, :2079:24, :2081:24, :2082:24, :2083:24
  assign io_compare_write_commit = io_compare_write_commit_0;	// src/main/scala/Design.scala:1833:7, :2100:24, :2116:24, :2117:24
  assign io_compare_value = _csr_value2;	// src/main/scala/Design.scala:1833:7, :1870:28
endmodule


// Generated by CIRCT firtool-1.159.0
module Fr198Timer(	// src/main/scala/Design.scala:2165:7
  input         clock,	// src/main/scala/Design.scala:2165:7
                reset,	// src/main/scala/Design.scala:2165:7
                io_req_valid,	// src/main/scala/Design.scala:2166:14
                io_write,	// src/main/scala/Design.scala:2166:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:2166:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:2166:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:2166:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:2166:14
  output        io_req_ready,	// src/main/scala/Design.scala:2166:14
                io_rsp_valid,	// src/main/scala/Design.scala:2166:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:2166:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:2166:14
  output        io_match_event	// src/main/scala/Design.scala:2166:14
);

  wire        _csr_io_ctrl_write_commit;	// src/main/scala/Design.scala:2223:19
  wire [31:0] _csr_io_ctrl_candidate;	// src/main/scala/Design.scala:2223:19
  wire        _csr_io_count_write_commit;	// src/main/scala/Design.scala:2223:19
  wire [31:0] _csr_io_count_candidate;	// src/main/scala/Design.scala:2223:19
  wire        _csr_io_compare_write_commit;	// src/main/scala/Design.scala:2223:19
  wire [31:0] _csr_io_compare_value;	// src/main/scala/Design.scala:2223:19
  reg  [31:0] ctrl_value;	// src/main/scala/Design.scala:2179:27
  reg  [31:0] count_value;	// src/main/scala/Design.scala:2180:28
  wire        advance =
    ctrl_value[0] & ~reset
    & ~(_csr_io_ctrl_write_commit | _csr_io_count_write_commit
        | _csr_io_compare_write_commit);	// src/main/scala/Design.scala:2179:27, :2223:19, :2259:33, :2260:24, :2263:33, :2264:28, :2265:28, :2266:22, :2267:22
  wire [31:0] _increment_T = count_value + 32'h1;	// src/main/scala/Design.scala:2180:28, :2268:28
  wire        io_match_event_0 = advance & _increment_T == _csr_io_compare_value;	// src/main/scala/Design.scala:2223:19, :2266:22, :2267:22, :2268:28, :2269:22, :2270:29
  always @(posedge clock) begin	// src/main/scala/Design.scala:2165:7
    if (reset) begin	// src/main/scala/Design.scala:2165:7
      ctrl_value <= 32'h0;	// src/main/scala/Design.scala:2179:27
      count_value <= 32'h0;	// src/main/scala/Design.scala:2180:28
    end
    else begin	// src/main/scala/Design.scala:2165:7
      if (_csr_io_ctrl_write_commit)	// src/main/scala/Design.scala:2223:19
        ctrl_value <= _csr_io_ctrl_candidate;	// src/main/scala/Design.scala:2179:27, :2223:19
      else if (io_match_event_0 & ~(ctrl_value[1]))	// src/main/scala/Design.scala:2179:27, :2261:25, :2262:28, :2270:29, :2273:26
        ctrl_value <= {30'h0, ctrl_value[1], 1'h0};	// src/main/scala/Design.scala:2179:27, :2274:30
      if (_csr_io_count_write_commit)	// src/main/scala/Design.scala:2223:19
        count_value <= _csr_io_count_candidate;	// src/main/scala/Design.scala:2180:28, :2223:19
      else if (advance)	// src/main/scala/Design.scala:2266:22, :2267:22
        count_value <= io_match_event_0 & ctrl_value[1] ? 32'h0 : _increment_T;	// src/main/scala/Design.scala:2179:27, :2180:28, :2261:25, :2268:28, :2270:29, :2272:29, :2277:20
    end
  end // always @(posedge)
  BitloomTimerCsr csr (	// src/main/scala/Design.scala:2223:19
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid),
    .io_write                (io_write),
    .io_addr                 (io_addr),
    .io_wdata                (io_wdata),
    .io_wstrb                (io_wstrb),
    .io_rsp_ready            (io_rsp_ready),
    .io_req_ready            (io_req_ready),
    .io_rsp_valid            (io_rsp_valid),
    .io_rdata                (io_rdata),
    .io_error                (io_error),
    .io_ctrl_write_commit    (_csr_io_ctrl_write_commit),
    .io_ctrl_value           (ctrl_value),	// src/main/scala/Design.scala:2179:27
    .io_ctrl_candidate       (_csr_io_ctrl_candidate),
    .io_count_write_commit   (_csr_io_count_write_commit),
    .io_count_value          (count_value),	// src/main/scala/Design.scala:2180:28
    .io_count_candidate      (_csr_io_count_candidate),
    .io_compare_write_commit (_csr_io_compare_write_commit),
    .io_compare_value        (_csr_io_compare_value),
    .io_match_bits           ({31'h0, io_match_event_0})	// src/main/scala/Design.scala:2270:29, :2271:20
  );	// src/main/scala/Design.scala:2223:19
  assign io_match_event = io_match_event_0;	// src/main/scala/Design.scala:2165:7, :2270:29
endmodule


// Generated by CIRCT firtool-1.159.0
module BitloomIrqCsr(	// src/main/scala/Design.scala:2284:7
  input         clock,	// src/main/scala/Design.scala:2284:7
                reset,	// src/main/scala/Design.scala:2284:7
                io_req_valid,	// src/main/scala/Design.scala:2285:14
                io_write,	// src/main/scala/Design.scala:2285:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:2285:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:2285:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:2285:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:2285:14
  output        io_req_ready,	// src/main/scala/Design.scala:2285:14
                io_rsp_valid,	// src/main/scala/Design.scala:2285:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:2285:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:2285:14
  output [31:0] io_pending_value,	// src/main/scala/Design.scala:2285:14
  input  [31:0] io_event_bits,	// src/main/scala/Design.scala:2285:14
  output [31:0] io_enable_value,	// src/main/scala/Design.scala:2285:14
  output        io_test_write_commit,	// src/main/scala/Design.scala:2285:14
  output [31:0] io_test_candidate,	// src/main/scala/Design.scala:2285:14
  input  [31:0] io_raw_value	// src/main/scala/Design.scala:2285:14
);

  reg         _csr_pending;	// src/main/scala/Design.scala:2315:29
  reg  [31:0] _csr_data;	// src/main/scala/Design.scala:2316:26
  reg  [1:0]  _csr_error;	// src/main/scala/Design.scala:2317:27
  reg  [31:0] _csr_value0;	// src/main/scala/Design.scala:2318:28
  reg  [31:0] _csr_value1;	// src/main/scala/Design.scala:2319:28
  wire        io_req_ready_0 = ~_csr_pending & ~reset;	// src/main/scala/Design.scala:2315:29, :2441:27, :2443:34, :2444:22
  wire        _csr_n114_T = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:2444:22, :2446:28
  wire [4:0]  _csr_n18 = {5{io_wstrb[0]}};	// src/main/scala/Design.scala:2454:23, :2456:18
  wire [31:0] io_pending_value_0 = {27'h0, _csr_value0[4:0]};	// src/main/scala/Design.scala:2318:28, :2471:27
  wire [31:0] io_enable_value_0 = {27'h0, _csr_value1[4:0]};	// src/main/scala/Design.scala:2319:28, :2502:27
  wire        _csr_n100_T = io_addr == 16'h8;	// src/main/scala/Design.scala:2532:12, :2533:23
  wire        _csr_n112_T = io_addr == 16'hC;	// src/main/scala/Design.scala:2556:13, :2557:24
  wire        _csr_n50_T = io_addr == 16'h0;	// src/main/scala/Design.scala:2474:23
  wire        _csr_n80_T = io_addr == 16'h4;	// src/main/scala/Design.scala:2504:12, :2505:23
  always @(posedge clock) begin	// src/main/scala/Design.scala:2284:7
    if (reset) begin	// src/main/scala/Design.scala:2284:7
      _csr_pending <= 1'h0;	// src/main/scala/Design.scala:2315:29
      _csr_data <= 32'h0;	// src/main/scala/Design.scala:2316:26
      _csr_error <= 2'h0;	// src/main/scala/Design.scala:2317:27
      _csr_value0 <= 32'h0;	// src/main/scala/Design.scala:2318:28
      _csr_value1 <= 32'h0;	// src/main/scala/Design.scala:2319:28
    end
    else begin	// src/main/scala/Design.scala:2284:7
      _csr_pending <= _csr_n114_T | ~io_rsp_ready & _csr_pending;	// src/main/scala/Design.scala:2315:29, :2446:28, :2449:18, :2450:18
      if (_csr_n114_T) begin	// src/main/scala/Design.scala:2446:28
        _csr_data <=
          _csr_n112_T
            ? (io_write ? 32'h0 : {27'h0, io_raw_value[4:0]})
            : _csr_n100_T
                ? 32'h0
                : _csr_n80_T
                    ? (io_write ? 32'h0 : io_enable_value_0)
                    : _csr_n50_T & ~io_write ? io_pending_value_0 : 32'h0;	// src/main/scala/Design.scala:2316:26, :2448:24, :2471:27, :2474:23, :2493:18, :2494:18, :2502:27, :2505:23, :2528:18, :2529:18, :2533:23, :2553:19, :2555:29, :2557:24, :2566:19, :2567:19
        _csr_error <=
          _csr_n112_T
            ? {io_write, 1'h0}
            : _csr_n100_T ? {~io_write, 1'h0} : _csr_n80_T ? 2'h0 : {~_csr_n50_T, 1'h0};	// src/main/scala/Design.scala:2317:27, :2474:23, :2491:18, :2492:18, :2505:23, :2527:18, :2533:23, :2550:18, :2551:18, :2557:24, :2564:19, :2565:19
      end
      _csr_value0 <=
        io_pending_value_0
        & ~(_csr_n114_T & _csr_n50_T & io_write & io_wstrb[0]
              ? io_wdata & {27'h0, _csr_n18}
              : 32'h0) | {27'h0, io_event_bits[4:0]};	// src/main/scala/Design.scala:2318:28, :2446:28, :2454:23, :2456:18, :2471:27, :2474:23, :2475:24, :2479:24, :2483:24, :2487:24, :2488:24, :2495:18, :2497:24, :2498:24, :2499:29, :2500:24
      _csr_value1 <=
        _csr_n114_T & _csr_n80_T & io_write & io_wstrb[0]
          ? io_enable_value_0 & {27'h7FFFFFF, ~_csr_n18} | io_wdata & {27'h0, _csr_n18}
          : io_enable_value_0;	// src/main/scala/Design.scala:2319:28, :2446:28, :2454:23, :2456:18, :2502:27, :2505:23, :2506:24, :2510:24, :2514:24, :2516:24, :2517:24, :2518:24, :2522:24, :2523:24, :2530:18
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:2284:7, :2444:22
  assign io_rsp_valid = _csr_pending;	// src/main/scala/Design.scala:2284:7, :2315:29
  assign io_rdata = _csr_data;	// src/main/scala/Design.scala:2284:7, :2316:26
  assign io_error = _csr_error;	// src/main/scala/Design.scala:2284:7, :2317:27
  assign io_pending_value = io_pending_value_0;	// src/main/scala/Design.scala:2284:7, :2471:27
  assign io_enable_value = io_enable_value_0;	// src/main/scala/Design.scala:2284:7, :2502:27
  assign io_test_write_commit = _csr_n114_T & _csr_n100_T & io_write & io_wstrb[0];	// src/main/scala/Design.scala:2284:7, :2446:28, :2454:23, :2533:23, :2534:24, :2546:24, :2547:24
  assign io_test_candidate = io_wdata & {27'h0, _csr_n18};	// src/main/scala/Design.scala:2284:7, :2456:18, :2538:24, :2542:24
endmodule


// Generated by CIRCT firtool-1.159.0
module Fr198Irq(	// src/main/scala/Design.scala:2577:7
  input         clock,	// src/main/scala/Design.scala:2577:7
                reset,	// src/main/scala/Design.scala:2577:7
                io_req_valid,	// src/main/scala/Design.scala:2578:14
                io_write,	// src/main/scala/Design.scala:2578:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:2578:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:2578:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:2578:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:2578:14
  output        io_req_ready,	// src/main/scala/Design.scala:2578:14
                io_rsp_valid,	// src/main/scala/Design.scala:2578:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:2578:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:2578:14
  input  [4:0]  io_raw_events,	// src/main/scala/Design.scala:2578:14
  output        io_irq	// src/main/scala/Design.scala:2578:14
);

  wire [31:0] _csr_io_pending_value;	// src/main/scala/Design.scala:2616:19
  wire [31:0] _csr_io_enable_value;	// src/main/scala/Design.scala:2616:19
  wire        _csr_io_test_write_commit;	// src/main/scala/Design.scala:2616:19
  wire [31:0] _csr_io_test_candidate;	// src/main/scala/Design.scala:2616:19
  wire [31:0] raw_value = {27'h0, io_raw_events};	// src/main/scala/Design.scala:2646:10, :2648:32
  BitloomIrqCsr csr (	// src/main/scala/Design.scala:2616:19
    .clock                (clock),
    .reset                (reset),
    .io_req_valid         (io_req_valid),
    .io_write             (io_write),
    .io_addr              (io_addr),
    .io_wdata             (io_wdata),
    .io_wstrb             (io_wstrb),
    .io_rsp_ready         (io_rsp_ready),
    .io_req_ready         (io_req_ready),
    .io_rsp_valid         (io_rsp_valid),
    .io_rdata             (io_rdata),
    .io_error             (io_error),
    .io_pending_value     (_csr_io_pending_value),
    .io_event_bits
      (raw_value | (_csr_io_test_write_commit ? _csr_io_test_candidate : 32'h0)),	// src/main/scala/Design.scala:2616:19, :2645:10, :2648:32, :2649:19, :2650:27
    .io_enable_value      (_csr_io_enable_value),
    .io_test_write_commit (_csr_io_test_write_commit),
    .io_test_candidate    (_csr_io_test_candidate),
    .io_raw_value         (raw_value)	// src/main/scala/Design.scala:2648:32
  );	// src/main/scala/Design.scala:2616:19
  assign io_irq = |(_csr_io_pending_value & _csr_io_enable_value);	// src/main/scala/Design.scala:2577:7, :2616:19, :2651:27, :2652:19
endmodule


// Generated by CIRCT firtool-1.159.0
module Fr198Bridge(	// src/main/scala/Design.scala:7:7
  input         clock,	// src/main/scala/Design.scala:7:7
                reset,	// src/main/scala/Design.scala:7:7
  input  [15:0] io_s_axi_awaddr,	// src/main/scala/Design.scala:8:14
  input         io_s_axi_awvalid,	// src/main/scala/Design.scala:8:14
  input  [31:0] io_s_axi_wdata,	// src/main/scala/Design.scala:8:14
  input  [3:0]  io_s_axi_wstrb,	// src/main/scala/Design.scala:8:14
  input         io_s_axi_wvalid,	// src/main/scala/Design.scala:8:14
                io_s_axi_bready,	// src/main/scala/Design.scala:8:14
  input  [15:0] io_s_axi_araddr,	// src/main/scala/Design.scala:8:14
  input         io_s_axi_arvalid,	// src/main/scala/Design.scala:8:14
                io_s_axi_rready,	// src/main/scala/Design.scala:8:14
                io_csr_req_ready,	// src/main/scala/Design.scala:8:14
                io_csr_rsp_valid,	// src/main/scala/Design.scala:8:14
  input  [31:0] io_csr_rdata,	// src/main/scala/Design.scala:8:14
  input  [1:0]  io_csr_error,	// src/main/scala/Design.scala:8:14
  output        io_s_axi_awready,	// src/main/scala/Design.scala:8:14
                io_s_axi_wready,	// src/main/scala/Design.scala:8:14
                io_s_axi_arready,	// src/main/scala/Design.scala:8:14
                io_s_axi_bvalid,	// src/main/scala/Design.scala:8:14
  output [1:0]  io_s_axi_bresp,	// src/main/scala/Design.scala:8:14
  output        io_s_axi_rvalid,	// src/main/scala/Design.scala:8:14
  output [31:0] io_s_axi_rdata,	// src/main/scala/Design.scala:8:14
  output [1:0]  io_s_axi_rresp,	// src/main/scala/Design.scala:8:14
  output        io_csr_req_valid,	// src/main/scala/Design.scala:8:14
                io_csr_write,	// src/main/scala/Design.scala:8:14
  output [15:0] io_csr_addr,	// src/main/scala/Design.scala:8:14
  output [31:0] io_csr_wdata,	// src/main/scala/Design.scala:8:14
  output [3:0]  io_csr_wstrb,	// src/main/scala/Design.scala:8:14
  output        io_csr_rsp_ready	// src/main/scala/Design.scala:8:14
);

  reg         aw_full;	// src/main/scala/Design.scala:39:24
  reg         w_full;	// src/main/scala/Design.scala:40:23
  reg         ar_full;	// src/main/scala/Design.scala:41:24
  reg  [15:0] aw_addr;	// src/main/scala/Design.scala:42:24
  reg  [31:0] w_data;	// src/main/scala/Design.scala:43:23
  reg  [3:0]  w_strb;	// src/main/scala/Design.scala:44:23
  reg  [15:0] ar_addr;	// src/main/scala/Design.scala:45:24
  reg         offer;	// src/main/scala/Design.scala:46:22
  reg         offer_write;	// src/main/scala/Design.scala:47:28
  reg         exec;	// src/main/scala/Design.scala:48:21
  reg         owner;	// src/main/scala/Design.scala:49:22
  reg         prefer_write;	// src/main/scala/Design.scala:50:29
  reg         b_full;	// src/main/scala/Design.scala:51:23
  reg         r_full;	// src/main/scala/Design.scala:52:23
  reg  [1:0]  b_error;	// src/main/scala/Design.scala:53:24
  reg  [1:0]  r_error;	// src/main/scala/Design.scala:54:24
  reg  [31:0] r_data;	// src/main/scala/Design.scala:55:23
  reg  [31:0] offer_data;	// src/main/scala/Design.scala:56:27
  reg  [3:0]  offer_strb;	// src/main/scala/Design.scala:57:27
  wire        io_csr_req_valid_0 = offer & ~reset;	// src/main/scala/Design.scala:46:22, :109:33, :123:29
  wire        io_csr_rsp_ready_0 = exec & ~reset;	// src/main/scala/Design.scala:48:21, :109:33, :128:28
  wire        aw_take = ~aw_full & io_s_axi_awvalid;	// src/main/scala/Design.scala:39:24, :103:31, :104:31
  wire        w_take = ~w_full & io_s_axi_wvalid;	// src/main/scala/Design.scala:40:23, :105:29, :106:29
  wire        ar_take = ~ar_full & io_s_axi_arvalid;	// src/main/scala/Design.scala:41:24, :107:31, :108:31
  wire        we = aw_full & w_full & ~b_full;	// src/main/scala/Design.scala:39:24, :40:23, :51:23, :113:21, :115:29, :116:24
  wire        re = ar_full & ~r_full;	// src/main/scala/Design.scala:41:24, :52:23, :114:21, :117:17
  wire        select = ~offer & ~exec & (we | re);	// src/main/scala/Design.scala:46:22, :48:21, :110:21, :111:19, :112:20, :115:29, :116:24, :117:17, :118:18, :119:18
  wire        commit = io_csr_req_valid_0 & io_csr_req_ready;	// src/main/scala/Design.scala:123:29, :124:30
  wire        write_commit = commit & offer_write;	// src/main/scala/Design.scala:47:28, :124:30, :126:26
  wire        response = io_csr_rsp_ready_0 & io_csr_rsp_valid;	// src/main/scala/Design.scala:128:28, :129:32
  wire        write_response = response & owner;	// src/main/scala/Design.scala:49:22, :129:32, :130:30
  wire        read_response = response & ~owner;	// src/main/scala/Design.scala:49:22, :129:32, :131:23, :132:29
  always @(posedge clock) begin	// src/main/scala/Design.scala:7:7
    if (reset) begin	// src/main/scala/Design.scala:7:7
      aw_full <= 1'h0;	// src/main/scala/Design.scala:39:24
      w_full <= 1'h0;	// src/main/scala/Design.scala:39:24, :40:23
      ar_full <= 1'h0;	// src/main/scala/Design.scala:39:24, :41:24
      aw_addr <= 16'h0;	// src/main/scala/Design.scala:42:24
      w_data <= 32'h0;	// src/main/scala/Design.scala:43:23
      w_strb <= 4'h0;	// src/main/scala/Design.scala:44:23
      ar_addr <= 16'h0;	// src/main/scala/Design.scala:42:24, :45:24
      offer <= 1'h0;	// src/main/scala/Design.scala:39:24, :46:22
      offer_write <= 1'h0;	// src/main/scala/Design.scala:39:24, :47:28
      exec <= 1'h0;	// src/main/scala/Design.scala:39:24, :48:21
      owner <= 1'h0;	// src/main/scala/Design.scala:39:24, :49:22
      prefer_write <= 1'h0;	// src/main/scala/Design.scala:39:24, :50:29
      b_full <= 1'h0;	// src/main/scala/Design.scala:39:24, :51:23
      r_full <= 1'h0;	// src/main/scala/Design.scala:39:24, :52:23
      b_error <= 2'h0;	// src/main/scala/Design.scala:53:24
      r_error <= 2'h0;	// src/main/scala/Design.scala:53:24, :54:24
      r_data <= 32'h0;	// src/main/scala/Design.scala:43:23, :55:23
      offer_data <= 32'h0;	// src/main/scala/Design.scala:43:23, :56:27
      offer_strb <= 4'h0;	// src/main/scala/Design.scala:44:23, :57:27
    end
    else begin	// src/main/scala/Design.scala:7:7
      aw_full <= ~write_commit & (aw_take | aw_full);	// src/main/scala/Design.scala:39:24, :104:31, :126:26, :135:21, :136:17
      w_full <= ~write_commit & (w_take | w_full);	// src/main/scala/Design.scala:40:23, :106:29, :126:26, :136:17, :137:20, :138:16
      ar_full <= ~(commit & ~offer_write) & (ar_take | ar_full);	// src/main/scala/Design.scala:41:24, :47:28, :108:31, :124:30, :125:29, :127:25, :139:21, :140:17
      if (aw_take)	// src/main/scala/Design.scala:104:31
        aw_addr <= io_s_axi_awaddr;	// src/main/scala/Design.scala:42:24
      if (w_take) begin	// src/main/scala/Design.scala:106:29
        w_data <= io_s_axi_wdata;	// src/main/scala/Design.scala:43:23
        w_strb <= io_s_axi_wstrb;	// src/main/scala/Design.scala:44:23
      end
      if (ar_take)	// src/main/scala/Design.scala:108:31
        ar_addr <= io_s_axi_araddr;	// src/main/scala/Design.scala:45:24
      offer <= ~commit & (select | offer);	// src/main/scala/Design.scala:46:22, :112:20, :119:18, :124:30, :141:23, :142:20
      if (select) begin	// src/main/scala/Design.scala:112:20, :119:18
        offer_write <= we & (prefer_write | ~re);	// src/main/scala/Design.scala:47:28, :50:29, :115:29, :116:24, :117:17, :120:17, :121:35, :122:22
        offer_data <= w_data;	// src/main/scala/Design.scala:43:23, :56:27
        offer_strb <= w_strb;	// src/main/scala/Design.scala:44:23, :57:27
      end
      exec <= ~response & (commit | exec);	// src/main/scala/Design.scala:48:21, :124:30, :129:32, :143:22, :144:19
      if (commit) begin	// src/main/scala/Design.scala:124:30
        owner <= offer_write;	// src/main/scala/Design.scala:47:28, :49:22
        prefer_write <= ~offer_write;	// src/main/scala/Design.scala:47:28, :50:29, :125:29
      end
      b_full <= write_response | ~(b_full & io_s_axi_bready) & b_full;	// src/main/scala/Design.scala:51:23, :130:30, :133:20, :145:20, :146:16
      r_full <= read_response | ~(r_full & io_s_axi_rready) & r_full;	// src/main/scala/Design.scala:52:23, :132:29, :134:20, :147:20, :148:16
      if (write_response)	// src/main/scala/Design.scala:130:30
        b_error <= io_csr_error;	// src/main/scala/Design.scala:53:24
      if (read_response) begin	// src/main/scala/Design.scala:132:29
        r_error <= io_csr_error;	// src/main/scala/Design.scala:54:24
        r_data <= io_csr_rdata;	// src/main/scala/Design.scala:55:23
      end
    end
  end // always @(posedge)
  assign io_s_axi_awready = ~aw_full;	// src/main/scala/Design.scala:7:7, :39:24, :103:31
  assign io_s_axi_wready = ~w_full;	// src/main/scala/Design.scala:7:7, :40:23, :105:29
  assign io_s_axi_arready = ~ar_full;	// src/main/scala/Design.scala:7:7, :41:24, :107:31
  assign io_s_axi_bvalid = b_full;	// src/main/scala/Design.scala:7:7, :51:23
  assign io_s_axi_bresp = b_error;	// src/main/scala/Design.scala:7:7, :53:24
  assign io_s_axi_rvalid = r_full;	// src/main/scala/Design.scala:7:7, :52:23
  assign io_s_axi_rdata = r_data;	// src/main/scala/Design.scala:7:7, :55:23
  assign io_s_axi_rresp = r_error;	// src/main/scala/Design.scala:7:7, :54:24
  assign io_csr_req_valid = io_csr_req_valid_0;	// src/main/scala/Design.scala:7:7, :123:29
  assign io_csr_write = offer_write;	// src/main/scala/Design.scala:7:7, :47:28
  assign io_csr_addr = offer_write ? aw_addr : ar_addr;	// src/main/scala/Design.scala:7:7, :42:24, :45:24, :47:28, :149:21
  assign io_csr_wdata = offer_data;	// src/main/scala/Design.scala:7:7, :56:27
  assign io_csr_wstrb = offer_strb;	// src/main/scala/Design.scala:7:7, :57:27
  assign io_csr_rsp_ready = io_csr_rsp_ready_0;	// src/main/scala/Design.scala:7:7, :128:28
endmodule


// Generated by CIRCT firtool-1.159.0
module Fr198Decoder(	// src/main/scala/Design.scala:179:7
  input         clock,	// src/main/scala/Design.scala:179:7
                reset,	// src/main/scala/Design.scala:179:7
                io_req_valid,	// src/main/scala/Design.scala:180:14
                io_write,	// src/main/scala/Design.scala:180:14
  input  [15:0] io_addr,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_wdata,	// src/main/scala/Design.scala:180:14
  input  [3:0]  io_wstrb,	// src/main/scala/Design.scala:180:14
  input         io_rsp_ready,	// src/main/scala/Design.scala:180:14
  output        io_req_ready,	// src/main/scala/Design.scala:180:14
                io_rsp_valid,	// src/main/scala/Design.scala:180:14
  output [31:0] io_rdata,	// src/main/scala/Design.scala:180:14
  output [1:0]  io_error,	// src/main/scala/Design.scala:180:14
  input         io_uart_req_ready,	// src/main/scala/Design.scala:180:14
                io_uart_rsp_valid,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_uart_rdata,	// src/main/scala/Design.scala:180:14
  input  [1:0]  io_uart_error,	// src/main/scala/Design.scala:180:14
  output        io_uart_req_valid,	// src/main/scala/Design.scala:180:14
                io_uart_write,	// src/main/scala/Design.scala:180:14
  output [15:0] io_uart_addr,	// src/main/scala/Design.scala:180:14
  output [31:0] io_uart_wdata,	// src/main/scala/Design.scala:180:14
  output [3:0]  io_uart_wstrb,	// src/main/scala/Design.scala:180:14
  output        io_uart_rsp_ready,	// src/main/scala/Design.scala:180:14
  input         io_gpio_req_ready,	// src/main/scala/Design.scala:180:14
                io_gpio_rsp_valid,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_gpio_rdata,	// src/main/scala/Design.scala:180:14
  input  [1:0]  io_gpio_error,	// src/main/scala/Design.scala:180:14
  output        io_gpio_req_valid,	// src/main/scala/Design.scala:180:14
                io_gpio_write,	// src/main/scala/Design.scala:180:14
  output [15:0] io_gpio_addr,	// src/main/scala/Design.scala:180:14
  output [31:0] io_gpio_wdata,	// src/main/scala/Design.scala:180:14
  output [3:0]  io_gpio_wstrb,	// src/main/scala/Design.scala:180:14
  output        io_gpio_rsp_ready,	// src/main/scala/Design.scala:180:14
  input         io_timer_req_ready,	// src/main/scala/Design.scala:180:14
                io_timer_rsp_valid,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_timer_rdata,	// src/main/scala/Design.scala:180:14
  input  [1:0]  io_timer_error,	// src/main/scala/Design.scala:180:14
  output        io_timer_req_valid,	// src/main/scala/Design.scala:180:14
                io_timer_write,	// src/main/scala/Design.scala:180:14
  output [15:0] io_timer_addr,	// src/main/scala/Design.scala:180:14
  output [31:0] io_timer_wdata,	// src/main/scala/Design.scala:180:14
  output [3:0]  io_timer_wstrb,	// src/main/scala/Design.scala:180:14
  output        io_timer_rsp_ready,	// src/main/scala/Design.scala:180:14
  input         io_irq_req_ready,	// src/main/scala/Design.scala:180:14
                io_irq_rsp_valid,	// src/main/scala/Design.scala:180:14
  input  [31:0] io_irq_rdata,	// src/main/scala/Design.scala:180:14
  input  [1:0]  io_irq_error,	// src/main/scala/Design.scala:180:14
  output        io_irq_req_valid,	// src/main/scala/Design.scala:180:14
                io_irq_write,	// src/main/scala/Design.scala:180:14
  output [15:0] io_irq_addr,	// src/main/scala/Design.scala:180:14
  output [31:0] io_irq_wdata,	// src/main/scala/Design.scala:180:14
  output [3:0]  io_irq_wstrb,	// src/main/scala/Design.scala:180:14
  output        io_irq_rsp_ready	// src/main/scala/Design.scala:180:14
);

  reg        busy;	// src/main/scala/Design.scala:232:21
  reg        miss;	// src/main/scala/Design.scala:233:21
  reg  [1:0] owner;	// src/main/scala/Design.scala:234:22
  wire       available = ~busy & ~reset;	// src/main/scala/Design.scala:232:21, :311:33, :312:16, :313:21
  wire       offering = available & io_req_valid;	// src/main/scala/Design.scala:313:21, :314:25
  wire       leaf_owned = busy & ~miss;	// src/main/scala/Design.scala:232:21, :233:21, :315:20, :316:22
  wire       ready_active = io_rsp_ready & ~reset;	// src/main/scala/Design.scala:311:33, :317:32
  wire       valid_0 = busy & miss;	// src/main/scala/Design.scala:232:21, :233:21, :318:22
  wire       hit_1 = io_addr[15:8] == 8'h0;	// src/main/scala/Design.scala:309:18, :327:20
  wire       uart_owned = leaf_owned & owner == 2'h0;	// src/main/scala/Design.scala:234:22, :316:22, :335:26, :336:28
  wire       gpio_hit = io_addr[15:8] == 8'h1;	// src/main/scala/Design.scala:309:18, :341:13, :344:20
  wire       gpio_owned = leaf_owned & owner == 2'h1;	// src/main/scala/Design.scala:234:22, :316:22, :343:11, :352:26, :353:28
  wire       timer_hit = io_addr[15:8] == 8'h2;	// src/main/scala/Design.scala:309:18, :358:14, :361:21
  wire       timer_owned = leaf_owned & owner == 2'h2;	// src/main/scala/Design.scala:234:22, :316:22, :358:14, :369:27, :370:29
  wire       irq_hit = io_addr[15:8] == 8'h3;	// src/main/scala/Design.scala:309:18, :375:12, :378:19
  wire       irq_owned = leaf_owned & (&owner);	// src/main/scala/Design.scala:234:22, :316:22, :386:25, :387:27
  wire       valid_4 =
    irq_owned
      ? io_irq_rsp_valid
      : timer_owned
          ? io_timer_rsp_valid
          : gpio_owned ? io_gpio_rsp_valid : uart_owned ? io_uart_rsp_valid : valid_0;	// src/main/scala/Design.scala:318:22, :336:28, :338:17, :353:28, :355:17, :370:29, :372:17, :387:27, :389:17
  wire       io_req_ready_0 =
    available
    & (irq_hit
         ? io_irq_req_ready
         : timer_hit
             ? io_timer_req_ready
             : gpio_hit ? io_gpio_req_ready : ~hit_1 | io_uart_req_ready);	// src/main/scala/Design.scala:313:21, :327:20, :329:17, :344:20, :346:17, :361:21, :363:17, :378:19, :380:17, :393:29
  wire       commit = io_req_valid & io_req_ready_0;	// src/main/scala/Design.scala:393:29, :397:26
  always @(posedge clock) begin	// src/main/scala/Design.scala:179:7
    if (reset) begin	// src/main/scala/Design.scala:179:7
      busy <= 1'h0;	// src/main/scala/Design.scala:232:21
      miss <= 1'h0;	// src/main/scala/Design.scala:232:21, :233:21
      owner <= 2'h0;	// src/main/scala/Design.scala:234:22
    end
    else begin	// src/main/scala/Design.scala:179:7
      busy <= ~(valid_4 & ready_active) & (busy | commit);	// src/main/scala/Design.scala:232:21, :317:32, :389:17, :397:26, :398:27, :399:24, :400:19
      if (commit) begin	// src/main/scala/Design.scala:397:26
        miss <= ~(hit_1 | gpio_hit | timer_hit | irq_hit);	// src/main/scala/Design.scala:233:21, :327:20, :344:20, :345:18, :361:21, :362:18, :378:19, :379:18, :392:19
        owner <= io_addr[9:8];	// src/main/scala/Design.scala:234:22, :310:26
      end
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// src/main/scala/Design.scala:179:7, :393:29
  assign io_rsp_valid = valid_4;	// src/main/scala/Design.scala:179:7, :389:17
  assign io_rdata =
    irq_owned
      ? io_irq_rdata
      : timer_owned
          ? io_timer_rdata
          : gpio_owned ? io_gpio_rdata : uart_owned ? io_uart_rdata : 32'h0;	// src/main/scala/Design.scala:179:7, :306:10, :336:28, :339:16, :353:28, :356:16, :370:29, :373:16, :387:27, :390:16
  assign io_error =
    irq_owned
      ? io_irq_error
      : timer_owned
          ? io_timer_error
          : gpio_owned ? io_gpio_error : uart_owned ? io_uart_error : {2{valid_0}};	// src/main/scala/Design.scala:179:7, :318:22, :323:17, :336:28, :340:17, :353:28, :357:17, :370:29, :374:17, :387:27, :391:17
  assign io_uart_req_valid = offering & hit_1;	// src/main/scala/Design.scala:179:7, :314:25, :327:20, :330:33
  assign io_uart_write = io_write;	// src/main/scala/Design.scala:179:7
  assign io_uart_addr = io_addr;	// src/main/scala/Design.scala:179:7
  assign io_uart_wdata = io_wdata;	// src/main/scala/Design.scala:179:7
  assign io_uart_wstrb = io_wstrb;	// src/main/scala/Design.scala:179:7
  assign io_uart_rsp_ready = uart_owned & ready_active;	// src/main/scala/Design.scala:179:7, :317:32, :336:28, :337:35
  assign io_gpio_req_valid = offering & gpio_hit;	// src/main/scala/Design.scala:179:7, :314:25, :344:20, :347:33
  assign io_gpio_write = io_write;	// src/main/scala/Design.scala:179:7
  assign io_gpio_addr = io_addr - 16'h100;	// src/main/scala/Design.scala:179:7, :348:27
  assign io_gpio_wdata = io_wdata;	// src/main/scala/Design.scala:179:7
  assign io_gpio_wstrb = io_wstrb;	// src/main/scala/Design.scala:179:7
  assign io_gpio_rsp_ready = gpio_owned & ready_active;	// src/main/scala/Design.scala:179:7, :317:32, :353:28, :354:35
  assign io_timer_req_valid = offering & timer_hit;	// src/main/scala/Design.scala:179:7, :314:25, :361:21, :364:34
  assign io_timer_write = io_write;	// src/main/scala/Design.scala:179:7
  assign io_timer_addr = io_addr - 16'h200;	// src/main/scala/Design.scala:179:7, :365:28
  assign io_timer_wdata = io_wdata;	// src/main/scala/Design.scala:179:7
  assign io_timer_wstrb = io_wstrb;	// src/main/scala/Design.scala:179:7
  assign io_timer_rsp_ready = timer_owned & ready_active;	// src/main/scala/Design.scala:179:7, :317:32, :370:29, :371:37
  assign io_irq_req_valid = offering & irq_hit;	// src/main/scala/Design.scala:179:7, :314:25, :378:19, :381:32
  assign io_irq_write = io_write;	// src/main/scala/Design.scala:179:7
  assign io_irq_addr = io_addr - 16'h300;	// src/main/scala/Design.scala:179:7, :382:26
  assign io_irq_wdata = io_wdata;	// src/main/scala/Design.scala:179:7
  assign io_irq_wstrb = io_wstrb;	// src/main/scala/Design.scala:179:7
  assign io_irq_rsp_ready = irq_owned & ready_active;	// src/main/scala/Design.scala:179:7, :317:32, :387:27, :388:33
endmodule


// Generated by CIRCT firtool-1.159.0
module Fr198AxiCore(	// src/main/scala/Design.scala:2656:7
  input         clock,	// src/main/scala/Design.scala:2656:7
                reset,	// src/main/scala/Design.scala:2656:7
  input  [15:0] io_axi_s_axi_awaddr,	// src/main/scala/Design.scala:2657:14
  input  [2:0]  io_axi_s_axi_awprot,	// src/main/scala/Design.scala:2657:14
  input         io_axi_s_axi_awvalid,	// src/main/scala/Design.scala:2657:14
  input  [31:0] io_axi_s_axi_wdata,	// src/main/scala/Design.scala:2657:14
  input  [3:0]  io_axi_s_axi_wstrb,	// src/main/scala/Design.scala:2657:14
  input         io_axi_s_axi_wvalid,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_bready,	// src/main/scala/Design.scala:2657:14
  input  [15:0] io_axi_s_axi_araddr,	// src/main/scala/Design.scala:2657:14
  input  [2:0]  io_axi_s_axi_arprot,	// src/main/scala/Design.scala:2657:14
  input         io_axi_s_axi_arvalid,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_rready,	// src/main/scala/Design.scala:2657:14
  output        io_axi_s_axi_awready,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_wready,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_arready,	// src/main/scala/Design.scala:2657:14
                io_axi_s_axi_bvalid,	// src/main/scala/Design.scala:2657:14
  output [1:0]  io_axi_s_axi_bresp,	// src/main/scala/Design.scala:2657:14
  output        io_axi_s_axi_rvalid,	// src/main/scala/Design.scala:2657:14
  output [31:0] io_axi_s_axi_rdata,	// src/main/scala/Design.scala:2657:14
  output [1:0]  io_axi_s_axi_rresp,	// src/main/scala/Design.scala:2657:14
  input         io_u_rx,	// src/main/scala/Design.scala:2657:14
  output        io_u_tx,	// src/main/scala/Design.scala:2657:14
  input  [31:0] io_g_pad_in,	// src/main/scala/Design.scala:2657:14
  output [31:0] io_g_pad_out,	// src/main/scala/Design.scala:2657:14
                io_g_pad_oe,	// src/main/scala/Design.scala:2657:14
  output        io_i_irq	// src/main/scala/Design.scala:2657:14
);

  wire        _decoder_io_req_ready;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_rsp_valid;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_rdata;	// src/main/scala/Design.scala:2881:23
  wire [1:0]  _decoder_io_error;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_uart_req_valid;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_uart_write;	// src/main/scala/Design.scala:2881:23
  wire [15:0] _decoder_io_uart_addr;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_uart_wdata;	// src/main/scala/Design.scala:2881:23
  wire [3:0]  _decoder_io_uart_wstrb;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_uart_rsp_ready;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_gpio_req_valid;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_gpio_write;	// src/main/scala/Design.scala:2881:23
  wire [15:0] _decoder_io_gpio_addr;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_gpio_wdata;	// src/main/scala/Design.scala:2881:23
  wire [3:0]  _decoder_io_gpio_wstrb;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_gpio_rsp_ready;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_timer_req_valid;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_timer_write;	// src/main/scala/Design.scala:2881:23
  wire [15:0] _decoder_io_timer_addr;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_timer_wdata;	// src/main/scala/Design.scala:2881:23
  wire [3:0]  _decoder_io_timer_wstrb;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_timer_rsp_ready;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_irq_req_valid;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_irq_write;	// src/main/scala/Design.scala:2881:23
  wire [15:0] _decoder_io_irq_addr;	// src/main/scala/Design.scala:2881:23
  wire [31:0] _decoder_io_irq_wdata;	// src/main/scala/Design.scala:2881:23
  wire [3:0]  _decoder_io_irq_wstrb;	// src/main/scala/Design.scala:2881:23
  wire        _decoder_io_irq_rsp_ready;	// src/main/scala/Design.scala:2881:23
  wire        _bridge_io_csr_req_valid;	// src/main/scala/Design.scala:2851:22
  wire        _bridge_io_csr_write;	// src/main/scala/Design.scala:2851:22
  wire [15:0] _bridge_io_csr_addr;	// src/main/scala/Design.scala:2851:22
  wire [31:0] _bridge_io_csr_wdata;	// src/main/scala/Design.scala:2851:22
  wire [3:0]  _bridge_io_csr_wstrb;	// src/main/scala/Design.scala:2851:22
  wire        _bridge_io_csr_rsp_ready;	// src/main/scala/Design.scala:2851:22
  wire        _irq_io_req_ready;	// src/main/scala/Design.scala:2838:19
  wire        _irq_io_rsp_valid;	// src/main/scala/Design.scala:2838:19
  wire [31:0] _irq_io_rdata;	// src/main/scala/Design.scala:2838:19
  wire [1:0]  _irq_io_error;	// src/main/scala/Design.scala:2838:19
  wire        _timer_io_req_ready;	// src/main/scala/Design.scala:2826:21
  wire        _timer_io_rsp_valid;	// src/main/scala/Design.scala:2826:21
  wire [31:0] _timer_io_rdata;	// src/main/scala/Design.scala:2826:21
  wire [1:0]  _timer_io_error;	// src/main/scala/Design.scala:2826:21
  wire        _timer_io_match_event;	// src/main/scala/Design.scala:2826:21
  wire        _gpio_io_req_ready;	// src/main/scala/Design.scala:2811:20
  wire        _gpio_io_rsp_valid;	// src/main/scala/Design.scala:2811:20
  wire [31:0] _gpio_io_rdata;	// src/main/scala/Design.scala:2811:20
  wire [1:0]  _gpio_io_error;	// src/main/scala/Design.scala:2811:20
  wire        _gpio_io_raw_event;	// src/main/scala/Design.scala:2811:20
  wire        _uart_io_req_ready;	// src/main/scala/Design.scala:2797:20
  wire        _uart_io_rsp_valid;	// src/main/scala/Design.scala:2797:20
  wire [31:0] _uart_io_rdata;	// src/main/scala/Design.scala:2797:20
  wire [1:0]  _uart_io_error;	// src/main/scala/Design.scala:2797:20
  wire [3:0]  _uart_io_raw_events;	// src/main/scala/Design.scala:2797:20
  Fr198Uart uart (	// src/main/scala/Design.scala:2797:20
    .clock         (clock),
    .reset         (reset),
    .io_req_valid  (_decoder_io_uart_req_valid),	// src/main/scala/Design.scala:2881:23
    .io_write      (_decoder_io_uart_write),	// src/main/scala/Design.scala:2881:23
    .io_addr       (_decoder_io_uart_addr),	// src/main/scala/Design.scala:2881:23
    .io_wdata      (_decoder_io_uart_wdata),	// src/main/scala/Design.scala:2881:23
    .io_wstrb      (_decoder_io_uart_wstrb),	// src/main/scala/Design.scala:2881:23
    .io_rsp_ready  (_decoder_io_uart_rsp_ready),	// src/main/scala/Design.scala:2881:23
    .io_req_ready  (_uart_io_req_ready),
    .io_rsp_valid  (_uart_io_rsp_valid),
    .io_rdata      (_uart_io_rdata),
    .io_error      (_uart_io_error),
    .io_rx         (io_u_rx),
    .io_tx         (io_u_tx),
    .io_raw_events (_uart_io_raw_events)
  );	// src/main/scala/Design.scala:2797:20
  Fr198Gpio gpio (	// src/main/scala/Design.scala:2811:20
    .clock        (clock),
    .reset        (reset),
    .io_req_valid (_decoder_io_gpio_req_valid),	// src/main/scala/Design.scala:2881:23
    .io_write     (_decoder_io_gpio_write),	// src/main/scala/Design.scala:2881:23
    .io_addr      (_decoder_io_gpio_addr),	// src/main/scala/Design.scala:2881:23
    .io_wdata     (_decoder_io_gpio_wdata),	// src/main/scala/Design.scala:2881:23
    .io_wstrb     (_decoder_io_gpio_wstrb),	// src/main/scala/Design.scala:2881:23
    .io_rsp_ready (_decoder_io_gpio_rsp_ready),	// src/main/scala/Design.scala:2881:23
    .io_req_ready (_gpio_io_req_ready),
    .io_rsp_valid (_gpio_io_rsp_valid),
    .io_rdata     (_gpio_io_rdata),
    .io_error     (_gpio_io_error),
    .io_pad_in    (io_g_pad_in),
    .io_pad_out   (io_g_pad_out),
    .io_pad_oe    (io_g_pad_oe),
    .io_raw_event (_gpio_io_raw_event)
  );	// src/main/scala/Design.scala:2811:20
  Fr198Timer timer (	// src/main/scala/Design.scala:2826:21
    .clock          (clock),
    .reset          (reset),
    .io_req_valid   (_decoder_io_timer_req_valid),	// src/main/scala/Design.scala:2881:23
    .io_write       (_decoder_io_timer_write),	// src/main/scala/Design.scala:2881:23
    .io_addr        (_decoder_io_timer_addr),	// src/main/scala/Design.scala:2881:23
    .io_wdata       (_decoder_io_timer_wdata),	// src/main/scala/Design.scala:2881:23
    .io_wstrb       (_decoder_io_timer_wstrb),	// src/main/scala/Design.scala:2881:23
    .io_rsp_ready   (_decoder_io_timer_rsp_ready),	// src/main/scala/Design.scala:2881:23
    .io_req_ready   (_timer_io_req_ready),
    .io_rsp_valid   (_timer_io_rsp_valid),
    .io_rdata       (_timer_io_rdata),
    .io_error       (_timer_io_error),
    .io_match_event (_timer_io_match_event)
  );	// src/main/scala/Design.scala:2826:21
  Fr198Irq irq (	// src/main/scala/Design.scala:2838:19
    .clock         (clock),
    .reset         (reset),
    .io_req_valid  (_decoder_io_irq_req_valid),	// src/main/scala/Design.scala:2881:23
    .io_write      (_decoder_io_irq_write),	// src/main/scala/Design.scala:2881:23
    .io_addr       (_decoder_io_irq_addr),	// src/main/scala/Design.scala:2881:23
    .io_wdata      (_decoder_io_irq_wdata),	// src/main/scala/Design.scala:2881:23
    .io_wstrb      (_decoder_io_irq_wstrb),	// src/main/scala/Design.scala:2881:23
    .io_rsp_ready  (_decoder_io_irq_rsp_ready),	// src/main/scala/Design.scala:2881:23
    .io_req_ready  (_irq_io_req_ready),
    .io_rsp_valid  (_irq_io_rsp_valid),
    .io_rdata      (_irq_io_rdata),
    .io_error      (_irq_io_error),
    .io_raw_events
      ({_gpio_io_raw_event,
        _uart_io_raw_events[2] | _uart_io_raw_events[3],
        _uart_io_raw_events[1:0],
        _timer_io_match_event}),	// src/main/scala/Design.scala:2797:20, :2811:20, :2826:21, :2984:30, :2985:34, :2986:35, :2990:33
    .io_irq        (io_i_irq)
  );	// src/main/scala/Design.scala:2838:19
  Fr198Bridge bridge (	// src/main/scala/Design.scala:2851:22
    .clock            (clock),
    .reset            (reset),
    .io_s_axi_awaddr  (io_axi_s_axi_awaddr),
    .io_s_axi_awvalid (io_axi_s_axi_awvalid),
    .io_s_axi_wdata   (io_axi_s_axi_wdata),
    .io_s_axi_wstrb   (io_axi_s_axi_wstrb),
    .io_s_axi_wvalid  (io_axi_s_axi_wvalid),
    .io_s_axi_bready  (io_axi_s_axi_bready),
    .io_s_axi_araddr  (io_axi_s_axi_araddr),
    .io_s_axi_arvalid (io_axi_s_axi_arvalid),
    .io_s_axi_rready  (io_axi_s_axi_rready),
    .io_csr_req_ready (_decoder_io_req_ready),	// src/main/scala/Design.scala:2881:23
    .io_csr_rsp_valid (_decoder_io_rsp_valid),	// src/main/scala/Design.scala:2881:23
    .io_csr_rdata     (_decoder_io_rdata),	// src/main/scala/Design.scala:2881:23
    .io_csr_error     (_decoder_io_error),	// src/main/scala/Design.scala:2881:23
    .io_s_axi_awready (io_axi_s_axi_awready),
    .io_s_axi_wready  (io_axi_s_axi_wready),
    .io_s_axi_arready (io_axi_s_axi_arready),
    .io_s_axi_bvalid  (io_axi_s_axi_bvalid),
    .io_s_axi_bresp   (io_axi_s_axi_bresp),
    .io_s_axi_rvalid  (io_axi_s_axi_rvalid),
    .io_s_axi_rdata   (io_axi_s_axi_rdata),
    .io_s_axi_rresp   (io_axi_s_axi_rresp),
    .io_csr_req_valid (_bridge_io_csr_req_valid),
    .io_csr_write     (_bridge_io_csr_write),
    .io_csr_addr      (_bridge_io_csr_addr),
    .io_csr_wdata     (_bridge_io_csr_wdata),
    .io_csr_wstrb     (_bridge_io_csr_wstrb),
    .io_csr_rsp_ready (_bridge_io_csr_rsp_ready)
  );	// src/main/scala/Design.scala:2851:22
  Fr198Decoder decoder (	// src/main/scala/Design.scala:2881:23
    .clock              (clock),
    .reset              (reset),
    .io_req_valid       (_bridge_io_csr_req_valid),	// src/main/scala/Design.scala:2851:22
    .io_write           (_bridge_io_csr_write),	// src/main/scala/Design.scala:2851:22
    .io_addr            (_bridge_io_csr_addr),	// src/main/scala/Design.scala:2851:22
    .io_wdata           (_bridge_io_csr_wdata),	// src/main/scala/Design.scala:2851:22
    .io_wstrb           (_bridge_io_csr_wstrb),	// src/main/scala/Design.scala:2851:22
    .io_rsp_ready       (_bridge_io_csr_rsp_ready),	// src/main/scala/Design.scala:2851:22
    .io_req_ready       (_decoder_io_req_ready),
    .io_rsp_valid       (_decoder_io_rsp_valid),
    .io_rdata           (_decoder_io_rdata),
    .io_error           (_decoder_io_error),
    .io_uart_req_ready  (_uart_io_req_ready),	// src/main/scala/Design.scala:2797:20
    .io_uart_rsp_valid  (_uart_io_rsp_valid),	// src/main/scala/Design.scala:2797:20
    .io_uart_rdata      (_uart_io_rdata),	// src/main/scala/Design.scala:2797:20
    .io_uart_error      (_uart_io_error),	// src/main/scala/Design.scala:2797:20
    .io_uart_req_valid  (_decoder_io_uart_req_valid),
    .io_uart_write      (_decoder_io_uart_write),
    .io_uart_addr       (_decoder_io_uart_addr),
    .io_uart_wdata      (_decoder_io_uart_wdata),
    .io_uart_wstrb      (_decoder_io_uart_wstrb),
    .io_uart_rsp_ready  (_decoder_io_uart_rsp_ready),
    .io_gpio_req_ready  (_gpio_io_req_ready),	// src/main/scala/Design.scala:2811:20
    .io_gpio_rsp_valid  (_gpio_io_rsp_valid),	// src/main/scala/Design.scala:2811:20
    .io_gpio_rdata      (_gpio_io_rdata),	// src/main/scala/Design.scala:2811:20
    .io_gpio_error      (_gpio_io_error),	// src/main/scala/Design.scala:2811:20
    .io_gpio_req_valid  (_decoder_io_gpio_req_valid),
    .io_gpio_write      (_decoder_io_gpio_write),
    .io_gpio_addr       (_decoder_io_gpio_addr),
    .io_gpio_wdata      (_decoder_io_gpio_wdata),
    .io_gpio_wstrb      (_decoder_io_gpio_wstrb),
    .io_gpio_rsp_ready  (_decoder_io_gpio_rsp_ready),
    .io_timer_req_ready (_timer_io_req_ready),	// src/main/scala/Design.scala:2826:21
    .io_timer_rsp_valid (_timer_io_rsp_valid),	// src/main/scala/Design.scala:2826:21
    .io_timer_rdata     (_timer_io_rdata),	// src/main/scala/Design.scala:2826:21
    .io_timer_error     (_timer_io_error),	// src/main/scala/Design.scala:2826:21
    .io_timer_req_valid (_decoder_io_timer_req_valid),
    .io_timer_write     (_decoder_io_timer_write),
    .io_timer_addr      (_decoder_io_timer_addr),
    .io_timer_wdata     (_decoder_io_timer_wdata),
    .io_timer_wstrb     (_decoder_io_timer_wstrb),
    .io_timer_rsp_ready (_decoder_io_timer_rsp_ready),
    .io_irq_req_ready   (_irq_io_req_ready),	// src/main/scala/Design.scala:2838:19
    .io_irq_rsp_valid   (_irq_io_rsp_valid),	// src/main/scala/Design.scala:2838:19
    .io_irq_rdata       (_irq_io_rdata),	// src/main/scala/Design.scala:2838:19
    .io_irq_error       (_irq_io_error),	// src/main/scala/Design.scala:2838:19
    .io_irq_req_valid   (_decoder_io_irq_req_valid),
    .io_irq_write       (_decoder_io_irq_write),
    .io_irq_addr        (_decoder_io_irq_addr),
    .io_irq_wdata       (_decoder_io_irq_wdata),
    .io_irq_wstrb       (_decoder_io_irq_wstrb),
    .io_irq_rsp_ready   (_decoder_io_irq_rsp_ready)
  );	// src/main/scala/Design.scala:2881:23
endmodule


module Fr198Axi(
 input clk,input aresetn,
 input [15:0] axi_s_axi_awaddr,input [2:0] axi_s_axi_awprot,input axi_s_axi_awvalid,output axi_s_axi_awready,
 input [31:0] axi_s_axi_wdata,input [3:0] axi_s_axi_wstrb,input axi_s_axi_wvalid,output axi_s_axi_wready,
 input axi_s_axi_bready,output axi_s_axi_bvalid,output [1:0] axi_s_axi_bresp,
 input [15:0] axi_s_axi_araddr,input [2:0] axi_s_axi_arprot,input axi_s_axi_arvalid,output axi_s_axi_arready,
 input axi_s_axi_rready,output axi_s_axi_rvalid,output [31:0] axi_s_axi_rdata,output [1:0] axi_s_axi_rresp,
 input u_rx,output u_tx,input [31:0] g_pad_in,output [31:0] g_pad_out,output [31:0] g_pad_oe,output i_irq);
 wire core_reset = ~aresetn;
 Fr198AxiCore core(.clock(clk),.reset(core_reset),.io_axi_s_axi_awaddr(axi_s_axi_awaddr),.io_axi_s_axi_awprot(axi_s_axi_awprot),.io_axi_s_axi_awvalid(axi_s_axi_awvalid),.io_axi_s_axi_wdata(axi_s_axi_wdata),.io_axi_s_axi_wstrb(axi_s_axi_wstrb),.io_axi_s_axi_wvalid(axi_s_axi_wvalid),.io_axi_s_axi_bready(axi_s_axi_bready),.io_axi_s_axi_araddr(axi_s_axi_araddr),.io_axi_s_axi_arprot(axi_s_axi_arprot),.io_axi_s_axi_arvalid(axi_s_axi_arvalid),.io_axi_s_axi_rready(axi_s_axi_rready),.io_axi_s_axi_awready(axi_s_axi_awready),.io_axi_s_axi_wready(axi_s_axi_wready),.io_axi_s_axi_arready(axi_s_axi_arready),.io_axi_s_axi_bvalid(axi_s_axi_bvalid),.io_axi_s_axi_bresp(axi_s_axi_bresp),.io_axi_s_axi_rvalid(axi_s_axi_rvalid),.io_axi_s_axi_rdata(axi_s_axi_rdata),.io_axi_s_axi_rresp(axi_s_axi_rresp),.io_u_rx(u_rx),.io_u_tx(u_tx),.io_g_pad_in(g_pad_in),.io_g_pad_out(g_pad_out),.io_g_pad_oe(g_pad_oe),.io_i_irq(i_irq));
endmodule
